import type { Deity } from '../texts';

export type NameGender = 'boy' | 'girl' | 'any';

export type NameRecord = {
  id: string;
  hi: string;
  latin: string;
  gender: NameGender;
  charanas: readonly number[];
  meaningHi: string;
  meaningEn: string;
  root?: string;
  deityId?: Deity;
  syllableCount: 2 | 3 | 4;
};

/** One per-nakshatra shard file: `names.<NN>-<slug>.json`. */
export type NamkaranShard = {
  nakshatraIndex: number;
  nakshatra: string;
  names: NameRecord[];
};

/** Generated by `scripts/namkaran-build-index.mts`; non-zero charanas only. */
export type NamkaranCharanaCounts = {
  version: 1;
  charana: Record<string, number>;
};

export type NamkaranCorpusManifest = {
  verified: false;
  releaseEligible: false;
  referenceUrls: readonly string[];
  notes: string;
};
