// Generated by scripts/build-widget-backgrounds.mts — do not edit by hand.
// The in-app Widget Gallery's copy of the plates the native widgets bundle.
export const widgetBackgroundImages: Record<string, number> = {
  vedansh_widget_bg_verse_medium: require('./vedansh_widget_bg_verse_medium.jpg'),
  vedansh_widget_bg_verse_large: require('./vedansh_widget_bg_verse_large.jpg'),
  vedansh_widget_bg_verse_small: require('./vedansh_widget_bg_verse_small.jpg'),
  vedansh_widget_bg_panchang_small: require('./vedansh_widget_bg_panchang_small.jpg'),
  vedansh_widget_bg_panchang_medium: require('./vedansh_widget_bg_panchang_medium.jpg'),
  vedansh_widget_bg_panchang_large: require('./vedansh_widget_bg_panchang_large.jpg'),
  vedansh_widget_bg_japam_small: require('./vedansh_widget_bg_japam_small.jpg'),
  vedansh_widget_bg_japam_medium: require('./vedansh_widget_bg_japam_medium.jpg'),
};
