/**
 * The golden corpus (PRD-25 §6 Phase 0). Real questions a household asks, in
 * Devanagari, Hinglish and English, each with the intent it must resolve to and
 * — where it matters — the entity id it must pick. `corpus.test.ts` gates the
 * build: ≥ 85% top-1, and ZERO wrong answers (a wrong answer is a different
 * intent or a different entity than expected; an abstain is a miss, not a wrong).
 *
 * Negatives must NOT answer: `none` for out-of-domain, `declined` for the
 * predictive / personal framing the stance guard (§3.4) refuses.
 *
 * Grow this from the on-device unanswered-question log (§7.2), never by
 * writing questions the resolver already passes.
 */
export type CorpusCase =
  | { q: string; intent: string; slot?: [type: string, id: string] }
  | { q: string; expect: 'none' | 'declined' };

export const CORPUS: readonly CorpusCase[] = [
  /* ---------------- panchang.day ---------------- */
  { q: 'आज की तिथि क्या है', intent: 'panchang.day' },
  { q: 'aaj kaun si tithi hai', intent: 'panchang.day' },
  { q: 'aaj ki tithi', intent: 'panchang.day' },
  { q: 'कल कौन सी तिथि है', intent: 'panchang.day' },
  { q: 'kal kya tithi hai', intent: 'panchang.day' },
  { q: "what is today's tithi", intent: 'panchang.day' },
  { q: 'which tithi is it tomorrow', intent: 'panchang.day' },
  { q: 'आज का पंचांग', intent: 'panchang.day' },
  { q: 'aaj ka nakshatra kya hai', intent: 'panchang.day' },
  { q: 'आज कौन सा नक्षत्र है', intent: 'panchang.day' },
  { q: 'aaj kya hai', intent: 'panchang.day' },
  { q: 'tithi kya hai aaj', intent: 'panchang.day' },

  /* ---------------- muhurat.now ---------------- */
  { q: 'राहु काल कब है', intent: 'muhurat.now' },
  { q: 'rahu kaal kab hai', intent: 'muhurat.now' },
  { q: 'rahukal', intent: 'muhurat.now' },
  { q: 'aaj rahu kaal ka samay', intent: 'muhurat.now' },
  { q: 'कल राहु काल कब है', intent: 'muhurat.now' },
  { q: 'abhi shubh hai kya', intent: 'muhurat.now' },
  { q: 'choghadiya', intent: 'muhurat.now' },
  { q: 'आज का चौघड़िया', intent: 'muhurat.now' },
  { q: 'abhijit muhurat aaj', intent: 'muhurat.now' },
  { q: 'aaj ka muhurat', intent: 'muhurat.now' },
  { q: 'शुभ समय अभी', intent: 'muhurat.now' },
  { q: 'yamganda kab hai', intent: 'muhurat.now' },

  /* ---------------- observance.next ---------------- */
  { q: 'एकादशी कब है', intent: 'observance.next', slot: ['observance', 'class:ekadashi'] },
  { q: 'ekadashi kab hai', intent: 'observance.next', slot: ['observance', 'class:ekadashi'] },
  { q: 'ekadasi kb hai', intent: 'observance.next', slot: ['observance', 'class:ekadashi'] },
  { q: 'when is ekadashi', intent: 'observance.next', slot: ['observance', 'class:ekadashi'] },
  { q: 'agli ekadashi', intent: 'observance.next', slot: ['observance', 'class:ekadashi'] },
  { q: 'कल एकादशी है क्या', intent: 'observance.next', slot: ['observance', 'class:ekadashi'] },
  { q: 'kal ekadashi hai kya', intent: 'observance.next', slot: ['observance', 'class:ekadashi'] },
  { q: 'निर्जला एकादशी कब है', intent: 'observance.next', slot: ['observance', 'nirjala-ekadashi'] },
  { q: 'nirjala ekadashi kab hai', intent: 'observance.next', slot: ['observance', 'nirjala-ekadashi'] },
  { q: 'mokshada ekadashi kab padegi', intent: 'observance.next', slot: ['observance', 'mokshada-ekadashi'] },
  { q: 'शिवरात्रि कब है', intent: 'observance.next', slot: ['observance', 'class:shivaratri'] },
  { q: 'shivratri kab hai', intent: 'observance.next', slot: ['observance', 'class:shivaratri'] },
  { q: 'maha shivaratri kab hai', intent: 'observance.next', slot: ['observance', 'maha-shivaratri'] },
  { q: 'महाशिवरात्रि किस दिन है', intent: 'observance.next', slot: ['observance', 'maha-shivaratri'] },
  { q: 'holi kab hai', intent: 'observance.next', slot: ['observance', 'holi'] },
  { q: 'होली कब है', intent: 'observance.next', slot: ['observance', 'holi'] },
  { q: 'when is diwali', intent: 'observance.next', slot: ['observance', 'diwali'] },
  { q: 'दीवाली कब है', intent: 'observance.next', slot: ['observance', 'diwali'] },
  { q: 'diwali kis tarikh ko hai', intent: 'observance.next', slot: ['observance', 'diwali'] },
  { q: 'pradosh kab hai', intent: 'observance.next', slot: ['observance', 'class:pradosh'] },
  { q: 'प्रदोष व्रत कब है', intent: 'observance.next', slot: ['observance', 'class:pradosh'] },
  { q: 'purnima kab hai', intent: 'observance.next', slot: ['observance', 'class:purnima'] },
  { q: 'पूर्णिमा कब है', intent: 'observance.next', slot: ['observance', 'class:purnima'] },
  { q: 'amavasya kab hai', intent: 'observance.next', slot: ['observance', 'class:amavasya'] },
  { q: 'sankashti chaturthi kab hai', intent: 'observance.next' },
  { q: 'karwa chauth kab hai', intent: 'observance.next', slot: ['observance', 'karwa-chauth'] },
  { q: 'करवा चौथ कब है', intent: 'observance.next', slot: ['observance', 'karwa-chauth'] },
  { q: 'navratri kab se hai', intent: 'observance.next', slot: ['observance', 'class:navratri'] },
  { q: 'नवरात्रि कब है', intent: 'observance.next', slot: ['observance', 'class:navratri'] },
  { q: 'ganesh chaturthi kab hai', intent: 'observance.next', slot: ['observance', 'ganesh-chaturthi'] },
  { q: 'गणेश चतुर्थी कब है', intent: 'observance.next', slot: ['observance', 'ganesh-chaturthi'] },
  { q: 'janmashtami kab hai', intent: 'observance.next', slot: ['observance', 'janmashtami'] },
  { q: 'raksha bandhan kab hai', intent: 'observance.next', slot: ['observance', 'raksha-bandhan'] },
  { q: 'रक्षा बंधन किस दिन है', intent: 'observance.next', slot: ['observance', 'raksha-bandhan'] },
  { q: 'hanuman jayanti kab hai', intent: 'observance.next', slot: ['observance', 'hanuman-jayanti'] },
  { q: 'ram navami kab hai', intent: 'observance.next', slot: ['observance', 'ram-navami'] },
  { q: 'dhanteras kab hai', intent: 'observance.next', slot: ['observance', 'dhanteras'] },
  { q: 'makar sankranti kab hai', intent: 'observance.next' },
  { q: 'satyanarayan vrat kab hai', intent: 'observance.next' },
  { q: 'kal purnima hai kya', intent: 'observance.next', slot: ['observance', 'class:purnima'] },
  { q: 'parso amavasya hai kya', intent: 'observance.next', slot: ['observance', 'class:amavasya'] },

  /* ---------------- vrat.how ---------------- */
  { q: 'एकादशी व्रत कैसे करें', intent: 'vrat.how', slot: ['observance', 'class:ekadashi'] },
  { q: 'ekadashi vrat kaise kare', intent: 'vrat.how', slot: ['observance', 'class:ekadashi'] },
  { q: 'ekadashi ka vrat kaise rakhe', intent: 'vrat.how' },
  { q: 'how to observe ekadashi fast', intent: 'vrat.how' },
  { q: 'nirjala ekadashi vrat vidhi', intent: 'vrat.how', slot: ['observance', 'nirjala-ekadashi'] },
  { q: 'निर्जला एकादशी उपवास कैसे करें', intent: 'vrat.how', slot: ['observance', 'nirjala-ekadashi'] },
  { q: 'pradosh vrat kaise kare', intent: 'vrat.how', slot: ['observance', 'class:pradosh'] },
  { q: 'प्रदोष व्रत के नियम', intent: 'vrat.how', slot: ['observance', 'class:pradosh'] },
  { q: 'sankashti vrat kaise rakhe', intent: 'vrat.how' },
  { q: 'shivratri vrat kaise kare', intent: 'vrat.how', slot: ['observance', 'class:shivaratri'] },
  { q: 'ekadashi parana kab kare', intent: 'vrat.how', slot: ['observance', 'class:ekadashi'] },
  { q: 'janmashtami vrat kaise rakhe', intent: 'vrat.how', slot: ['observance', 'janmashtami'] },

  /* ---------------- vrat.food ---------------- */
  { q: 'एकादशी व्रत में क्या खाएँ', intent: 'vrat.food', slot: ['observance', 'class:ekadashi'] },
  { q: 'ekadashi me kya khaye', intent: 'vrat.food', slot: ['observance', 'class:ekadashi'] },
  { q: 'ekadashi vrat me kya kha sakte hai', intent: 'vrat.food' },
  { q: 'what to eat on ekadashi', intent: 'vrat.food' },
  { q: 'ekadashi me kya nahi khana chahiye', intent: 'vrat.food' },
  { q: 'vrat me kya khaye', intent: 'vrat.food' },
  { q: 'व्रत में क्या खाएँ', intent: 'vrat.food' },
  { q: 'phalahar me kya kha sakte hai', intent: 'vrat.food' },
  { q: 'ekadashi falahar', intent: 'vrat.food' },

  /* ---------------- bhog.offer ---------------- */
  { q: 'गणेश जी को क्या चढ़ाएँ', intent: 'bhog.offer', slot: ['deity', 'ganesha'] },
  { q: 'ganesh ji ko kya chadhaye', intent: 'bhog.offer', slot: ['deity', 'ganesha'] },
  { q: 'ganpati ko kya chadhaye', intent: 'bhog.offer', slot: ['deity', 'ganesha'] },
  { q: 'ganeshji ko kya chadhana chahiye', intent: 'bhog.offer', slot: ['deity', 'ganesha'] },
  { q: 'ganesh ji ka bhog kya hai', intent: 'bhog.offer', slot: ['deity', 'ganesha'] },
  { q: 'ganesha naivedya', intent: 'bhog.offer', slot: ['deity', 'ganesha'] },
  { q: 'what to offer ganesha', intent: 'bhog.offer', slot: ['deity', 'ganesha'] },
  { q: 'bhog for ganpati', intent: 'bhog.offer', slot: ['deity', 'ganesha'] },
  { q: 'गणपति को क्या अर्पण करें', intent: 'bhog.offer', slot: ['deity', 'ganesha'] },
  { q: 'शिव जी को क्या चढ़ाएँ', intent: 'bhog.offer', slot: ['deity', 'shiva'] },
  { q: 'shiv ji ka bhog', intent: 'bhog.offer', slot: ['deity', 'shiva'] },
  { q: 'bholenath ko kya chadhaye', intent: 'bhog.offer', slot: ['deity', 'shiva'] },
  { q: 'mahadev ko kya arpit kare', intent: 'bhog.offer', slot: ['deity', 'shiva'] },
  { q: 'हनुमान जी को क्या चढ़ाएँ', intent: 'bhog.offer', slot: ['deity', 'hanuman'] },
  { q: 'hanuman ji ka bhog kya hai', intent: 'bhog.offer', slot: ['deity', 'hanuman'] },
  { q: 'bajrangbali ko kya chadhaye', intent: 'bhog.offer', slot: ['deity', 'hanuman'] },
  { q: 'कृष्ण जी को क्या चढ़ाएँ', intent: 'bhog.offer', slot: ['deity', 'krishna'] },
  { q: 'kanha ji ka bhog', intent: 'bhog.offer', slot: ['deity', 'krishna'] },
  { q: 'laddu gopal ko kya chadhaye', intent: 'bhog.offer', slot: ['deity', 'krishna'] },
  { q: 'lakshmi ji ko kya chadhaye', intent: 'bhog.offer', slot: ['deity', 'lakshmi'] },
  { q: 'माँ लक्ष्मी का भोग', intent: 'bhog.offer', slot: ['deity', 'lakshmi'] },
  { q: 'durga maa ko kya chadhaye', intent: 'bhog.offer', slot: ['deity', 'durga'] },
  { q: 'navratri me mata ko kya chadhaye', intent: 'bhog.offer' },
  { q: 'satyanarayan bhog', intent: 'bhog.offer' },
  { q: 'karwa chauth ka bhog', intent: 'bhog.offer', slot: ['observance', 'karwa-chauth'] },
  { q: 'janmashtami me kya bhog lagaye', intent: 'bhog.offer', slot: ['observance', 'janmashtami'] },

  /* ---------------- bhog.avoid ---------------- */
  { q: 'गणेश जी को क्या नहीं चढ़ाना चाहिए', intent: 'bhog.avoid', slot: ['deity', 'ganesha'] },
  { q: 'ganesh ji ko kya nahi chadhana chahiye', intent: 'bhog.avoid', slot: ['deity', 'ganesha'] },
  { q: 'ganpati ko kya nahi chadhaye', intent: 'bhog.avoid', slot: ['deity', 'ganesha'] },
  { q: 'what must not be offered to ganesha', intent: 'bhog.avoid', slot: ['deity', 'ganesha'] },
  { q: 'ganesh ji ko tulsi chadhana varjit hai kya', intent: 'bhog.avoid', slot: ['deity', 'ganesha'] },
  { q: 'shiv ji ko kya nahi chadhana', intent: 'bhog.avoid', slot: ['deity', 'shiva'] },
  { q: 'शिव जी को क्या नहीं चढ़ाना चाहिए', intent: 'bhog.avoid', slot: ['deity', 'shiva'] },

  /* ---------------- katha.find ---------------- */
  { q: 'एकादशी की कथा', intent: 'katha.find' },
  { q: 'ekadashi vrat katha', intent: 'katha.find' },
  { q: 'satyanarayan katha', intent: 'katha.find' },
  { q: 'सत्यनारायण की कथा', intent: 'katha.find' },
  { q: 'karwa chauth ki katha', intent: 'katha.find', slot: ['observance', 'karwa-chauth'] },
  { q: 'shivratri katha', intent: 'katha.find' },
  { q: 'story of holi', intent: 'katha.find', slot: ['observance', 'holi'] },
  { q: 'diwali ki kahani', intent: 'katha.find', slot: ['observance', 'diwali'] },
  { q: 'pradosh vrat katha', intent: 'katha.find' },

  /* ---------------- vidhi.how ---------------- */
  { q: 'सत्यनारायण पूजा विधि', intent: 'vidhi.how' },
  { q: 'satyanarayan puja kaise kare', intent: 'vidhi.how' },
  { q: 'satyanarayan puja vidhi', intent: 'vidhi.how' },
  { q: 'करवा चौथ की पूजा कैसे करें', intent: 'vidhi.how', slot: ['observance', 'karwa-chauth'] },
  { q: 'karwa chauth puja vidhi', intent: 'vidhi.how', slot: ['observance', 'karwa-chauth'] },
  { q: 'karwa chauth puja samagri', intent: 'vidhi.how', slot: ['observance', 'karwa-chauth'] },
  { q: 'ganesh chaturthi sthapana kaise kare', intent: 'vidhi.how', slot: ['observance', 'ganesh-chaturthi'] },
  { q: 'गणेश स्थापना की विधि', intent: 'vidhi.how' },
  { q: 'diwali lakshmi puja vidhi', intent: 'vidhi.how' },
  { q: 'दीवाली की पूजा कैसे करें', intent: 'vidhi.how', slot: ['observance', 'diwali'] },
  { q: 'diwali puja me kya chahiye', intent: 'vidhi.how', slot: ['observance', 'diwali'] },
  { q: 'navratri ghatasthapana vidhi', intent: 'vidhi.how' },
  { q: 'shivratri puja kaise kare', intent: 'vidhi.how' },
  { q: 'महाशिवरात्रि पूजा विधि', intent: 'vidhi.how', slot: ['observance', 'maha-shivaratri'] },

  /* ---------------- muhurat.event ---------------- */
  { q: 'गृह प्रवेश का मुहूर्त', intent: 'muhurat.event', slot: ['occasion', 'griha-pravesh'] },
  { q: 'griha pravesh muhurat', intent: 'muhurat.event', slot: ['occasion', 'griha-pravesh'] },
  { q: 'gruh pravesh ka muhurt kab hai', intent: 'muhurat.event', slot: ['occasion', 'griha-pravesh'] },
  { q: 'grih pravesh kab kare', intent: 'muhurat.event', slot: ['occasion', 'griha-pravesh'] },
  { q: 'house warming auspicious date', intent: 'muhurat.event', slot: ['occasion', 'griha-pravesh'] },
  { q: 'naye ghar me kab jaye shubh din', intent: 'muhurat.event', slot: ['occasion', 'griha-pravesh'] },
  { q: 'वाहन खरीदने का मुहूर्त', intent: 'muhurat.event', slot: ['occasion', 'vahan'] },
  { q: 'gadi kharidne ka shubh din', intent: 'muhurat.event', slot: ['occasion', 'vahan'] },
  { q: 'new car muhurat', intent: 'muhurat.event', slot: ['occasion', 'vahan'] },
  { q: 'mundan ka muhurat', intent: 'muhurat.event', slot: ['occasion', 'mundan'] },
  { q: 'मुंडन का शुभ दिन', intent: 'muhurat.event', slot: ['occasion', 'mundan'] },
  { q: 'annaprashan muhurat', intent: 'muhurat.event', slot: ['occasion', 'annaprashan'] },
  { q: 'namkaran ka muhurat', intent: 'muhurat.event', slot: ['occasion', 'namkaran'] },
  { q: 'नामकरण कब करें', intent: 'muhurat.event', slot: ['occasion', 'namkaran'] },
  { q: 'vidyarambh muhurat', intent: 'muhurat.event', slot: ['occasion', 'vidyarambh'] },
  { q: 'bhumi pujan ka muhurat', intent: 'muhurat.event', slot: ['occasion', 'bhumi-pujan'] },
  { q: 'dukan kholne ka shubh din', intent: 'muhurat.event', slot: ['occasion', 'vyapar'] },
  { q: 'vyapar arambh muhurat', intent: 'muhurat.event', slot: ['occasion', 'vyapar'] },
  { q: 'sona kharidne ka muhurat', intent: 'muhurat.event', slot: ['occasion', 'swarna'] },
  { q: 'gold kharidne ka shubh din', intent: 'muhurat.event', slot: ['occasion', 'swarna'] },
  { q: 'property kharidne ka muhurat', intent: 'muhurat.event', slot: ['occasion', 'sampatti'] },
  { q: 'yatra ka muhurat', intent: 'muhurat.event', slot: ['occasion', 'yatra'] },
  { q: 'upanayana muhurat', intent: 'muhurat.event', slot: ['occasion', 'upanayana'] },
  { q: 'janeu ka muhurat', intent: 'muhurat.event', slot: ['occasion', 'upanayana'] },
  { q: 'karnavedha ka shubh din', intent: 'muhurat.event', slot: ['occasion', 'karnavedha'] },

  /* ---------------- vastu.direction ---------------- */
  { q: 'मंदिर किस दिशा में होना चाहिए', intent: 'vastu.direction', slot: ['room', 'puja-room'] },
  { q: 'mandir kis disha me hona chahiye', intent: 'vastu.direction', slot: ['room', 'puja-room'] },
  { q: 'mandir kis taraf rakhe', intent: 'vastu.direction', slot: ['room', 'puja-room'] },
  { q: 'puja room direction', intent: 'vastu.direction', slot: ['room', 'puja-room'] },
  { q: 'पूजा घर किस दिशा में', intent: 'vastu.direction', slot: ['room', 'puja-room'] },
  { q: 'which direction should the mandir face', intent: 'vastu.direction', slot: ['room', 'puja-room'] },
  { q: 'murti kis disha me rakhe', intent: 'vastu.direction', slot: ['room', 'puja-room'] },
  { q: 'रसोई किस दिशा में', intent: 'vastu.direction', slot: ['room', 'kitchen'] },
  { q: 'kitchen kis disha me hona chahiye', intent: 'vastu.direction', slot: ['room', 'kitchen'] },
  { q: 'rasoi kaun si disha me', intent: 'vastu.direction', slot: ['room', 'kitchen'] },
  { q: 'सोते समय सिर किस दिशा में', intent: 'vastu.direction', slot: ['room', 'sleeping'] },
  { q: 'sone ki disha konsi honi chahiye', intent: 'vastu.direction', slot: ['room', 'sleeping'] },
  { q: 'sote samay sir kis taraf', intent: 'vastu.direction', slot: ['room', 'sleeping'] },
  { q: 'which direction to sleep', intent: 'vastu.direction', slot: ['room', 'sleeping'] },
  { q: 'तुलसी किस दिशा में रखें', intent: 'vastu.direction', slot: ['room', 'tulsi'] },
  { q: 'tulsi ka paudha kahan rakhe', intent: 'vastu.direction', slot: ['room', 'tulsi'] },
  { q: 'main door kis disha me', intent: 'vastu.direction', slot: ['room', 'main-door'] },
  { q: 'मुख्य द्वार किस दिशा में', intent: 'vastu.direction', slot: ['room', 'main-door'] },
  { q: 'toilet kis disha me hona chahiye', intent: 'vastu.direction', slot: ['room', 'toilet'] },
  { q: 'शौचालय किस दिशा में', intent: 'vastu.direction', slot: ['room', 'toilet'] },
  { q: 'brahmasthan me kya rakhe vastu', intent: 'vastu.direction', slot: ['room', 'brahmasthan'] },

  /* ---------------- japam.mantra ---------------- */
  { q: 'ॐ नमः शिवाय का जप कैसे करें', intent: 'japam.mantra', slot: ['mantra', 'om-namah-shivaya'] },
  { q: 'om namah shivaya jap', intent: 'japam.mantra', slot: ['mantra', 'om-namah-shivaya'] },
  { q: 'gayatri mantra jap kaise kare', intent: 'japam.mantra', slot: ['mantra', 'gayatri-mantra'] },
  { q: 'गायत्री मंत्र कितनी बार जपें', intent: 'japam.mantra', slot: ['mantra', 'gayatri-mantra'] },
  { q: 'hare krishna mahamantra jap', intent: 'japam.mantra', slot: ['mantra', 'hare-krishna-mahamantra'] },
  { q: 'shiv ji ka jap', intent: 'japam.mantra', slot: ['deity', 'shiva'] },
  { q: 'how to chant om namah shivaya', intent: 'japam.mantra', slot: ['mantra', 'om-namah-shivaya'] },

  /* ---------------- sadhana.progress (context-dependent; corpus runs with one enrolment) ---- */
  { q: 'मेरा संकल्प कितना हुआ', intent: 'sadhana.progress' },
  { q: 'mera sankalp kaun sa din hai', intent: 'sadhana.progress' },
  { q: 'meri sadhana kitne din bache', intent: 'sadhana.progress' },
  { q: 'my sankalp progress', intent: 'sadhana.progress' },

  /* ---------------- negatives: out of domain → content search ---------------- */
  { q: 'what is karma', expect: 'none' },
  { q: 'karma kya hai', expect: 'none' },
  { q: 'hanuman chalisa', expect: 'none' },
  { q: 'कर्मण्येवाधिकारस्ते', expect: 'none' },
  { q: 'bhagavad gita chapter 2', expect: 'none' },
  { q: 'moksha kaise milta hai', expect: 'none' },
  { q: 'god exists?', expect: 'none' },
  { q: 'sundarkand', expect: 'none' },

  /* ---------------- negatives: stance guard → declined ---------------- */
  { q: 'kya mujhe naukri milegi', expect: 'declined' },
  { q: 'meri shadi kab hogi', expect: 'declined' },
  { q: 'mera bhavishya kya hai', expect: 'declined' },
  { q: 'will i get the job', expect: 'declined' },
  { q: 'kya mere kundali me dosh hai kya', expect: 'declined' },
  { q: 'will my business grow', expect: 'declined' },
  { q: 'meri kismat kaisi hai', expect: 'declined' },
  { q: 'exam me pass hounga kya', expect: 'declined' },
  { q: 'promotion milega kya', expect: 'declined' },
  { q: 'kal lottery lagegi kya', expect: 'declined' },
];
