/**
 * Hand-curated surface forms the registries and the transliterator cannot
 * produce — honorifics, regional names, common Hinglish spellings. This is the
 * ONLY hand-maintained vocabulary in `src/ask/`; everything else in the
 * lexicon is derived from code (PRD-25 §4.3).
 *
 * Grow it from the on-device unanswered-question log (§7.2), one release at a
 * time. Every alias must point at an id that exists — `lexicon.test.ts` fails
 * a dangling one.
 */
import type { EntityType } from './types';

export type Alias = readonly [form: string, type: EntityType, id: string];

export const ALIASES: readonly Alias[] = [
  // deities
  ['bajrangbali', 'deity', 'hanuman'],
  ['bajrang bali', 'deity', 'hanuman'],
  ['hanumanji', 'deity', 'hanuman'],
  ['maruti', 'deity', 'hanuman'],
  ['pavanputra', 'deity', 'hanuman'],
  ['shivji', 'deity', 'shiva'],
  ['bholenath', 'deity', 'shiva'],
  ['mahadev', 'deity', 'shiva'],
  ['shankar', 'deity', 'shiva'],
  ['ganpati', 'deity', 'ganesha'],
  ['ganapati', 'deity', 'ganesha'],
  ['vinayak', 'deity', 'ganesha'],
  ['lambodar', 'deity', 'ganesha'],
  ['kanha', 'deity', 'krishna'],
  ['gopal', 'deity', 'krishna'],
  ['laddu gopal', 'deity', 'krishna'],
  ['ram ji', 'deity', 'rama'],
  ['ramji', 'deity', 'rama'],
  ['raghunath', 'deity', 'rama'],
  ['durga maa', 'deity', 'durga'],
  ['mata rani', 'deity', 'durga'],
  ['ambe', 'deity', 'durga'],
  ['lakshmi ji', 'deity', 'lakshmi'],
  ['laxmi', 'deity', 'lakshmi'],
  ['mahalakshmi', 'deity', 'lakshmi'],
  ['saraswati maa', 'deity', 'saraswati'],
  ['sharda', 'deity', 'saraswati'],
  ['suryadev', 'deity', 'surya'],
  ['surya dev', 'deity', 'surya'],
  ['shani dev', 'deity', 'shani'],
  ['shanidev', 'deity', 'shani'],
  ['shanivar', 'deity', 'shani'],
  ['vishnu ji', 'deity', 'vishnu'],
  ['narayan', 'deity', 'vishnu'],
  ['hari', 'deity', 'vishnu'],

  // occasions (EVENT_RULES)
  ['gruh pravesh', 'occasion', 'griha-pravesh'],
  ['grih pravesh', 'occasion', 'griha-pravesh'],
  ['house warming', 'occasion', 'griha-pravesh'],
  ['housewarming', 'occasion', 'griha-pravesh'],
  ['naye ghar', 'occasion', 'griha-pravesh'],
  ['gadi kharid', 'occasion', 'vahan'],
  ['car kharid', 'occasion', 'vahan'],
  ['new car', 'occasion', 'vahan'],
  ['bike kharid', 'occasion', 'vahan'],
  ['naam rakhna', 'occasion', 'namkaran'],
  ['naming ceremony', 'occasion', 'namkaran'],
  ['mundan sanskar', 'occasion', 'mundan'],
  ['pehli baar anna', 'occasion', 'annaprashan'],
  ['kaan chhedna', 'occasion', 'karnavedha'],
  ['janeu', 'occasion', 'upanayana'],
  ['dukan kholna', 'occasion', 'vyapar'],
  ['dukan', 'occasion', 'vyapar'],
  ['shop', 'occasion', 'vyapar'],
  ['business', 'occasion', 'vyapar'],
  ['business shuru', 'occasion', 'vyapar'],
  ['new business', 'occasion', 'vyapar'],
  ['sona kharid', 'occasion', 'swarna'],
  ['gold kharid', 'occasion', 'swarna'],
  ['jameen kharid', 'occasion', 'sampatti'],
  ['plot kharid', 'occasion', 'sampatti'],
  ['property kharid', 'occasion', 'sampatti'],
  ['neev', 'occasion', 'bhumi-pujan'],
  ['bhoomi pujan', 'occasion', 'bhumi-pujan'],
  ['padhai shuru', 'occasion', 'vidyarambh'],
  ['school shuru', 'occasion', 'vidyarambh'],
  ['safar', 'occasion', 'yatra'],
  ['travel', 'occasion', 'yatra'],

  // observances the registry spells with a prefix or as one word
  ['satyanarayan', 'observance', 'shree-satyanarayan-vrat'],
  ['satyanarayana', 'observance', 'shree-satyanarayan-vrat'],
  ['mahashivratri', 'observance', 'maha-shivaratri'],
  ['mahashivaratri', 'observance', 'maha-shivaratri'],
  ['महाशिवरात्रि', 'observance', 'maha-shivaratri'],
  ['deepavali', 'observance', 'diwali'],
  ['deepawali', 'observance', 'diwali'],
  ['dipavali', 'observance', 'diwali'],
  ['ganesh utsav', 'observance', 'ganesh-chaturthi'],
  ['ganeshotsav', 'observance', 'ganesh-chaturthi'],
  ['rakhi', 'observance', 'raksha-bandhan'],
  ['karva chauth', 'observance', 'karwa-chauth'],

  // vastu rooms
  ['mandir', 'room', 'puja-room'],
  ['puja room', 'room', 'puja-room'],
  ['pooja room', 'room', 'puja-room'],
  ['puja ghar', 'room', 'puja-room'],
  ['pooja ghar', 'room', 'puja-room'],
  ['devghar', 'room', 'puja-room'],
  ['murti', 'room', 'puja-room'],
  ['rasoi', 'room', 'kitchen'],
  ['chulha', 'room', 'kitchen'],
  ['kitchen', 'room', 'kitchen'],
  ['darvaja', 'room', 'main-door'],
  ['darwaza', 'room', 'main-door'],
  ['main door', 'room', 'main-door'],
  ['entrance', 'room', 'main-door'],
  ['mukhya dwar', 'room', 'main-door'],
  ['sone ki', 'room', 'sleeping'],
  ['sone ka', 'room', 'sleeping'],
  ['sote samay', 'room', 'sleeping'],
  ['sir kis', 'room', 'sleeping'],
  ['bedroom', 'room', 'sleeping'],
  ['sleeping', 'room', 'sleeping'],
  ['sleep', 'room', 'sleeping'],
  ['head direction', 'room', 'sleeping'],
  ['tulsi', 'room', 'tulsi'],
  ['tulsi ka paudha', 'room', 'tulsi'],
  ['toilet', 'room', 'toilet'],
  ['bathroom', 'room', 'toilet'],
  ['shauchalay', 'room', 'toilet'],
  ['brahmasthan', 'room', 'brahmasthan'],
  ['ghar ka center', 'room', 'brahmasthan'],
  ['ghar ka madhya', 'room', 'brahmasthan'],
] as const;
