// GENERATED by scripts/gen-route-graph.mts — do not edit by hand.
//
// For each route, the routes its screen can open. Used ONLY to order the
// background warm-up (see `screenPrefetch.prioritise`): arriving somewhere
// pushes its children to the front of the queue so the next tap is already warm.
//
// Ordering-only means a stale or missing edge is harmless — that screen simply
// gets warmed by the ordinary breadth-first walk instead. Kept honest by
// `__tests__/routeGraph.test.ts`.

export const routeGraph: Readonly<Record<string, readonly string[]>> = {
  "AbujhDays": ["MuhuratDetail"],
  "BajrangBaanChapters": ["BajrangBaanReader"],
  "BrowseByPurpose": ["PurposeList"],
  "DaanDirectory": ["DaanDirectoryDetail"],
  "DaanDirectoryDetail": ["DaanEntry", "DaanKatha"],
  "DaanJourney": ["DaanDirectory", "DaanEntry", "DaanKatha"],
  "DaanKatha": ["DaanEntry", "DaanJourney"],
  "DaanLedger": ["DaanEntry", "DaanKatha"],
  "DaanPunya": ["DaanDirectory", "DaanJourney", "DaanKatha", "DaanLedger"],
  "DeityIndex": ["DeityDetail"],
  "DurgaStotramChapters": ["DurgaStotramReader"],
  "GaneshStotramChapters": ["GaneshStotramReader"],
  "GharVastu": ["GharVastuSetup"],
  "GharVastuRoster": ["GharVastu", "GharVastuCompare", "GharVastuSetup"],
  "GharVastuSetup": ["GharVastu"],
  "GitaChapters": ["GitaReader"],
  "Gochar": ["Kundali"],
  "HanumanAshtakChapters": ["HanumanAshtakReader"],
  "Home": ["BrowseByPurpose", "CategoryList", "DaanPunya", "DeityIndex", "RoutineToday", "SadhanaPrograms", "Search", "TheerthMap", "TodayVidhan", "VidhiCatalog"],
  "JanmaTithiList": ["JanmaTithiDetail", "PitruSmaranDetail"],
  "KrishnaStotramChapters": ["KrishnaStotramReader"],
  "KulParampara": ["KulParamparaEdit", "KulParamparaExport"],
  "Kundali": ["KundaliReport"],
  "KundaliReport": ["Kundali"],
  "MoreHome": ["DaanPunya", "JanmaTithiList", "JapamAlarms", "KulParampara", "PitruSmaranList", "Profile", "Reminders", "VastuDisha", "WidgetGallery", "Wishlist"],
  "MuhuratDayDetail": ["MuhuratDetail"],
  "MuhuratFinder": ["AbujhDays", "MuhuratResults"],
  "MuhuratResults": ["GharVastu", "GharVastuSetup", "Kundali", "MuhuratDayDetail", "PanchangHome", "VastuDisha"],
  "MyVrat": ["MuhuratDayDetail", "ObservanceDetail"],
  "Namkaran": ["NamkaranRashi", "NamkaranResult"],
  "NamkaranRashi": ["NamkaranResult"],
  "NamkaranResult": ["MuhuratResults", "NamkaranRashi"],
  "ObservanceDetail": ["DaanJourney", "MyVrat", "VidhiDetail"],
  "ObservanceList": ["ObservanceDetail"],
  "PanchangHome": ["Gochar", "GunaMilan", "KathaLibrary", "Kundali", "MuhuratDetail", "MuhuratFinder", "MyVrat", "Namkaran", "ObservanceDetail", "ObservanceList", "Rashifal", "VidhiCatalog", "VidhiDetail"],
  "PitruKatha": ["GitaReader"],
  "PitruPakshaOverview": ["PitruPakshaShiksha", "PitruParichayReader", "PitruSmaranDetail", "PitruSmaranList", "VidhiDetail"],
  "PitruPakshaShiksha": ["GitaReader", "PitruKatha", "PitruPakshaOverview", "PitruParichayReader", "PitruSmaranList", "VidhiDetail"],
  "PitruSmaranDetail": ["PitruSmaranEdit", "VidhiDetail"],
  "PitruSmaranList": ["PitruPakshaOverview", "PitruSmaranDetail", "PitruSmaranEdit"],
  "PurposeList": ["DaanPunya"],
  "RamcharitmanasChapters": ["RamcharitmanasReader"],
  "RamStutiChapters": ["RamStutiReader"],
  "Rashifal": ["Kundali"],
  "RoutineAddItems": ["RoutineToday"],
  "RoutineCreate": ["RoutineAddItems", "SadhanaPrograms"],
  "RoutineDetail": ["RoutineAddItems"],
  "RoutineList": ["RoutineCreate", "RoutineDetail", "SadhanaPrograms"],
  "RoutineToday": ["RoutineList", "SadhanaPrograms"],
  "SadhanaProgramDetail": ["RoutineToday"],
  "SadhanaPrograms": ["SadhanaProgramDetail"],
  "SaraswatiStotramChapters": ["SaraswatiStotramReader"],
  "Search": ["DeityList", "TodayVidhan", "VidhiDetail"],
  "ShivaStrotamChapters": ["ShivaStrotamReader"],
  "SundarkandChapters": ["SundarkandReader"],
  "TheerthMap": ["TheerthDetail"],
  "TodayVidhan": ["Search"],
  "ValmikiRamayanChapters": ["ValmikiRamayanReader"],
  "VastuDisha": ["GharVastuRoster", "GharVastuSetup"],
  "VidhiCatalog": ["VidhiDetail"],
  "VidhiDetail": ["VidhiConduct"],
  "VishnuSahasranamaChapters": ["VishnuSahasranamaReader"],
};

/** Routes reachable in one tap from `route`. */
export function childRoutes(route: string | undefined): readonly string[] {
  return route ? routeGraph[route] ?? [] : [];
}
