import type { FestivalRule } from './types';

export const FESTIVAL_RULES: FestivalRule[] = [
  { id: 'makar-sankranti', nameHi: 'मकर संक्रांति', nameEn: 'Makar Sankranti', lunarMonth: 10, paksha: 'krishna', tithi: 1, marker: 'star' },
  { id: 'vasant-panchami', nameHi: 'वसंत पंचमी', nameEn: 'Vasant Panchami', lunarMonth: 11, paksha: 'shukla', tithi: 5, marker: 'star' },
  { id: 'maha-shivaratri', nameHi: 'महा शिवरात्रि', nameEn: 'Maha Shivaratri', lunarMonth: 11, paksha: 'krishna', tithi: 14, marker: 'star', linkSectionId: 'shiv-chalisa' },
  { id: 'holi', nameHi: 'होली', nameEn: 'Holi', lunarMonth: 12, paksha: 'shukla', tithi: 15, marker: 'star' },
  { id: 'ram-navami', nameHi: 'राम नवमी', nameEn: 'Ram Navami', lunarMonth: 1, paksha: 'shukla', tithi: 9, marker: 'star', linkSectionId: 'ram-stuti' },
  { id: 'hanuman-jayanti', nameHi: 'हनुमान जयंती', nameEn: 'Hanuman Jayanti', lunarMonth: 1, paksha: 'shukla', tithi: 15, marker: 'star', linkSectionId: 'hanuman-chalisa' },
  { id: 'akshaya-tritiya', nameHi: 'अक्षय तृतीया', nameEn: 'Akshaya Tritiya', lunarMonth: 2, paksha: 'shukla', tithi: 3, marker: 'star' },
  { id: 'guru-purnima', nameHi: 'गुरु पूर्णिमा', nameEn: 'Guru Purnima', lunarMonth: 4, paksha: 'shukla', tithi: 15, marker: 'star' },
  { id: 'raksha-bandhan', nameHi: 'रक्षा बंधन', nameEn: 'Raksha Bandhan', lunarMonth: 5, paksha: 'shukla', tithi: 15, marker: 'star' },
  { id: 'janmashtami', nameHi: 'जन्माष्टमी', nameEn: 'Janmashtami', lunarMonth: 5, paksha: 'krishna', tithi: 8, marker: 'star' },
  { id: 'ganesh-chaturthi', nameHi: 'गणेश चतुर्थी', nameEn: 'Ganesh Chaturthi', lunarMonth: 6, paksha: 'shukla', tithi: 4, marker: 'star', linkSectionId: 'ganesh-chalisa' },
  { id: 'navratri-start', nameHi: 'नवरात्रि प्रारंभ', nameEn: 'Navratri Begins', lunarMonth: 7, paksha: 'shukla', tithi: 1, marker: 'star', linkSectionId: 'durga-stotram' },
  { id: 'dussehra', nameHi: 'दशहरा', nameEn: 'Dussehra', lunarMonth: 7, paksha: 'shukla', tithi: 10, marker: 'star' },
  { id: 'karwa-chauth', nameHi: 'करवा चौथ', nameEn: 'Karwa Chauth', lunarMonth: 8, paksha: 'krishna', tithi: 4, marker: 'star' },
  { id: 'diwali', nameHi: 'दीपावली', nameEn: 'Diwali', lunarMonth: 8, paksha: 'krishna', tithi: 15, marker: 'star' },
  { id: 'govardhan-puja', nameHi: 'गोवर्धन पूजा', nameEn: 'Govardhan Puja', lunarMonth: 8, paksha: 'shukla', tithi: 1, marker: 'star' },
  { id: 'bhai-dooj', nameHi: 'भाई दूज', nameEn: 'Bhai Dooj', lunarMonth: 8, paksha: 'shukla', tithi: 2, marker: 'star' },
  { id: 'dev-uthani-ekadashi', nameHi: 'देव उठनी एकादशी', nameEn: 'Dev Uthani Ekadashi', lunarMonth: 8, paksha: 'shukla', tithi: 11, marker: 'dot' },
];

export const EKADASHI_NAMES: { lunarMonth: number; paksha: 'shukla' | 'krishna'; nameHi: string; nameEn: string }[] = [
  { lunarMonth: 1, paksha: 'shukla', nameHi: 'कामदा एकादशी', nameEn: 'Kamada Ekadashi' },
  { lunarMonth: 1, paksha: 'krishna', nameHi: 'वरूथिनी एकादशी', nameEn: 'Varuthini Ekadashi' },
  { lunarMonth: 2, paksha: 'shukla', nameHi: 'मोहिनी एकादशी', nameEn: 'Mohini Ekadashi' },
  { lunarMonth: 2, paksha: 'krishna', nameHi: 'अपरा एकादशी', nameEn: 'Apara Ekadashi' },
  { lunarMonth: 3, paksha: 'shukla', nameHi: 'निर्जला एकादशी', nameEn: 'Nirjala Ekadashi' },
  { lunarMonth: 3, paksha: 'krishna', nameHi: 'योगिनी एकादशी', nameEn: 'Yogini Ekadashi' },
  { lunarMonth: 4, paksha: 'shukla', nameHi: 'देवशयनी एकादशी', nameEn: 'Devshayani Ekadashi' },
  { lunarMonth: 4, paksha: 'krishna', nameHi: 'कामिका एकादशी', nameEn: 'Kamika Ekadashi' },
  { lunarMonth: 5, paksha: 'shukla', nameHi: 'पुत्रदा एकादशी', nameEn: 'Putrada Ekadashi' },
  { lunarMonth: 5, paksha: 'krishna', nameHi: 'अजा एकादशी', nameEn: 'Aja Ekadashi' },
  { lunarMonth: 6, paksha: 'shukla', nameHi: 'परिवर्तिनी एकादशी', nameEn: 'Parivartini Ekadashi' },
  { lunarMonth: 6, paksha: 'krishna', nameHi: 'इन्दिरा एकादशी', nameEn: 'Indira Ekadashi' },
  { lunarMonth: 7, paksha: 'shukla', nameHi: 'पापांकुशा एकादशी', nameEn: 'Papankusha Ekadashi' },
  { lunarMonth: 7, paksha: 'krishna', nameHi: 'रमा एकादशी', nameEn: 'Rama Ekadashi' },
  { lunarMonth: 8, paksha: 'shukla', nameHi: 'देव उठनी एकादशी', nameEn: 'Dev Uthani Ekadashi' },
  { lunarMonth: 8, paksha: 'krishna', nameHi: 'उत्पन्ना एकादशी', nameEn: 'Utpanna Ekadashi' },
  { lunarMonth: 9, paksha: 'shukla', nameHi: 'मोक्षदा एकादशी', nameEn: 'Mokshada Ekadashi' },
  { lunarMonth: 9, paksha: 'krishna', nameHi: 'सफला एकादशी', nameEn: 'Saphala Ekadashi' },
  { lunarMonth: 10, paksha: 'shukla', nameHi: 'पुत्रदा एकादशी', nameEn: 'Putrada Ekadashi' },
  { lunarMonth: 10, paksha: 'krishna', nameHi: 'षटतिला एकादशी', nameEn: 'Shattila Ekadashi' },
  { lunarMonth: 11, paksha: 'shukla', nameHi: 'जया एकादशी', nameEn: 'Jaya Ekadashi' },
  { lunarMonth: 11, paksha: 'krishna', nameHi: 'विजया एकादशी', nameEn: 'Vijaya Ekadashi' },
  { lunarMonth: 12, paksha: 'shukla', nameHi: 'आमलकी एकादशी', nameEn: 'Amalaki Ekadashi' },
  { lunarMonth: 12, paksha: 'krishna', nameHi: 'पापमोचनी एकादशी', nameEn: 'Papmochani Ekadashi' },
];
