import { GRAHA_NAMES_EN, GRAHA_NAMES_HI, GRAHA_ORDER } from './kundali';
import { COMBUSTION_ORB_DEG } from './kundaliBasis';
import {
  BHAVA_PLAIN,
  COMBUST_NOTE,
  FACTOR_REASON,
  GRAHA_BHAVA_READINGS,
  GRAHA_PLAIN,
  GRAHA_READING_REVIEW,
  GRAHA_SECTION_COPY,
  GRAHA_UPAY,
  MANTRA_COUNT,
  RETROGRADE_NOTE,
  SIGN_STRENGTH,
  TONE_LABEL,
  TONE_LINE,
  UPAY_INTRO,
  type GrahaFactorId,
} from './grahaReadingContent';
import { BHAVA_ORDINAL_HI, ordinalEn } from './reportFormat';

/**
 * The jyotishi review sheet for the graha cards (RULEBOOK §14.7.7) — every
 * reviewable string, rendered from the tables so the sheet can never drift
 * from what the app shows. `npm run export:graha-review` writes it to
 * docs/reviews/graha-readings-jyotishi-review.md; an engine test fails when
 * the committed sheet is stale. Not imported by the app.
 */

function cell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

const FACTOR_ORDER: readonly GrahaFactorId[] = [
  'sign-exalted',
  'sign-own',
  'sign-friend',
  'sign-enemy',
  'sign-debilitated',
  'house-digbala',
  'house-gains',
  'house-benefic-strong',
  'house-malefic-growth',
  'house-benefic-dusthana',
  'house-malefic-hidden',
  'lord-lagna',
  'lord-yogakaraka',
  'lord-trikona',
  'lord-demanding',
  'combust',
];

export function renderGrahaReviewSheet(): string {
  const lines: string[] = [];
  const push = (...rows: string[]) => lines.push(...rows);

  push('# नवग्रह विवेचन — jyotishi review sheet');
  push('');
  push('<!-- Generated by `npm run export:graha-review` from mobile/src/panchang/grahaReadingContent.ts. Do not edit by hand: edit the tables, then regenerate. -->');
  push('');
  push(`**Status:** ${GRAHA_READING_REVIEW.status}${GRAHA_READING_REVIEW.signOffRef ? ` · sign-off ${GRAHA_READING_REVIEW.signOffRef}` : ''}${GRAHA_READING_REVIEW.reviewedOn ? ` · ${GRAHA_READING_REVIEW.reviewedOn}` : ''}`);
  push('');
  push(`**Scope:** ${GRAHA_READING_REVIEW.scope}.`);
  push('');
  push('## How to review');
  push('');
  push('1. Read each graha table. For every house row, tick **OK** or write the correction in **Notes** — wording, classical accuracy, and tone (plain words, no fear, no event or illness, no fate).');
  push('2. Check the upay row for each graha: day, daan, seva, beej mantra and the paath.');
  push('3. Check the label convention in `docs/roadmap/conventions/graha-reading-v1.md` and the reason lines below.');
  push('4. Sign off at the end. The app shows these cards in store builds only after the sign-off reference and date are recorded in `GRAHA_READING_REVIEW`.');
  push('');
  push('Every card is built as: **name and meaning → house and life areas → sign and strength → label (why) → what it gives → where to take care → houses it rules for the Lagna → upay**.');
  push('');

  push('## Section copy');
  push('');
  push('| Hindi | English | OK | Notes |');
  push('|---|---|---|---|');
  push(`| ${cell(GRAHA_SECTION_COPY.title.hi)} | ${cell(GRAHA_SECTION_COPY.title.en)} | ☐ | |`);
  for (const paragraph of GRAHA_SECTION_COPY.body) push(`| ${cell(paragraph.hi)} | ${cell(paragraph.en)} | ☐ | |`);
  push('');

  push('## What each graha stands for');
  push('');
  push('| Graha | Hindi | English | OK | Notes |');
  push('|---|---|---|---|---|');
  for (const graha of GRAHA_ORDER) {
    const plain = GRAHA_PLAIN[graha];
    push(`| ${plain.nameHi} · ${plain.nameEn} | ${cell(plain.meaningHi)} | ${cell(plain.meaningEn)} | ☐ | |`);
  }
  push('');

  push('## What each house covers');
  push('');
  push('| House | Hindi | English | OK | Notes |');
  push('|---|---|---|---|---|');
  BHAVA_PLAIN.forEach((house, index) => {
    push(`| ${BHAVA_ORDINAL_HI[index]} · ${ordinalEn(index + 1)} | ${cell(house.hi)} | ${cell(house.en)} | ☐ | |`);
  });
  push('');

  push('## Strength words');
  push('');
  push('| Key | Hindi | English | OK | Notes |');
  push('|---|---|---|---|---|');
  for (const [key, phrase] of Object.entries(SIGN_STRENGTH)) push(`| ${key} | ${cell(phrase.hi)} | ${cell(phrase.en)} | ☐ | |`);
  push(`| retrograde | ${cell(RETROGRADE_NOTE.hi)} | ${cell(RETROGRADE_NOTE.en)} | ☐ | |`);
  push(`| combust | ${cell(COMBUST_NOTE.hi)} | ${cell(COMBUST_NOTE.en)} | ☐ | |`);
  push('');
  push(`Combustion orbs (degrees from the Sun): ${Object.entries(COMBUSTION_ORB_DEG).map(([graha, orb]) => `${GRAHA_NAMES_EN[graha as keyof typeof GRAHA_NAMES_EN]} ${orb}°`).join(', ')}.`);
  push('');

  push('## Labels and the reasons behind them');
  push('');
  push('| Label | Hindi | English | OK | Notes |');
  push('|---|---|---|---|---|');
  for (const tone of ['supportive', 'mixed', 'care'] as const) {
    push(`| ${tone} | ${cell(`${TONE_LABEL[tone].hi} — ${TONE_LINE[tone].hi}`)} | ${cell(`${TONE_LABEL[tone].en} — ${TONE_LINE[tone].en}`)} | ☐ | |`);
  }
  push(`| mixed, no vote | ${cell(TONE_LINE.quiet.hi)} | ${cell(TONE_LINE.quiet.en)} | ☐ | |`);
  push('');
  push('Reason lines as they read on a card (sample values: Guru, the 4th house; Jupiter ruling the 9th and 12th; 6° from the Sun):');
  push('');
  push('| Reason | Hindi | English | OK | Notes |');
  push('|---|---|---|---|---|');
  for (const id of FACTOR_ORDER) {
    const text = FACTOR_REASON[id]({
      grahaHi: 'गुरु',
      grahaEn: 'Jupiter',
      houseHi: 'चतुर्थ भाव',
      houseEn: '4th house',
      ruledHi: 'नवम भाव (भाग्य और धर्म)',
      ruledEn: '9th house (fortune and dharma)',
      degreesFromSun: 6,
    });
    push(`| ${id} | ${cell(text.hi)} | ${cell(text.en)} | ☐ | |`);
  }
  push('');

  for (const graha of GRAHA_ORDER) {
    const plain = GRAHA_PLAIN[graha];
    const upay = GRAHA_UPAY[graha];
    push(`## ${GRAHA_NAMES_HI[graha]} · ${plain.nameEn}`);
    push('');
    push('| House | What it gives (Hindi) | Where to take care (Hindi) | What it gives (English) | Where to take care (English) | OK | Notes |');
    push('|---|---|---|---|---|---|---|');
    GRAHA_BHAVA_READINGS[graha].forEach((reading, index) => {
      push(
        `| ${BHAVA_ORDINAL_HI[index]} · ${ordinalEn(index + 1)} | ${cell(reading.givesHi)} | ${cell(reading.careHi)} | ${cell(reading.givesEn)} | ${cell(reading.careEn)} | ☐ | |`
      );
    });
    push('');
    push(`**Upay** (shown as “${UPAY_INTRO.keep.en}” on a supportive card, “${UPAY_INTRO.steady.en}” otherwise):`);
    push('');
    push('| Part | Hindi | English | OK | Notes |');
    push('|---|---|---|---|---|');
    push(`| Day | ${upay.vaarHi} | ${upay.vaarEn} | ☐ | |`);
    push(`| Daan | ${cell(upay.daanHi)} | ${cell(upay.daanEn)} | ☐ | |`);
    push(`| Seva | ${cell(upay.sevaHi)} | ${cell(upay.sevaEn)} | ☐ | |`);
    push(`| Mantra | ${upay.mantraHi} — ${MANTRA_COUNT.hi} | ${upay.mantraEn} — ${MANTRA_COUNT.en} | ☐ | |`);
    push(`| Paath | \`${upay.practiceSourceId}\` | \`${upay.practiceSourceId}\` | ☐ | |`);
    push('');
  }

  push('## Open questions for the reviewer');
  push('');
  push('- Rahu and Ketu have no weekday of their own: the draft follows शनिवत् राहु · कुजवत् केतु (Rahu on Saturday, Ketu on Tuesday). Their daan (urad dal and a blanket; a blanket and til) and seva (grain for birds; roti for a dog) are common folk practice — confirm or correct.');
  push('- The cow-fodder seva (gau-gras) sits with Budh on Wednesday, matching the shared vaar-daan table. Some families give it on Friday for Shukra — confirm.');
  push('- The label treats the Moon and Mercury as benefic in every chart (no waxing/waning or association check), and kendra lordship as neutral (no kendradhipati rule). Confirm these simplifications are acceptable for a first version.');
  push('- Combustion uses flat orbs; the retrograde variants for Mercury (12°) and Venus (8°) are not applied.');
  push('');
  push('## Sign-off');
  push('');
  push('Record who reviewed outside the repository — no names or contact details go in code or in this sheet.');
  push('');
  push('- Sign-off reference (review page link or ticket id): ____________________');
  push('- Date (YYYY-MM-DD): ____________________');
  push('- Approved as corrected above: ☐ yes ☐ no');
  push('');
  return lines.join('\n');
}
