import type { PurposeId } from './prashnaPurposes';

export type ReadingText = { hi: string; en: string };
export const readingText = (hi: string, en: string): ReadingText => ({ hi, en });
const T = readingText;
export type PrashnaQuestion = {
  id: string;
  purposeId: PurposeId;
  label: ReadingText;
  actions: readonly ReadingText[];
  caution: ReadingText;
};

/** Editorial decision support. These steps are NOT derived facts about a person. */
const GENERAL: Record<PurposeId, { actions: ReadingText[]; caution: ReadingText }> = {
  naukri: { actions: [T('काम में अपनी मुख्य ज़रूरत लिखें: सीखना, ज़िम्मेदारी या बदलाव।', 'Name your main work priority: learning, responsibility or change.'), T('अगले अवसर में काम और अपेक्षाएँ स्पष्ट करें।', 'Clarify the work and expectations in the next opportunity.')], caution: T('यह विवेचन आपकी नौकरी की वर्तमान स्थिति नहीं जानता। नीचे अपना प्रश्न चुनें।', 'This reading does not know your employment situation. Choose your specific question.') },
  vyapar: { actions: [T('ग्राहक की एक समस्या स्पष्ट शब्दों में लिखें।', 'Describe one customer problem in plain words.'), T('उस विचार को सीमित प्रयोग से परखें और प्रतिक्रिया लिखें।', 'Test the idea with a limited experiment and record the feedback.')], caution: T('कुंडली वास्तविक माँग या लाभ की पुष्टि नहीं करती।', 'A chart does not establish real demand or profitability.') },
  vidya: { actions: [T('एक विषय में देखें कि कठिनाई समझने, याद रखने या अभ्यास में है।', 'For one topic, distinguish difficulty understanding, recalling or practising.'), T('उसी कठिनाई के लिए छोटा अभ्यास चुनें और परिणाम देखें।', 'Choose a small exercise for that difficulty and review the result.')], caution: T('यह क्षमता या परीक्षा के अंकों का माप नहीं है।', 'This is not a measure of ability or exam marks.') },
  dhan: { actions: [T('अपनी नियमित आय और ज़रूरी ख़र्च का स्पष्ट लेखा बनाएँ।', 'Make a clear record of regular income and essential expenses.'), T('बड़े निर्णय से पहले अपनी वास्तविक प्रतिबद्धताएँ समझें।', 'Understand your actual commitments before a major decision.')], caution: T('यह वित्तीय सलाह नहीं है — निवेश का निर्णय अपने सलाहकार से लें।', 'This is not financial advice — discuss investment decisions with your adviser.') },
  vivah: { actions: [T('काम, घर और परिवार को लेकर अपनी अपेक्षाएँ साझा करें।', 'Discuss expectations about work, home and family.'), T('दोनों की प्राथमिकताओं और असहमतियों को समय देकर समझें।', 'Take time to understand both people’s priorities and disagreements.')], caution: T('निर्णय में दोनों व्यक्तियों की सहमति और वास्तविक संबंध सबसे ज़रूरी हैं।', 'Both people’s consent and the real relationship matter most in the decision.') },
  santan: { actions: [T('परिवार से जुड़ी इच्छा और ज़िम्मेदारियों पर खुलकर बात करें।', 'Discuss your wishes and responsibilities around family openly.'), T('व्यावहारिक सहायता और देखभाल की व्यवस्था पर साथ विचार करें।', 'Consider practical support and caregiving arrangements together.')], caution: T('यह संतान होने की सम्भावना या समय नहीं बताता। स्वास्थ्य से जुड़ा प्रश्न चिकित्सक के पास ले जाएँ।', 'This does not assess fertility or predict timing. A health concern goes to a doctor.') },
  swasthya: { actions: [T('नींद, भोजन और विश्राम की दिनचर्या में क्या बदल रहा है, देखें।', 'Notice what is changing in your sleep, meals and rest.'), T('अपनी सुविधा के अनुसार एक सरल नियमित आदत चुनें।', 'Choose one manageable routine that fits your circumstances.')], caution: T('यह स्वास्थ्य का आकलन नहीं है। कोई लक्षण या परेशानी हो तो चिकित्सक की सलाह लें।', 'This is not a health assessment. A symptom or concern goes to a doctor.') },
  yatra: { actions: [T('यात्रा का उद्देश्य और अपनी ज़रूरी व्यवस्थाएँ लिखें।', 'Write down the purpose of travel and the arrangements you need.'), T('समय, दस्तावेज़ और रहने की व्यवस्था की पुष्टि करें।', 'Confirm timing, documents and accommodation.')], caution: T('स्थान बदलने का निर्णय वास्तविक अवसरों और ज़िम्मेदारियों के साथ लें।', 'Consider real opportunities and responsibilities when deciding to relocate.') },
  man: { actions: [T('देखें कि किन परिस्थितियों में मन को आराम मिलता है।', 'Notice which situations help you feel more settled.'), T('किसी विश्वस्त व्यक्ति से बात करने और विश्राम के लिए समय निकालें।', 'Make space for rest and a conversation with someone you trust.')], caution: T('कुंडली मानसिक स्वास्थ्य का आकलन नहीं करती। परेशानी बनी रहे तो योग्य सहायता लें।', 'A chart does not assess mental health. Seek qualified support if distress persists.') },
};

export const PRASHNA_QUESTIONS: readonly PrashnaQuestion[] = [
  { id: 'job-first', purposeId: 'naukri', label: T('पहली नौकरी खोज रहा/रही हूँ', 'Looking for my first job'), actions: [T('अपने कौशल से मेल खाने वाली दो तरह की भूमिकाएँ चुनें।', 'Shortlist two types of roles that match your skills.'), T('हर तरह की भूमिका के लिए अपने काम का एक उदाहरण तैयार करें।', 'Prepare one example of your work for each type of role.'), T('पूछें कि पहले महीने में मार्गदर्शन कौन देगा।', 'Ask who will guide you in your first month.')], caution: T('आवेदन से मिले जवाबों के अनुसार खोज सुधारें; कुंडली चयन की पुष्टि नहीं करती।', 'Adjust your search using application feedback; a chart cannot confirm selection.') },
  { id: 'job-switch', purposeId: 'naukri', label: T('नौकरी बदलने पर विचार है', 'Considering a job switch'), actions: [T('नौकरी बदलने के दो मुख्य कारण लिखें।', 'Write down your two main reasons for changing jobs.'), T('टीम, काम के बोझ और पहले 90 दिनों की अपेक्षाएँ पूछें।', 'Ask about the team, workload and expectations for the first 90 days.'), T('लिखित भूमिका को अपनी ज़रूरतों से मिलाकर देखें।', 'Compare the written role with what you want to change.')], caution: T('केवल पद का नाम नहीं, काम की वास्तविकता और अपना निर्णय-समय भी देखें।', 'Consider the actual work and your decision deadline, as well as the title.') },
  { id: 'job-growth', purposeId: 'naukri', label: T('मौजूदा भूमिका में आगे बढ़ना है', 'Growing in my current role'), actions: [T('तीन हाल के योगदान और उनके परिणाम लिखें।', 'List three recent contributions and their outcomes.'), T('प्रबंधक से अगली भूमिका के मानदंड पूछें।', 'Ask your manager about the criteria for the next role.'), T('एक लक्ष्य और उसकी समीक्षा की तारीख तय करें।', 'Agree on one milestone and a review date.')], caution: T('अधिक काम लेना पदोन्नति का वादा नहीं है; अपेक्षाएँ स्पष्ट करें।', 'Extra work is not a promise of promotion; clarify expectations.') },
  { id: 'study-exam', purposeId: 'vidya', label: T('परीक्षा की तैयारी', 'Preparing for an exam'), actions: [T('एक विषय के प्रश्न बिना नोट्स हल करके देखें।', 'Try answering questions on one topic without notes.'), T('गलतियों को बाँटें: समझ, याद रखना या समय।', 'Separate mistakes into understanding, recall or time.'), T('उसी कठिनाई पर अभ्यास करके फिर तुलना करें।', 'Practise the specific difficulty and compare again.')], caution: GENERAL.vidya.caution },
  { id: 'study-course', purposeId: 'vidya', label: T('विषय या कोर्स चुनना है', 'Choosing a subject or course'), actions: [T('रुचि और प्रवेश की शर्तों से दो कोर्स चुनें।', 'Shortlist two courses using your interests and prerequisites.'), T('हर कोर्स का एक शुरुआती अभ्यास आज़माएँ।', 'Try one introductory task from each course.'), T('वर्तमान छात्र से रोज़ की पढ़ाई के बारे में बात करें।', 'Ask a current student about the daily work.')], caution: T('कुंडली के किसी संकेत से विषय खारिज न करें; अपना अनुभव भी देखें।', 'Do not rule out a subject because of a chart indication; consider your experience.') },
  { id: 'business-start', purposeId: 'vyapar', label: T('नया विचार आज़माना है', 'Testing a new business idea'), actions: [T('ग्राहक की एक समस्या एक वाक्य में लिखें।', 'Describe one customer problem in a sentence.'), T('संभावित ग्राहकों से पूछें कि वे अभी इसे कैसे हल करते हैं।', 'Ask potential customers how they solve it today.'), T('छोटा प्रयोग और उससे सीखने का लक्ष्य तय करें।', 'Define a small pilot and what you want to learn.')], caution: GENERAL.vyapar.caution },
  { id: 'business-partner', purposeId: 'vyapar', label: T('साझेदार जोड़ने पर विचार है', 'Considering a business partner'), actions: [T('नियमित ज़िम्मेदारियाँ किसकी होंगी, लिखें।', 'Write down who will own each recurring responsibility.'), T('असहमति और निर्णयों का तरीका तय करें।', 'Discuss how disagreements and decisions will be handled.'), T('बड़ी प्रतिबद्धता से पहले सीमित काम साथ करके देखें।', 'Try a limited project together before a larger commitment.')], caution: T('अच्छे संबंध स्पष्ट शर्तों और समझौते की उचित पेशेवर समीक्षा का विकल्प नहीं हैं।', 'A friendly relationship does not replace clear terms and appropriate professional review of an agreement.') },
];

export function questionsForPurpose(purposeId: PurposeId): readonly PrashnaQuestion[] {
  return [{ id: 'general', purposeId, label: T('सामान्य मार्गदर्शन', 'General guidance'), ...GENERAL[purposeId] }, ...PRASHNA_QUESTIONS.filter(q => q.purposeId === purposeId)];
}

export function questionForPurpose(purposeId: PurposeId, questionId?: string): PrashnaQuestion {
  const questions = questionsForPurpose(purposeId);
  return questions.find(q => q.id === questionId) ?? questions[0];
}
