// Rajasthan tehsil headquarters — the fine-grained half of the location picker.
// 342 entries covering all 33 revenue districts, appended to CITIES after the
// national list in `locations.ts`; every one is a real town with a stable `rj-` id
// (ids are persisted in AsyncStorage and used as observance-cache keys, so they must
// never be renamed).
//
// Coordinates come from two published datasets, in this order of preference:
//   1. GeoNames gazetteer (`cities.json`, admin1 = 24)
//   2. All-India Pincode Directory sub/head office, then branch office
// Rows were rejected unless they fell inside the Rajasthan bounding box AND inside
// their own district's 2nd-98th percentile office box, which throws out the postal
// rows geocoded onto a same-named place elsewhere in the state. Tehsils with no
// surviving row are deliberately absent rather than approximated.
//
// Elevations are inverse-distance interpolations from 51 published town
// elevations (exact for those towns). Elevation only feeds the horizon-dip term of
// sunrise, where a 100 m error moves sunrise by well under a minute, so this is the
// same "deliberately coarse" contract the national list documents.
import type { City } from './locations';

export const RAJASTHAN_TEHSILS: City[] = [
  // Ajmer
  { id: 'rj-ajmer', nameHi: 'अजमेर', nameEn: 'Ajmer', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 26.4521, longitude: 74.6387, elevation: 486 },
  { id: 'rj-arain', nameHi: 'अरांई', nameEn: 'Arain', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 26.4495, longitude: 75.0392, elevation: 437 },
  { id: 'rj-beawar', nameHi: 'ब्यावर', nameEn: 'Beawar', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 26.1012, longitude: 74.3203, elevation: 439 },
  { id: 'rj-bhinai', nameHi: 'भिनाय', nameEn: 'Bhinai', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 26.0522, longitude: 74.7713, elevation: 441 },
  { id: 'rj-bijainagar', nameHi: 'बिजयनगर', nameEn: 'Bijainagar', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 25.9408, longitude: 74.6578, elevation: 434 },
  { id: 'rj-jawaja', nameHi: 'जवाजा', nameEn: 'Jawaja', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 25.9408, longitude: 74.2061, elevation: 434 },
  { id: 'rj-kekri', nameHi: 'केकड़ी', nameEn: 'Kekri', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 25.9713, longitude: 75.1499, elevation: 380 },
  { id: 'rj-kishangarh', nameHi: 'किशनगढ़', nameEn: 'Kishangarh', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 26.5901, longitude: 74.854, elevation: 428 },
  { id: 'rj-masuda', nameHi: 'मसूदा', nameEn: 'Masuda', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 26.0928, longitude: 74.5098, elevation: 445 },
  { id: 'rj-nasirabad', nameHi: 'नसीराबाद', nameEn: 'Nasirabad', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 26.3047, longitude: 74.7336, elevation: 473 },
  { id: 'rj-pisangan', nameHi: 'पीसांगन', nameEn: 'Pisangan', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 26.3932, longitude: 74.3819, elevation: 480 },
  { id: 'rj-pushkar', nameHi: 'पुष्कर', nameEn: 'Pushkar', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 26.4902, longitude: 74.5521, elevation: 510 },
  { id: 'rj-sarwar', nameHi: 'सरवाड़', nameEn: 'Sarwar', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 26.2425, longitude: 75.1287, elevation: 414 },
  { id: 'rj-sawar', nameHi: 'सांवर', nameEn: 'Sawar', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 25.7557, longitude: 75.2229, elevation: 347 },
  { id: 'rj-tantoti', nameHi: 'टांटोटी', nameEn: 'Tantoti', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 26.1394, longitude: 74.8181, elevation: 449 },
  { id: 'rj-todgarh', nameHi: 'टॉडगढ़', nameEn: 'Todgarh', districtHi: 'अजमेर', districtEn: 'Ajmer', latitude: 25.6911, longitude: 73.9727, elevation: 411 },
  // Alwar
  { id: 'rj-alwar', nameHi: 'अलवर', nameEn: 'Alwar', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.5625, longitude: 76.625, elevation: 271 },
  { id: 'rj-bansur', nameHi: 'बानसूर', nameEn: 'Bansur', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.6833, longitude: 76.3521, elevation: 283 },
  { id: 'rj-barodameo', nameHi: 'बड़ौदामेव', nameEn: 'Barodameo', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.484, longitude: 76.8674, elevation: 270 },
  { id: 'rj-behror', nameHi: 'बहरोड़', nameEn: 'Behror', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.8883, longitude: 76.2811, elevation: 302 },
  { id: 'rj-govindgarh', nameHi: 'गोविंदगढ़', nameEn: 'Govindgarh', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.5042, longitude: 76.9994, elevation: 261 },
  { id: 'rj-kathumar', nameHi: 'कठूमर', nameEn: 'Kathumar', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.3193, longitude: 77.0764, elevation: 235 },
  { id: 'rj-khairthal', nameHi: 'खैरथल', nameEn: 'Khairthal', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.8018, longitude: 76.6422, elevation: 275 },
  { id: 'rj-kishangarh-bas', nameHi: 'किशनगढ़ बास', nameEn: 'Kishangarh Bas', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.8169, longitude: 76.7285, elevation: 275 },
  { id: 'rj-kotkasim', nameHi: 'कोटकासिम', nameEn: 'Kotkasim', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 28.0301, longitude: 76.719, elevation: 285 },
  { id: 'rj-laxmangarh', nameHi: 'लक्ष्मणगढ़', nameEn: 'Laxmangarh', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.8229, longitude: 75.0275, elevation: 366 },
  { id: 'rj-malakhera', nameHi: 'मालाखेड़ा', nameEn: 'Malakhera', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.388, longitude: 76.6275, elevation: 275 },
  { id: 'rj-mundawar', nameHi: 'मुंडावर', nameEn: 'Mundawar', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.8645, longitude: 76.552, elevation: 280 },
  { id: 'rj-neemrana', nameHi: 'नीमराना', nameEn: 'Neemrana', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.9919, longitude: 76.3854, elevation: 299 },
  { id: 'rj-rajgarh-alwar', nameHi: 'राजगढ़', nameEn: 'Rajgarh', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.9397, longitude: 76.0043, elevation: 335 },
  { id: 'rj-ramgarh-alwar', nameHi: 'रामगढ़', nameEn: 'Ramgarh', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.711, longitude: 75.0793, elevation: 405 },
  { id: 'rj-reni', nameHi: 'रेनी', nameEn: 'Reni', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.1869, longitude: 76.7398, elevation: 285 },
  { id: 'rj-shahjahanpur', nameHi: 'शाहजहाँपुर', nameEn: 'Shahjahanpur', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.9974, longitude: 76.4491, elevation: 294 },
  { id: 'rj-thanagazi', nameHi: 'थानागाजी', nameEn: 'Thanagazi', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.4006, longitude: 76.3171, elevation: 293 },
  { id: 'rj-tijara', nameHi: 'तिजारा', nameEn: 'Tijara', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.9341, longitude: 76.8554, elevation: 277 },
  { id: 'rj-umrain', nameHi: 'उमरैण', nameEn: 'Umrain', districtHi: 'अलवर', districtEn: 'Alwar', latitude: 27.5003, longitude: 76.5691, elevation: 273 },
  // Banswara
  { id: 'rj-anandpuri', nameHi: 'आनंदपुरी', nameEn: 'Anandpuri', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.5529, longitude: 74.4493, elevation: 305 },
  { id: 'rj-arthuna', nameHi: 'अर्थूना', nameEn: 'Arthuna', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.4982, longitude: 74.0961, elevation: 307 },
  { id: 'rj-bagidora', nameHi: 'बागीदौरा', nameEn: 'Bagidora', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.4025, longitude: 74.2683, elevation: 310 },
  { id: 'rj-banswara', nameHi: 'बांसवाड़ा', nameEn: 'Banswara', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.5411, longitude: 74.4425, elevation: 302 },
  { id: 'rj-danpur', nameHi: 'दानपुर', nameEn: 'Danpur', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.5134, longitude: 74.7132, elevation: 329 },
  { id: 'rj-gangar-talai', nameHi: 'गांगड़तलाई', nameEn: 'Gangar Talai', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.2604, longitude: 74.1622, elevation: 317 },
  { id: 'rj-garhi', nameHi: 'गढ़ी', nameEn: 'Garhi', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.5901, longitude: 74.1482, elevation: 308 },
  { id: 'rj-ghatol', nameHi: 'घाटोल', nameEn: 'Ghatol', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.7568, longitude: 74.4133, elevation: 330 },
  { id: 'rj-kushalgarh', nameHi: 'कुशलगढ़', nameEn: 'Kushalgarh', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.199, longitude: 74.4507, elevation: 319 },
  { id: 'rj-loharia', nameHi: 'लोहारिया', nameEn: 'Loharia', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.0813, longitude: 74.6796, elevation: 335 },
  { id: 'rj-sajjangarh', nameHi: 'सज्जनगढ़', nameEn: 'Sajjangarh', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.26, longitude: 74.2899, elevation: 315 },
  { id: 'rj-sallopat', nameHi: 'सल्लोपाट', nameEn: 'Sallopat', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.1802, longitude: 74.1644, elevation: 321 },
  { id: 'rj-talwara', nameHi: 'तलवाड़ा', nameEn: 'Talwara', districtHi: 'बांसवाड़ा', districtEn: 'Banswara', latitude: 23.8555, longitude: 73.8776, elevation: 252 },
  // Baran
  { id: 'rj-anta', nameHi: 'अंता', nameEn: 'Anta', districtHi: 'बारां', districtEn: 'Baran', latitude: 25.15, longitude: 76.3, elevation: 274 },
  { id: 'rj-atru', nameHi: 'अटरू', nameEn: 'Atru', districtHi: 'बारां', districtEn: 'Baran', latitude: 24.8769, longitude: 76.6611, elevation: 277 },
  { id: 'rj-baran', nameHi: 'बारां', nameEn: 'Baran', districtHi: 'बारां', districtEn: 'Baran', latitude: 25.1, longitude: 76.5167, elevation: 262 },
  { id: 'rj-chhabra', nameHi: 'छबड़ा', nameEn: 'Chhabra', districtHi: 'बारां', districtEn: 'Baran', latitude: 24.6647, longitude: 76.8438, elevation: 297 },
  { id: 'rj-chhipabarod', nameHi: 'छीपाबड़ौद', nameEn: 'Chhipabarod', districtHi: 'बारां', districtEn: 'Baran', latitude: 24.6236, longitude: 76.7078, elevation: 302 },
  { id: 'rj-harnawada-shahji', nameHi: 'हरनावदा शाहजी', nameEn: 'Harnawada Shahji', districtHi: 'बारां', districtEn: 'Baran', latitude: 24.43, longitude: 76.7, elevation: 312 },
  { id: 'rj-mangrol', nameHi: 'मांगरोल', nameEn: 'Mangrol', districtHi: 'बारां', districtEn: 'Baran', latitude: 25.3306, longitude: 76.5097, elevation: 271 },
  // Barmer
  { id: 'rj-balotra', nameHi: 'बालोतरा', nameEn: 'Balotra', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.8324, longitude: 72.24, elevation: 156 },
  { id: 'rj-barmer', nameHi: 'बाड़मेर', nameEn: 'Barmer', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.7457, longitude: 71.3921, elevation: 227 },
  { id: 'rj-baytoo', nameHi: 'बायतू', nameEn: 'Baytoo', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.8967, longitude: 71.7668, elevation: 216 },
  { id: 'rj-chohtan', nameHi: 'चौहटन', nameEn: 'Chohtan', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.4804, longitude: 71.0691, elevation: 233 },
  { id: 'rj-dhorimanna', nameHi: 'धोरीमन्ना', nameEn: 'Dhorimanna', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.2037, longitude: 71.4369, elevation: 206 },
  { id: 'rj-gadra-road', nameHi: 'गड़रा रोड', nameEn: 'Gadra Road', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.7431, longitude: 70.5414, elevation: 251 },
  { id: 'rj-gudamalani', nameHi: 'गुड़ामालानी', nameEn: 'Gudamalani', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.2553, longitude: 71.7504, elevation: 205 },
  { id: 'rj-pachpadra', nameHi: 'पचपदरा', nameEn: 'Pachpadra', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.9233, longitude: 72.2557, elevation: 164 },
  { id: 'rj-samdari', nameHi: 'समदड़ी', nameEn: 'Samdari', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.813, longitude: 72.5788, elevation: 210 },
  { id: 'rj-sedwa', nameHi: 'सेड़वा', nameEn: 'Sedwa', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.8651, longitude: 71.5494, elevation: 227 },
  { id: 'rj-sheo', nameHi: 'शिव', nameEn: 'Sheo', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 26.1911, longitude: 71.2433, elevation: 236 },
  { id: 'rj-sindhari', nameHi: 'सिणधरी', nameEn: 'Sindhari', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.5649, longitude: 71.9251, elevation: 210 },
  { id: 'rj-siwana', nameHi: 'सिवाना', nameEn: 'Siwana', districtHi: 'बाड़मेर', districtEn: 'Barmer', latitude: 25.6515, longitude: 72.4224, elevation: 194 },
  // Bharatpur
  { id: 'rj-bayana', nameHi: 'बयाना', nameEn: 'Bayana', districtHi: 'भरतपुर', districtEn: 'Bharatpur', latitude: 26.9079, longitude: 77.2899, elevation: 224 },
  { id: 'rj-bharatpur', nameHi: 'भरतपुर', nameEn: 'Bharatpur', districtHi: 'भरतपुर', districtEn: 'Bharatpur', latitude: 27.2173, longitude: 77.4901, elevation: 183 },
  { id: 'rj-bhusawar', nameHi: 'भुसावर', nameEn: 'Bhusawar', districtHi: 'भरतपुर', districtEn: 'Bharatpur', latitude: 27.0389, longitude: 77.0485, elevation: 247 },
  { id: 'rj-deeg', nameHi: 'डीग', nameEn: 'Deeg', districtHi: 'भरतपुर', districtEn: 'Bharatpur', latitude: 27.4745, longitude: 77.328, elevation: 205 },
  { id: 'rj-kaman', nameHi: 'कामां', nameEn: 'Kaman', districtHi: 'भरतपुर', districtEn: 'Bharatpur', latitude: 27.6579, longitude: 77.2691, elevation: 236 },
  { id: 'rj-kumher', nameHi: 'कुम्हेर', nameEn: 'Kumher', districtHi: 'भरतपुर', districtEn: 'Bharatpur', latitude: 27.3166, longitude: 77.3708, elevation: 189 },
  { id: 'rj-nadbai', nameHi: 'नदबई', nameEn: 'Nadbai', districtHi: 'भरतपुर', districtEn: 'Bharatpur', latitude: 27.2229, longitude: 77.1957, elevation: 206 },
  { id: 'rj-nagar', nameHi: 'नगर', nameEn: 'Nagar', districtHi: 'भरतपुर', districtEn: 'Bharatpur', latitude: 27.424, longitude: 77.0992, elevation: 238 },
  { id: 'rj-roopbas', nameHi: 'रूपबास', nameEn: 'Roopbas', districtHi: 'भरतपुर', districtEn: 'Bharatpur', latitude: 26.9951, longitude: 77.5936, elevation: 193 },
  { id: 'rj-weir', nameHi: 'वैर', nameEn: 'Weir', districtHi: 'भरतपुर', districtEn: 'Bharatpur', latitude: 27.0186, longitude: 77.1764, elevation: 224 },
  // Bhilwara
  { id: 'rj-asind', nameHi: 'आसींद', nameEn: 'Asind', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.7342, longitude: 74.3328, elevation: 428 },
  { id: 'rj-badnore', nameHi: 'बदनोर', nameEn: 'Badnore', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.8369, longitude: 74.2822, elevation: 431 },
  { id: 'rj-banera', nameHi: 'बनेड़ा', nameEn: 'Banera', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.5063, longitude: 74.6746, elevation: 419 },
  { id: 'rj-bhilwara', nameHi: 'भीलवाड़ा', nameEn: 'Bhilwara', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.3471, longitude: 74.6408, elevation: 421 },
  { id: 'rj-bijoliya', nameHi: 'बिजौलियां', nameEn: 'Bijoliya', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.1609, longitude: 75.3233, elevation: 319 },
  { id: 'rj-gangapur', nameHi: 'गंगापुर', nameEn: 'Gangapur', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.2195, longitude: 74.2603, elevation: 468 },
  { id: 'rj-gulabpura', nameHi: 'गुलाबपुरा', nameEn: 'Gulabpura', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.9045, longitude: 74.6603, elevation: 431 },
  { id: 'rj-hamirgarh', nameHi: 'हमीरगढ़', nameEn: 'Hamirgarh', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.1877, longitude: 74.6312, elevation: 418 },
  { id: 'rj-hurda', nameHi: 'हुरड़ा', nameEn: 'Hurda', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.9039, longitude: 74.6882, elevation: 430 },
  { id: 'rj-jahazpur', nameHi: 'जहाजपुर', nameEn: 'Jahazpur', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.6199, longitude: 75.2761, elevation: 323 },
  { id: 'rj-kareda', nameHi: 'कारेड़ा', nameEn: 'Kareda', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.5188, longitude: 74.232, elevation: 439 },
  { id: 'rj-kotri', nameHi: 'कोटड़ी', nameEn: 'Kotri', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.3986, longitude: 74.9011, elevation: 408 },
  { id: 'rj-mandal', nameHi: 'मांडल', nameEn: 'Mandal', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.4413, longitude: 74.5698, elevation: 421 },
  { id: 'rj-mandalgarh', nameHi: 'माण्डलगढ़', nameEn: 'Mandalgarh', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.1941, longitude: 75.0721, elevation: 377 },
  { id: 'rj-phulia-kalan', nameHi: 'फूलियाकलां', nameEn: 'Phulia Kalan', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.8229, longitude: 74.9637, elevation: 398 },
  { id: 'rj-sahara', nameHi: 'सहाड़ा', nameEn: 'Sahara', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.1901, longitude: 74.2408, elevation: 478 },
  { id: 'rj-shahpura-bhilwara', nameHi: 'शाहपुरा', nameEn: 'Shahpura', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.6209, longitude: 74.9249, elevation: 398 },
  { id: 'rj-suwana', nameHi: 'सुवाणा', nameEn: 'Suwana', districtHi: 'भीलवाड़ा', districtEn: 'Bhilwara', latitude: 25.3535, longitude: 74.7007, elevation: 420 },
  // Bikaner
  { id: 'rj-bajju', nameHi: 'बज्जू', nameEn: 'Bajju', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 27.9334, longitude: 72.5126, elevation: 263 },
  { id: 'rj-bikaner', nameHi: 'बीकानेर', nameEn: 'Bikaner', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 28.0176, longitude: 73.3149, elevation: 242 },
  { id: 'rj-chhattargarh', nameHi: 'छत्तरगढ़', nameEn: 'Chhattargarh', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 28.0208, longitude: 73.3158, elevation: 243 },
  { id: 'rj-deshnoke', nameHi: 'देशनोक', nameEn: 'Deshnoke', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 27.7984, longitude: 73.343, elevation: 250 },
  { id: 'rj-khajuwala', nameHi: 'खाजूवाला', nameEn: 'Khajuwala', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 28.7044, longitude: 72.5947, elevation: 261 },
  { id: 'rj-kolayat', nameHi: 'कोलायत', nameEn: 'Kolayat', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 27.8381, longitude: 72.9597, elevation: 255 },
  { id: 'rj-lunkaransar', nameHi: 'लूणकरणसर', nameEn: 'Lunkaransar', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 28.4938, longitude: 73.7492, elevation: 262 },
  { id: 'rj-napasar', nameHi: 'नापासर', nameEn: 'Napasar', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 27.9606, longitude: 73.5591, elevation: 250 },
  { id: 'rj-nokha', nameHi: 'नोखा', nameEn: 'Nokha', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 27.5616, longitude: 73.4714, elevation: 288 },
  { id: 'rj-panchu', nameHi: 'पांचू', nameEn: 'Panchu', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 27.9828, longitude: 72.3141, elevation: 265 },
  { id: 'rj-poogal', nameHi: 'पूगल', nameEn: 'Poogal', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 28.4881, longitude: 72.8059, elevation: 259 },
  { id: 'rj-sri-dungargarh', nameHi: 'श्रीडूंगरगढ़', nameEn: 'Sri Dungargarh', districtHi: 'बीकानेर', districtEn: 'Bikaner', latitude: 28.0962, longitude: 74.0087, elevation: 297 },
  // Bundi
  { id: 'rj-bundi', nameHi: 'बूंदी', nameEn: 'Bundi', districtHi: 'बूंदी', districtEn: 'Bundi', latitude: 25.4385, longitude: 75.6373, elevation: 268 },
  { id: 'rj-dabi', nameHi: 'डाबी', nameEn: 'Dabi', districtHi: 'बूंदी', districtEn: 'Bundi', latitude: 25.0969, longitude: 75.5146, elevation: 295 },
  { id: 'rj-dei', nameHi: 'देई', nameEn: 'Dei', districtHi: 'बूंदी', districtEn: 'Bundi', latitude: 25.6782, longitude: 75.9289, elevation: 286 },
  { id: 'rj-hindoli', nameHi: 'हिंडोली', nameEn: 'Hindoli', districtHi: 'बूंदी', districtEn: 'Bundi', latitude: 25.5814, longitude: 75.4989, elevation: 282 },
  { id: 'rj-indergarh', nameHi: 'इंदरगढ़', nameEn: 'Indergarh', districtHi: 'बूंदी', districtEn: 'Bundi', latitude: 25.7282, longitude: 76.1904, elevation: 279 },
  { id: 'rj-keshoraipatan', nameHi: 'केशोरायपाटन', nameEn: 'Keshoraipatan', districtHi: 'बूंदी', districtEn: 'Bundi', latitude: 25.2928, longitude: 75.9395, elevation: 276 },
  { id: 'rj-nainwa', nameHi: 'नैनवां', nameEn: 'Nainwa', districtHi: 'बूंदी', districtEn: 'Bundi', latitude: 25.7715, longitude: 75.8498, elevation: 290 },
  { id: 'rj-talera', nameHi: 'तालेड़ा', nameEn: 'Talera', districtHi: 'बूंदी', districtEn: 'Bundi', latitude: 25.3158, longitude: 75.7328, elevation: 274 },
  // Chittorgarh
  { id: 'rj-bari-sadri', nameHi: 'बड़ीसादड़ी', nameEn: 'Bari Sadri', districtHi: 'चित्तौड़गढ़', districtEn: 'Chittorgarh', latitude: 24.4134, longitude: 74.4733, elevation: 414 },
  { id: 'rj-begun', nameHi: 'बेगूं', nameEn: 'Begun', districtHi: 'चित्तौड़गढ़', districtEn: 'Chittorgarh', latitude: 24.9833, longitude: 75.0, elevation: 390 },
  { id: 'rj-bhadesar', nameHi: 'भदेसर', nameEn: 'Bhadesar', districtHi: 'चित्तौड़गढ़', districtEn: 'Chittorgarh', latitude: 24.6822, longitude: 74.509, elevation: 413 },
  { id: 'rj-bhupalsagar', nameHi: 'भूपालसागर', nameEn: 'Bhupalsagar', districtHi: 'चित्तौड़गढ़', districtEn: 'Chittorgarh', latitude: 24.8467, longitude: 74.2109, elevation: 496 },
  { id: 'rj-chittorgarh', nameHi: 'चित्तौड़गढ़', nameEn: 'Chittorgarh', districtHi: 'चित्तौड़गढ़', districtEn: 'Chittorgarh', latitude: 24.8896, longitude: 74.624, elevation: 394 },
  { id: 'rj-dungla', nameHi: 'डूंगला', nameEn: 'Dungla', districtHi: 'चित्तौड़गढ़', districtEn: 'Chittorgarh', latitude: 24.5071, longitude: 74.3314, elevation: 427 },
  { id: 'rj-gangrar', nameHi: 'गंगरार', nameEn: 'Gangrar', districtHi: 'चित्तौड़गढ़', districtEn: 'Chittorgarh', latitude: 25.0503, longitude: 74.61, elevation: 406 },
  { id: 'rj-kapasan', nameHi: 'कपासन', nameEn: 'Kapasan', districtHi: 'चित्तौड़गढ़', districtEn: 'Chittorgarh', latitude: 24.8894, longitude: 74.3167, elevation: 454 },
  { id: 'rj-nimbahera', nameHi: 'निंबाहेड़ा', nameEn: 'Nimbahera', districtHi: 'चित्तौड़गढ़', districtEn: 'Chittorgarh', latitude: 24.6217, longitude: 74.68, elevation: 408 },
  { id: 'rj-rashmi', nameHi: 'रश्मि', nameEn: 'Rashmi', districtHi: 'चित्तौड़गढ़', districtEn: 'Chittorgarh', latitude: 25.0611, longitude: 74.3591, elevation: 445 },
  { id: 'rj-rawatbhata', nameHi: 'रावतभाटा', nameEn: 'Rawatbhata', districtHi: 'चित्तौड़गढ़', districtEn: 'Chittorgarh', latitude: 24.9298, longitude: 75.5921, elevation: 306 },
  // Churu
  { id: 'rj-bidasar', nameHi: 'बीदासर', nameEn: 'Bidasar', districtHi: 'चूरू', districtEn: 'Churu', latitude: 27.836, longitude: 74.3178, elevation: 333 },
  { id: 'rj-churu', nameHi: 'चूरू', nameEn: 'Churu', districtHi: 'चूरू', districtEn: 'Churu', latitude: 28.3041, longitude: 74.9672, elevation: 292 },
  { id: 'rj-rajgarh-churu', nameHi: 'राजगढ़', nameEn: 'Rajgarh', districtHi: 'चूरू', districtEn: 'Churu', latitude: 28.642, longitude: 75.3861, elevation: 317 },
  { id: 'rj-ratangarh', nameHi: 'रतनगढ़', nameEn: 'Ratangarh', districtHi: 'चूरू', districtEn: 'Churu', latitude: 28.0814, longitude: 74.6185, elevation: 321 },
  { id: 'rj-sadulpur', nameHi: 'सादुलपुर', nameEn: 'Sadulpur', districtHi: 'चूरू', districtEn: 'Churu', latitude: 28.6428, longitude: 75.3866, elevation: 317 },
  { id: 'rj-sardarshahar', nameHi: 'सरदारशहर', nameEn: 'Sardarshahar', districtHi: 'चूरू', districtEn: 'Churu', latitude: 28.4416, longitude: 74.4975, elevation: 305 },
  { id: 'rj-sujangarh', nameHi: 'सुजानगढ़', nameEn: 'Sujangarh', districtHi: 'चूरू', districtEn: 'Churu', latitude: 27.7, longitude: 74.4667, elevation: 349 },
  { id: 'rj-taranagar', nameHi: 'तारानगर', nameEn: 'Taranagar', districtHi: 'चूरू', districtEn: 'Churu', latitude: 28.6686, longitude: 75.0321, elevation: 305 },
  // Dausa
  { id: 'rj-bandikui', nameHi: 'बांदीकुई', nameEn: 'Bandikui', districtHi: 'दौसा', districtEn: 'Dausa', latitude: 27.0509, longitude: 76.5733, elevation: 316 },
  { id: 'rj-baswa', nameHi: 'बसवा', nameEn: 'Baswa', districtHi: 'दौसा', districtEn: 'Dausa', latitude: 27.1496, longitude: 76.5834, elevation: 304 },
  { id: 'rj-dausa', nameHi: 'दौसा', nameEn: 'Dausa', districtHi: 'दौसा', districtEn: 'Dausa', latitude: 26.89, longitude: 76.3358, elevation: 333 },
  { id: 'rj-lalsot', nameHi: 'लालसोट', nameEn: 'Lalsot', districtHi: 'दौसा', districtEn: 'Dausa', latitude: 26.5595, longitude: 76.3291, elevation: 312 },
  { id: 'rj-lawan', nameHi: 'लवाण', nameEn: 'Lawan', districtHi: 'दौसा', districtEn: 'Dausa', latitude: 26.7702, longitude: 76.2131, elevation: 329 },
  { id: 'rj-mahwa', nameHi: 'महुवा', nameEn: 'Mahwa', districtHi: 'दौसा', districtEn: 'Dausa', latitude: 27.0459, longitude: 76.9315, elevation: 267 },
  { id: 'rj-nangal-rajawatan', nameHi: 'नांगल राजावतान', nameEn: 'Nangal Rajawatan', districtHi: 'दौसा', districtEn: 'Dausa', latitude: 26.7513, longitude: 76.3338, elevation: 329 },
  { id: 'rj-ramgarh-pachwara', nameHi: 'रामगढ़ पचवारा', nameEn: 'Ramgarh Pachwara', districtHi: 'दौसा', districtEn: 'Dausa', latitude: 26.6227, longitude: 76.2603, elevation: 320 },
  { id: 'rj-sikrai', nameHi: 'सिकराय', nameEn: 'Sikrai', districtHi: 'दौसा', districtEn: 'Dausa', latitude: 26.9161, longitude: 76.6933, elevation: 308 },
  // Dholpur
  { id: 'rj-bari', nameHi: 'बाड़ी', nameEn: 'Bari', districtHi: 'धौलपुर', districtEn: 'Dholpur', latitude: 26.6466, longitude: 77.6163, elevation: 196 },
  { id: 'rj-dholpur', nameHi: 'धौलपुर', nameEn: 'Dholpur', districtHi: 'धौलपुर', districtEn: 'Dholpur', latitude: 26.6926, longitude: 77.8994, elevation: 177 },
  { id: 'rj-rajakhera', nameHi: 'राजाखेड़ा', nameEn: 'Rajakhera', districtHi: 'धौलपुर', districtEn: 'Dholpur', latitude: 26.898, longitude: 78.171, elevation: 188 },
  { id: 'rj-sarmathura', nameHi: 'सरमथुरा', nameEn: 'Sarmathura', districtHi: 'धौलपुर', districtEn: 'Dholpur', latitude: 26.5134, longitude: 77.3718, elevation: 256 },
  // Dungarpur
  { id: 'rj-aspur', nameHi: 'आसपुर', nameEn: 'Aspur', districtHi: 'डूंगरपुर', districtEn: 'Dungarpur', latitude: 23.9562, longitude: 74.0794, elevation: 297 },
  { id: 'rj-bicchiwara', nameHi: 'बिछीवाड़ा', nameEn: 'Bicchiwara', districtHi: 'डूंगरपुर', districtEn: 'Dungarpur', latitude: 23.7867, longitude: 73.5147, elevation: 254 },
  { id: 'rj-chikhali', nameHi: 'चीखली', nameEn: 'Chikhali', districtHi: 'डूंगरपुर', districtEn: 'Dungarpur', latitude: 23.8507, longitude: 73.71, elevation: 235 },
  { id: 'rj-dovda', nameHi: 'दोवड़ा', nameEn: 'Dovda', districtHi: 'डूंगरपुर', districtEn: 'Dungarpur', latitude: 23.8477, longitude: 73.8626, elevation: 249 },
  { id: 'rj-dungarpur', nameHi: 'डूंगरपुर', nameEn: 'Dungarpur', districtHi: 'डूंगरपुर', districtEn: 'Dungarpur', latitude: 23.8431, longitude: 73.7147, elevation: 220 },
  { id: 'rj-galiakot', nameHi: 'गलियाकोट', nameEn: 'Galiakot', districtHi: 'डूंगरपुर', districtEn: 'Dungarpur', latitude: 23.52, longitude: 74.0203, elevation: 300 },
  { id: 'rj-sabla', nameHi: 'साबला', nameEn: 'Sabla', districtHi: 'डूंगरपुर', districtEn: 'Dungarpur', latitude: 23.8445, longitude: 74.1769, elevation: 312 },
  { id: 'rj-sagwara', nameHi: 'सागवाड़ा', nameEn: 'Sagwara', districtHi: 'डूंगरपुर', districtEn: 'Dungarpur', latitude: 23.6795, longitude: 74.0201, elevation: 287 },
  { id: 'rj-simalwara', nameHi: 'सीमलवाड़ा', nameEn: 'Simalwara', districtHi: 'डूंगरपुर', districtEn: 'Dungarpur', latitude: 23.5698, longitude: 73.7419, elevation: 264 },
  // Sri Ganganagar
  { id: 'rj-anupgarh', nameHi: 'अनूपगढ़', nameEn: 'Anupgarh', districtHi: 'श्रीगंगानगर', districtEn: 'Sri Ganganagar', latitude: 29.1911, longitude: 73.2086, elevation: 210 },
  { id: 'rj-gharsana', nameHi: 'घड़साना', nameEn: 'Gharsana', districtHi: 'श्रीगंगानगर', districtEn: 'Sri Ganganagar', latitude: 29.9035, longitude: 73.8797, elevation: 177 },
  { id: 'rj-kesrisinghpur', nameHi: 'केसरीसिंहपुर', nameEn: 'Kesrisinghpur', districtHi: 'श्रीगंगानगर', districtEn: 'Sri Ganganagar', latitude: 29.9475, longitude: 73.6212, elevation: 179 },
  { id: 'rj-padampur', nameHi: 'पदमपुर', nameEn: 'Padampur', districtHi: 'श्रीगंगानगर', districtEn: 'Sri Ganganagar', latitude: 29.7089, longitude: 73.6254, elevation: 182 },
  { id: 'rj-raisinghnagar', nameHi: 'रायसिंहनगर', nameEn: 'Raisinghnagar', districtHi: 'श्रीगंगानगर', districtEn: 'Sri Ganganagar', latitude: 29.5358, longitude: 73.4492, elevation: 188 },
  { id: 'rj-rawla', nameHi: 'रावला', nameEn: 'Rawla', districtHi: 'श्रीगंगानगर', districtEn: 'Sri Ganganagar', latitude: 28.8384, longitude: 72.8868, elevation: 249 },
  { id: 'rj-sadulshahar', nameHi: 'सादुलशहर', nameEn: 'Sadulshahar', districtHi: 'श्रीगंगानगर', districtEn: 'Sri Ganganagar', latitude: 29.9087, longitude: 74.1757, elevation: 183 },
  { id: 'rj-sri-ganganagar', nameHi: 'श्रीगंगानगर', nameEn: 'Sri Ganganagar', districtHi: 'श्रीगंगानगर', districtEn: 'Sri Ganganagar', latitude: 29.9201, longitude: 73.875, elevation: 176 },
  { id: 'rj-srikaranpur', nameHi: 'श्रीकरणपुर', nameEn: 'Srikaranpur', districtHi: 'श्रीगंगानगर', districtEn: 'Sri Ganganagar', latitude: 29.8422, longitude: 73.4572, elevation: 184 },
  { id: 'rj-suratgarh', nameHi: 'सूरतगढ़', nameEn: 'Suratgarh', districtHi: 'श्रीगंगानगर', districtEn: 'Sri Ganganagar', latitude: 29.3215, longitude: 73.8998, elevation: 175 },
  { id: 'rj-vijaynagar', nameHi: 'श्रीविजयनगर', nameEn: 'Vijaynagar', districtHi: 'श्रीगंगानगर', districtEn: 'Sri Ganganagar', latitude: 29.2397, longitude: 73.5189, elevation: 187 },
  // Hanumangarh
  { id: 'rj-bhadra', nameHi: 'भादरा', nameEn: 'Bhadra', districtHi: 'हनुमानगढ़', districtEn: 'Hanumangarh', latitude: 29.103, longitude: 75.1714, elevation: 280 },
  { id: 'rj-hanumangarh', nameHi: 'हनुमानगढ़', nameEn: 'Hanumangarh', districtHi: 'हनुमानगढ़', districtEn: 'Hanumangarh', latitude: 29.5818, longitude: 74.3294, elevation: 190 },
  { id: 'rj-nohar', nameHi: 'नोहर', nameEn: 'Nohar', districtHi: 'हनुमानगढ़', districtEn: 'Hanumangarh', latitude: 29.1829, longitude: 74.7706, elevation: 232 },
  { id: 'rj-pilibanga', nameHi: 'पीलीबंगा', nameEn: 'Pilibanga', districtHi: 'हनुमानगढ़', districtEn: 'Hanumangarh', latitude: 29.4496, longitude: 74.1009, elevation: 184 },
  { id: 'rj-rawatsar', nameHi: 'रावतसर', nameEn: 'Rawatsar', districtHi: 'हनुमानगढ़', districtEn: 'Hanumangarh', latitude: 29.2672, longitude: 74.4029, elevation: 196 },
  { id: 'rj-sangaria', nameHi: 'संगरिया', nameEn: 'Sangaria', districtHi: 'हनुमानगढ़', districtEn: 'Hanumangarh', latitude: 29.7989, longitude: 74.4668, elevation: 191 },
  { id: 'rj-tibbi', nameHi: 'टिब्बी', nameEn: 'Tibbi', districtHi: 'हनुमानगढ़', districtEn: 'Hanumangarh', latitude: 29.5564, longitude: 74.504, elevation: 191 },
  // Jaipur
  { id: 'rj-amber', nameHi: 'आमेर', nameEn: 'Amber', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 26.983, longitude: 75.8667, elevation: 337 },
  { id: 'rj-bassi', nameHi: 'बस्सी', nameEn: 'Bassi', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 26.9193, longitude: 75.7196, elevation: 348 },
  { id: 'rj-chaksu', nameHi: 'चाकसू', nameEn: 'Chaksu', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 26.6051, longitude: 75.9481, elevation: 318 },
  { id: 'rj-chomu', nameHi: 'चौमूं', nameEn: 'Chomu', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 27.1678, longitude: 75.7103, elevation: 356 },
  { id: 'rj-dudu', nameHi: 'दूदू', nameEn: 'Dudu', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 26.6798, longitude: 75.23, elevation: 415 },
  { id: 'rj-jamwa-ramgarh', nameHi: 'जमवारामगढ़', nameEn: 'Jamwa Ramgarh', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 27.0202, longitude: 76.0109, elevation: 331 },
  { id: 'rj-jobner', nameHi: 'जोबनेर', nameEn: 'Jobner', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 26.9726, longitude: 75.3875, elevation: 385 },
  { id: 'rj-kishangarh-renwal', nameHi: 'किशनगढ़ रेनवाल', nameEn: 'Kishangarh Renwal', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 27.1623, longitude: 75.3579, elevation: 388 },
  { id: 'rj-kotputli', nameHi: 'कोटपूतली', nameEn: 'Kotputli', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 27.7021, longitude: 76.1991, elevation: 302 },
  { id: 'rj-manoharpur', nameHi: 'मनोहरपुर', nameEn: 'Manoharpur', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 27.2977, longitude: 75.9495, elevation: 335 },
  { id: 'rj-mozamabad', nameHi: 'मौजमाबाद', nameEn: 'Mozamabad', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 26.6634, longitude: 75.3685, elevation: 391 },
  { id: 'rj-phagi', nameHi: 'फागी', nameEn: 'Phagi', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 26.2928, longitude: 75.5571, elevation: 310 },
  { id: 'rj-phulera', nameHi: 'फुलेरा', nameEn: 'Phulera', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 26.874, longitude: 75.2417, elevation: 405 },
  { id: 'rj-sambhar', nameHi: 'सांभर', nameEn: 'Sambhar', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 26.9081, longitude: 75.1914, elevation: 409 },
  { id: 'rj-sanganer', nameHi: 'सांगानेर', nameEn: 'Sanganer', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 26.8111, longitude: 75.7833, elevation: 339 },
  { id: 'rj-shahpura-jaipur', nameHi: 'शाहपुरा', nameEn: 'Shahpura', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 26.5061, longitude: 75.4422, elevation: 364 },
  { id: 'rj-viratnagar', nameHi: 'विराटनगर', nameEn: 'Viratnagar', districtHi: 'जयपुर', districtEn: 'Jaipur', latitude: 27.4354, longitude: 76.183, elevation: 306 },
  // Jaisalmer
  { id: 'rj-bhaniyana', nameHi: 'भणियाणा', nameEn: 'Bhaniyana', districtHi: 'जैसलमेर', districtEn: 'Jaisalmer', latitude: 26.6331, longitude: 71.8729, elevation: 245 },
  { id: 'rj-fatehgarh', nameHi: 'फतेहगढ़', nameEn: 'Fatehgarh', districtHi: 'जैसलमेर', districtEn: 'Jaisalmer', latitude: 26.4961, longitude: 71.2042, elevation: 237 },
  { id: 'rj-jaisalmer', nameHi: 'जैसलमेर', nameEn: 'Jaisalmer', districtHi: 'जैसलमेर', districtEn: 'Jaisalmer', latitude: 26.9176, longitude: 70.9039, elevation: 225 },
  { id: 'rj-nachna', nameHi: 'नाचना', nameEn: 'Nachna', districtHi: 'जैसलमेर', districtEn: 'Jaisalmer', latitude: 27.5099, longitude: 71.7221, elevation: 251 },
  { id: 'rj-pokaran', nameHi: 'पोकरण', nameEn: 'Pokaran', districtHi: 'जैसलमेर', districtEn: 'Jaisalmer', latitude: 26.9201, longitude: 71.9163, elevation: 241 },
  { id: 'rj-ramgarh-jaisalmer', nameHi: 'रामगढ़', nameEn: 'Ramgarh', districtHi: 'जैसलमेर', districtEn: 'Jaisalmer', latitude: 27.3692, longitude: 70.4987, elevation: 239 },
  { id: 'rj-sam', nameHi: 'सम', nameEn: 'Sam', districtHi: 'जैसलमेर', districtEn: 'Jaisalmer', latitude: 26.8963, longitude: 70.694, elevation: 226 },
  // Jalore
  { id: 'rj-ahore', nameHi: 'आहोर', nameEn: 'Ahore', districtHi: 'जालोर', districtEn: 'Jalore', latitude: 25.3723, longitude: 72.7777, elevation: 217 },
  { id: 'rj-bagra', nameHi: 'बागरा', nameEn: 'Bagra', districtHi: 'जालोर', districtEn: 'Jalore', latitude: 25.1986, longitude: 72.5974, elevation: 229 },
  { id: 'rj-bhinmal', nameHi: 'भीनमाल', nameEn: 'Bhinmal', districtHi: 'जालोर', districtEn: 'Jalore', latitude: 24.9994, longitude: 72.2714, elevation: 148 },
  { id: 'rj-chitalwana', nameHi: 'चितलवाना', nameEn: 'Chitalwana', districtHi: 'जालोर', districtEn: 'Jalore', latitude: 24.9094, longitude: 71.6599, elevation: 103 },
  { id: 'rj-jalore', nameHi: 'जालोर', nameEn: 'Jalore', districtHi: 'जालोर', districtEn: 'Jalore', latitude: 25.35, longitude: 72.628, elevation: 179 },
  { id: 'rj-jaswantpura', nameHi: 'जसवंतपुरा', nameEn: 'Jaswantpura', districtHi: 'जालोर', districtEn: 'Jalore', latitude: 24.8019, longitude: 72.4598, elevation: 438 },
  { id: 'rj-raniwara', nameHi: 'रानीवाड़ा', nameEn: 'Raniwara', districtHi: 'जालोर', districtEn: 'Jalore', latitude: 24.751, longitude: 72.2053, elevation: 268 },
  { id: 'rj-sanchore', nameHi: 'सांचौर', nameEn: 'Sanchore', districtHi: 'जालोर', districtEn: 'Jalore', latitude: 24.7517, longitude: 71.7762, elevation: 68 },
  { id: 'rj-sayla', nameHi: 'सायला', nameEn: 'Sayla', districtHi: 'जालोर', districtEn: 'Jalore', latitude: 25.3134, longitude: 72.3076, elevation: 214 },
  // Jhalawar
  { id: 'rj-aklera', nameHi: 'अकलेरा', nameEn: 'Aklera', districtHi: 'झालावाड़', districtEn: 'Jhalawar', latitude: 24.4129, longitude: 76.5672, elevation: 315 },
  { id: 'rj-bakani', nameHi: 'बकानी', nameEn: 'Bakani', districtHi: 'झालावाड़', districtEn: 'Jhalawar', latitude: 24.2862, longitude: 76.2371, elevation: 322 },
  { id: 'rj-dag', nameHi: 'डग', nameEn: 'Dag', districtHi: 'झालावाड़', districtEn: 'Jhalawar', latitude: 23.9322, longitude: 75.8298, elevation: 350 },
  { id: 'rj-gangdhar', nameHi: 'गंगधार', nameEn: 'Gangdhar', districtHi: 'झालावाड़', districtEn: 'Jhalawar', latitude: 23.9406, longitude: 75.6219, elevation: 368 },
  { id: 'rj-jhalawar', nameHi: 'झालावाड़', nameEn: 'Jhalawar', districtHi: 'झालावाड़', districtEn: 'Jhalawar', latitude: 24.5963, longitude: 76.165, elevation: 317 },
  { id: 'rj-jhalrapatan', nameHi: 'झालरापाटन', nameEn: 'Jhalrapatan', districtHi: 'झालावाड़', districtEn: 'Jhalawar', latitude: 24.542, longitude: 76.1724, elevation: 319 },
  { id: 'rj-khanpur', nameHi: 'खानपुर', nameEn: 'Khanpur', districtHi: 'झालावाड़', districtEn: 'Jhalawar', latitude: 24.7324, longitude: 76.396, elevation: 308 },
  { id: 'rj-manoharthana', nameHi: 'मनोहरथाना', nameEn: 'Manoharthana', districtHi: 'झालावाड़', districtEn: 'Jhalawar', latitude: 24.24, longitude: 76.8018, elevation: 317 },
  { id: 'rj-pirawa', nameHi: 'पिड़ावा', nameEn: 'Pirawa', districtHi: 'झालावाड़', districtEn: 'Jhalawar', latitude: 24.1551, longitude: 76.0273, elevation: 330 },
  { id: 'rj-sunel', nameHi: 'सुनेल', nameEn: 'Sunel', districtHi: 'झालावाड़', districtEn: 'Jhalawar', latitude: 24.3707, longitude: 75.9571, elevation: 327 },
  // Jhunjhunu
  { id: 'rj-alsisar', nameHi: 'अलसीसर', nameEn: 'Alsisar', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 28.304, longitude: 75.2859, elevation: 322 },
  { id: 'rj-bissau', nameHi: 'बिसाऊ', nameEn: 'Bissau', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 28.2474, longitude: 75.0767, elevation: 305 },
  { id: 'rj-buhana', nameHi: 'बुहाना', nameEn: 'Buhana', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 28.2104, longitude: 75.8763, elevation: 335 },
  { id: 'rj-chirawa', nameHi: 'चिड़ावा', nameEn: 'Chirawa', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 28.2318, longitude: 75.6479, elevation: 332 },
  { id: 'rj-jhunjhunu', nameHi: 'झुंझुनूं', nameEn: 'Jhunjhunu', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 28.1274, longitude: 75.401, elevation: 323 },
  { id: 'rj-khetri', nameHi: 'खेतड़ी', nameEn: 'Khetri', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 28.0007, longitude: 75.7864, elevation: 345 },
  { id: 'rj-malsisar', nameHi: 'मलसीसर', nameEn: 'Malsisar', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 28.3536, longitude: 75.2975, elevation: 321 },
  { id: 'rj-mandawa', nameHi: 'मंडावा', nameEn: 'Mandawa', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 28.0554, longitude: 75.1483, elevation: 339 },
  { id: 'rj-nawalgarh', nameHi: 'नवलगढ़', nameEn: 'Nawalgarh', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 27.8516, longitude: 75.2738, elevation: 405 },
  { id: 'rj-pilani', nameHi: 'पिलानी', nameEn: 'Pilani', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 28.3672, longitude: 75.6035, elevation: 329 },
  { id: 'rj-surajgarh', nameHi: 'सूरजगढ़', nameEn: 'Surajgarh', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 28.3101, longitude: 75.7327, elevation: 332 },
  { id: 'rj-udaipurwati', nameHi: 'उदयपुरवाटी', nameEn: 'Udaipurwati', districtHi: 'झुंझुनूं', districtEn: 'Jhunjhunu', latitude: 27.7301, longitude: 75.4716, elevation: 389 },
  // Jodhpur
  { id: 'rj-aau', nameHi: 'आऊ', nameEn: 'Aau', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 27.1988, longitude: 72.8482, elevation: 257 },
  { id: 'rj-balesar', nameHi: 'बालेसर', nameEn: 'Balesar', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 26.3917, longitude: 72.4874, elevation: 242 },
  { id: 'rj-bap', nameHi: 'बाप', nameEn: 'Bap', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 27.3713, longitude: 72.3534, elevation: 232 },
  { id: 'rj-bhopalgarh', nameHi: 'भोपालगढ़', nameEn: 'Bhopalgarh', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 26.6489, longitude: 73.4932, elevation: 317 },
  { id: 'rj-bilara', nameHi: 'बिलाड़ा', nameEn: 'Bilara', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 26.1807, longitude: 73.7055, elevation: 346 },
  { id: 'rj-dechu', nameHi: 'देचू', nameEn: 'Dechu', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 26.7698, longitude: 72.3271, elevation: 240 },
  { id: 'rj-jodhpur', nameHi: 'जोधपुर', nameEn: 'Jodhpur', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 26.2684, longitude: 73.0059, elevation: 231 },
  { id: 'rj-lohawat', nameHi: 'लोहावट', nameEn: 'Lohawat', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 26.9844, longitude: 72.5907, elevation: 235 },
  { id: 'rj-luni', nameHi: 'लूणी', nameEn: 'Luni', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 26.0018, longitude: 73.0051, elevation: 245 },
  { id: 'rj-osian', nameHi: 'ओसियां', nameEn: 'Osian', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 26.7313, longitude: 72.905, elevation: 263 },
  { id: 'rj-phalodi', nameHi: 'फलौदी', nameEn: 'Phalodi', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 27.131, longitude: 72.3683, elevation: 226 },
  { id: 'rj-pipar-city', nameHi: 'पीपाड़ शहर', nameEn: 'Pipar City', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 26.3844, longitude: 73.5439, elevation: 314 },
  { id: 'rj-setrawa', nameHi: 'सेतरावा', nameEn: 'Setrawa', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 26.599, longitude: 72.2946, elevation: 246 },
  { id: 'rj-shergarh', nameHi: 'शेरगढ़', nameEn: 'Shergarh', districtHi: 'जोधपुर', districtEn: 'Jodhpur', latitude: 26.3305, longitude: 72.2926, elevation: 228 },
  // Karauli
  { id: 'rj-hindaun', nameHi: 'हिंडौन', nameEn: 'Hindaun', districtHi: 'करौली', districtEn: 'Karauli', latitude: 26.7341, longitude: 77.0352, elevation: 272 },
  { id: 'rj-karauli', nameHi: 'करौली', nameEn: 'Karauli', districtHi: 'करौली', districtEn: 'Karauli', latitude: 26.4983, longitude: 77.0276, elevation: 275 },
  { id: 'rj-mandrayal', nameHi: 'मंडरायल', nameEn: 'Mandrayal', districtHi: 'करौली', districtEn: 'Karauli', latitude: 26.3018, longitude: 77.2363, elevation: 271 },
  { id: 'rj-masalpur', nameHi: 'मासलपुर', nameEn: 'Masalpur', districtHi: 'करौली', districtEn: 'Karauli', latitude: 26.6307, longitude: 77.2321, elevation: 267 },
  { id: 'rj-nadoti', nameHi: 'नादौती', nameEn: 'Nadoti', districtHi: 'करौली', districtEn: 'Karauli', latitude: 26.7064, longitude: 76.7188, elevation: 294 },
  { id: 'rj-sapotra', nameHi: 'सपोटरा', nameEn: 'Sapotra', districtHi: 'करौली', districtEn: 'Karauli', latitude: 26.2928, longitude: 76.7522, elevation: 279 },
  { id: 'rj-sri-mahaveerji', nameHi: 'श्रीमहावीरजी', nameEn: 'Sri Mahaveerji', districtHi: 'करौली', districtEn: 'Karauli', latitude: 26.6956, longitude: 76.9091, elevation: 277 },
  { id: 'rj-todabhim', nameHi: 'टोडाभीम', nameEn: 'Todabhim', districtHi: 'करौली', districtEn: 'Karauli', latitude: 26.9167, longitude: 76.8167, elevation: 289 },
  // Kota
  { id: 'rj-digod', nameHi: 'दीगोद', nameEn: 'Digod', districtHi: 'कोटा', districtEn: 'Kota', latitude: 25.2217, longitude: 76.0818, elevation: 280 },
  { id: 'rj-itawa', nameHi: 'इटावा', nameEn: 'Itawa', districtHi: 'कोटा', districtEn: 'Kota', latitude: 25.5386, longitude: 76.3782, elevation: 281 },
  { id: 'rj-kanwas', nameHi: 'कनवास', nameEn: 'Kanwas', districtHi: 'कोटा', districtEn: 'Kota', latitude: 24.8663, longitude: 76.1246, elevation: 312 },
  { id: 'rj-kota', nameHi: 'कोटा', nameEn: 'Kota', districtHi: 'कोटा', districtEn: 'Kota', latitude: 25.1825, longitude: 75.8391, elevation: 271 },
  { id: 'rj-pipalda', nameHi: 'पीपल्दा', nameEn: 'Pipalda', districtHi: 'कोटा', districtEn: 'Kota', latitude: 25.55, longitude: 76.45, elevation: 280 },
  { id: 'rj-ramganjmandi', nameHi: 'रामगंजमंडी', nameEn: 'Ramganjmandi', districtHi: 'कोटा', districtEn: 'Kota', latitude: 24.6465, longitude: 75.9433, elevation: 335 },
  { id: 'rj-sangod', nameHi: 'सांगोद', nameEn: 'Sangod', districtHi: 'कोटा', districtEn: 'Kota', latitude: 24.9271, longitude: 76.2865, elevation: 291 },
  { id: 'rj-sultanpur', nameHi: 'सुल्तानपुर', nameEn: 'Sultanpur', districtHi: 'कोटा', districtEn: 'Kota', latitude: 24.6322, longitude: 75.8904, elevation: 332 },
  // Nagaur
  { id: 'rj-degana', nameHi: 'डेगाना', nameEn: 'Degana', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 26.8969, longitude: 74.3172, elevation: 426 },
  { id: 'rj-didwana', nameHi: 'डीडवाना', nameEn: 'Didwana', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 27.401, longitude: 74.5754, elevation: 376 },
  { id: 'rj-jayal', nameHi: 'जायल', nameEn: 'Jayal', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 27.2217, longitude: 74.0192, elevation: 318 },
  { id: 'rj-khinwsar', nameHi: 'खींवसर', nameEn: 'Khinwsar', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 27.0106, longitude: 73.7673, elevation: 311 },
  { id: 'rj-kuchaman-city', nameHi: 'कुचामन शहर', nameEn: 'Kuchaman City', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 27.1474, longitude: 74.8565, elevation: 405 },
  { id: 'rj-ladnun', nameHi: 'लाडनूं', nameEn: 'Ladnun', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 27.6531, longitude: 74.3999, elevation: 348 },
  { id: 'rj-makrana', nameHi: 'मकराना', nameEn: 'Makrana', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 27.0436, longitude: 74.7245, elevation: 420 },
  { id: 'rj-merta-city', nameHi: 'मेड़ता शहर', nameEn: 'Merta City', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 26.6486, longitude: 74.0341, elevation: 417 },
  { id: 'rj-mundwa', nameHi: 'मूंडवा', nameEn: 'Mundwa', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 27.0631, longitude: 73.823, elevation: 309 },
  { id: 'rj-nagaur', nameHi: 'नागौर', nameEn: 'Nagaur', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 27.202, longitude: 73.7339, elevation: 302 },
  { id: 'rj-nawa', nameHi: 'नावां', nameEn: 'Nawa', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 27.0195, longitude: 75.0023, elevation: 413 },
  { id: 'rj-parbatsar', nameHi: 'परबतसर', nameEn: 'Parbatsar', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 26.8869, longitude: 74.7641, elevation: 438 },
  { id: 'rj-riyan-bari', nameHi: 'रियां बड़ी', nameEn: 'Riyan Bari', districtHi: 'नागौर', districtEn: 'Nagaur', latitude: 26.696, longitude: 73.8342, elevation: 368 },
  // Pali
  { id: 'rj-bali', nameHi: 'बाली', nameEn: 'Bali', districtHi: 'पाली', districtEn: 'Pali', latitude: 25.1973, longitude: 73.2912, elevation: 343 },
  { id: 'rj-desuri', nameHi: 'देसूरी', nameEn: 'Desuri', districtHi: 'पाली', districtEn: 'Pali', latitude: 25.2732, longitude: 73.5656, elevation: 469 },
  { id: 'rj-jaitaran', nameHi: 'जैतारण', nameEn: 'Jaitaran', districtHi: 'पाली', districtEn: 'Pali', latitude: 26.2045, longitude: 73.9368, elevation: 410 },
  { id: 'rj-marwar-junction', nameHi: 'मारवाड़ जंक्शन', nameEn: 'Marwar Junction', districtHi: 'पाली', districtEn: 'Pali', latitude: 25.725, longitude: 73.6033, elevation: 284 },
  { id: 'rj-pali', nameHi: 'पाली', nameEn: 'Pali', districtHi: 'पाली', districtEn: 'Pali', latitude: 25.7728, longitude: 73.3234, elevation: 214 },
  { id: 'rj-rani', nameHi: 'रानी', nameEn: 'Rani', districtHi: 'पाली', districtEn: 'Pali', latitude: 25.3503, longitude: 73.3089, elevation: 338 },
  { id: 'rj-rohat', nameHi: 'रोहट', nameEn: 'Rohat', districtHi: 'पाली', districtEn: 'Pali', latitude: 25.7697, longitude: 73.3233, elevation: 222 },
  { id: 'rj-sadri', nameHi: 'सादड़ी', nameEn: 'Sadri', districtHi: 'पाली', districtEn: 'Pali', latitude: 25.1855, longitude: 73.4529, elevation: 450 },
  { id: 'rj-sojat', nameHi: 'सोजत', nameEn: 'Sojat', districtHi: 'पाली', districtEn: 'Pali', latitude: 25.9249, longitude: 73.6663, elevation: 306 },
  { id: 'rj-sumerpur', nameHi: 'सुमेरपुर', nameEn: 'Sumerpur', districtHi: 'पाली', districtEn: 'Pali', latitude: 25.1543, longitude: 73.0816, elevation: 273 },
  // Pratapgarh
  { id: 'rj-arnod', nameHi: 'अरनोद', nameEn: 'Arnod', districtHi: 'प्रतापगढ़', districtEn: 'Pratapgarh', latitude: 24.6998, longitude: 74.7543, elevation: 402 },
  { id: 'rj-chhoti-sadri', nameHi: 'छोटीसादड़ी', nameEn: 'Chhoti Sadri', districtHi: 'प्रतापगढ़', districtEn: 'Pratapgarh', latitude: 24.3815, longitude: 74.7012, elevation: 434 },
  { id: 'rj-dhariawad', nameHi: 'धरियावद', nameEn: 'Dhariawad', districtHi: 'प्रतापगढ़', districtEn: 'Pratapgarh', latitude: 24.1003, longitude: 74.4438, elevation: 397 },
  { id: 'rj-peepalkhoont', nameHi: 'पीपलखूंट', nameEn: 'Peepalkhoont', districtHi: 'प्रतापगढ़', districtEn: 'Pratapgarh', latitude: 23.8076, longitude: 74.5617, elevation: 383 },
  { id: 'rj-pratapgarh', nameHi: 'प्रतापगढ़', nameEn: 'Pratapgarh', districtHi: 'प्रतापगढ़', districtEn: 'Pratapgarh', latitude: 24.0322, longitude: 74.7816, elevation: 495 },
  { id: 'rj-suhagpura', nameHi: 'सुहागपुरा', nameEn: 'Suhagpura', districtHi: 'प्रतापगढ़', districtEn: 'Pratapgarh', latitude: 23.9199, longitude: 74.7866, elevation: 480 },
  // Rajsamand
  { id: 'rj-amet', nameHi: 'आमेट', nameEn: 'Amet', districtHi: 'राजसमंद', districtEn: 'Rajsamand', latitude: 25.3061, longitude: 73.9258, elevation: 515 },
  { id: 'rj-bhim', nameHi: 'भीम', nameEn: 'Bhim', districtHi: 'राजसमंद', districtEn: 'Rajsamand', latitude: 25.738, longitude: 74.0801, elevation: 419 },
  { id: 'rj-deogarh', nameHi: 'देवगढ़', nameEn: 'Deogarh', districtHi: 'राजसमंद', districtEn: 'Rajsamand', latitude: 25.5253, longitude: 73.9081, elevation: 441 },
  { id: 'rj-kelwara', nameHi: 'केलवाड़ा', nameEn: 'Kelwara', districtHi: 'राजसमंद', districtEn: 'Rajsamand', latitude: 25.1167, longitude: 73.5975, elevation: 537 },
  { id: 'rj-khamnor', nameHi: 'खमनोर', nameEn: 'Khamnor', districtHi: 'राजसमंद', districtEn: 'Rajsamand', latitude: 24.9121, longitude: 73.7213, elevation: 589 },
  { id: 'rj-nathdwara', nameHi: 'नाथद्वारा', nameEn: 'Nathdwara', districtHi: 'राजसमंद', districtEn: 'Rajsamand', latitude: 24.9381, longitude: 73.8239, elevation: 574 },
  { id: 'rj-railmagra', nameHi: 'रेलमगरा', nameEn: 'Railmagra', districtHi: 'राजसमंद', districtEn: 'Rajsamand', latitude: 25.0246, longitude: 74.1189, elevation: 528 },
  { id: 'rj-rajsamand', nameHi: 'राजसमंद', nameEn: 'Rajsamand', districtHi: 'राजसमंद', districtEn: 'Rajsamand', latitude: 25.0714, longitude: 73.8798, elevation: 546 },
  // Sawai Madhopur
  { id: 'rj-bamanwas', nameHi: 'बामनवास', nameEn: 'Bamanwas', districtHi: 'सवाई माधोपुर', districtEn: 'Sawai Madhopur', latitude: 26.5584, longitude: 76.5588, elevation: 300 },
  { id: 'rj-bonli', nameHi: 'बौंली', nameEn: 'Bonli', districtHi: 'सवाई माधोपुर', districtEn: 'Sawai Madhopur', latitude: 26.3129, longitude: 76.2278, elevation: 284 },
  { id: 'rj-chauth-ka-barwara', nameHi: 'चौथ का बरवाड़ा', nameEn: 'Chauth Ka Barwara', districtHi: 'सवाई माधोपुर', districtEn: 'Sawai Madhopur', latitude: 26.0501, longitude: 76.1531, elevation: 272 },
  { id: 'rj-gangapur-city', nameHi: 'गंगापुर सिटी', nameEn: 'Gangapur City', districtHi: 'सवाई माधोपुर', districtEn: 'Sawai Madhopur', latitude: 25.846, longitude: 75.4889, elevation: 312 },
  { id: 'rj-khandar', nameHi: 'खंडार', nameEn: 'Khandar', districtHi: 'सवाई माधोपुर', districtEn: 'Sawai Madhopur', latitude: 26.0191, longitude: 76.6017, elevation: 270 },
  { id: 'rj-malarna-doongar', nameHi: 'मलारना डूंगर', nameEn: 'Malarna Doongar', districtHi: 'सवाई माधोपुर', districtEn: 'Sawai Madhopur', latitude: 26.2883, longitude: 76.4704, elevation: 278 },
  { id: 'rj-sawai-madhopur', nameHi: 'सवाई माधोपुर', nameEn: 'Sawai Madhopur', districtHi: 'सवाई माधोपुर', districtEn: 'Sawai Madhopur', latitude: 26.023, longitude: 76.3441, elevation: 262 },
  { id: 'rj-wazirpur', nameHi: 'वजीरपुर', nameEn: 'Wazirpur', districtHi: 'सवाई माधोपुर', districtEn: 'Sawai Madhopur', latitude: 26.5597, longitude: 76.8867, elevation: 276 },
  // Sikar
  { id: 'rj-ajitgarh', nameHi: 'अजीतगढ़', nameEn: 'Ajitgarh', districtHi: 'सीकर', districtEn: 'Sikar', latitude: 27.4193, longitude: 75.8214, elevation: 352 },
  { id: 'rj-dantaramgarh', nameHi: 'दांतारामगढ़', nameEn: 'Dantaramgarh', districtHi: 'सीकर', districtEn: 'Sikar', latitude: 27.2579, longitude: 75.1789, elevation: 399 },
  { id: 'rj-fatehpur', nameHi: 'फतेहपुर', nameEn: 'Fatehpur', districtHi: 'सीकर', districtEn: 'Sikar', latitude: 27.9949, longitude: 74.9563, elevation: 315 },
  { id: 'rj-khandela', nameHi: 'खंडेला', nameEn: 'Khandela', districtHi: 'सीकर', districtEn: 'Sikar', latitude: 27.605, longitude: 75.502, elevation: 391 },
  { id: 'rj-lachhmangarh', nameHi: 'लक्ष्मणगढ़', nameEn: 'Lachhmangarh', districtHi: 'सीकर', districtEn: 'Sikar', latitude: 27.8255, longitude: 75.0262, elevation: 365 },
  { id: 'rj-neem-ka-thana', nameHi: 'नीम का थाना', nameEn: 'Neem Ka Thana', districtHi: 'सीकर', districtEn: 'Sikar', latitude: 27.7398, longitude: 75.7865, elevation: 359 },
  { id: 'rj-patan', nameHi: 'पाटन', nameEn: 'Patan', districtHi: 'सीकर', districtEn: 'Sikar', latitude: 27.7386, longitude: 75.8823, elevation: 348 },
  { id: 'rj-ramgarh-shekhawati', nameHi: 'रामगढ़ शेखावाटी', nameEn: 'Ramgarh Shekhawati', districtHi: 'सीकर', districtEn: 'Sikar', latitude: 28.1689, longitude: 74.9803, elevation: 310 },
  { id: 'rj-reengus', nameHi: 'रींगस', nameEn: 'Reengus', districtHi: 'सीकर', districtEn: 'Sikar', latitude: 27.3636, longitude: 75.5684, elevation: 379 },
  { id: 'rj-sikar', nameHi: 'सीकर', nameEn: 'Sikar', districtHi: 'सीकर', districtEn: 'Sikar', latitude: 27.6121, longitude: 75.14, elevation: 427 },
  { id: 'rj-sri-madhopur', nameHi: 'श्रीमाधोपुर', nameEn: 'Sri Madhopur', districtHi: 'सीकर', districtEn: 'Sikar', latitude: 27.466, longitude: 75.5974, elevation: 380 },
  // Sirohi
  { id: 'rj-abu-road', nameHi: 'आबू रोड', nameEn: 'Abu Road', districtHi: 'सिरोही', districtEn: 'Sirohi', latitude: 24.4801, longitude: 72.7819, elevation: 265 },
  { id: 'rj-mount-abu', nameHi: 'माउंट आबू', nameEn: 'Mount Abu', districtHi: 'सिरोही', districtEn: 'Sirohi', latitude: 24.5937, longitude: 72.7176, elevation: 1220 },
  { id: 'rj-pindwara', nameHi: 'पिंडवाड़ा', nameEn: 'Pindwara', districtHi: 'सिरोही', districtEn: 'Sirohi', latitude: 24.7975, longitude: 73.055, elevation: 285 },
  { id: 'rj-reodar', nameHi: 'रेवदर', nameEn: 'Reodar', districtHi: 'सिरोही', districtEn: 'Sirohi', latitude: 24.6198, longitude: 72.5263, elevation: 765 },
  { id: 'rj-sheoganj', nameHi: 'शिवगंज', nameEn: 'Sheoganj', districtHi: 'सिरोही', districtEn: 'Sirohi', latitude: 25.1392, longitude: 73.0678, elevation: 250 },
  { id: 'rj-sirohi', nameHi: 'सिरोही', nameEn: 'Sirohi', districtHi: 'सिरोही', districtEn: 'Sirohi', latitude: 24.8884, longitude: 72.8479, elevation: 321 },
  // Tonk
  { id: 'rj-deoli', nameHi: 'देवली', nameEn: 'Deoli', districtHi: 'टोंक', districtEn: 'Tonk', latitude: 25.7573, longitude: 75.3799, elevation: 318 },
  { id: 'rj-malpura', nameHi: 'मालपुरा', nameEn: 'Malpura', districtHi: 'टोंक', districtEn: 'Tonk', latitude: 26.2838, longitude: 75.3646, elevation: 356 },
  { id: 'rj-niwai', nameHi: 'निवाई', nameEn: 'Niwai', districtHi: 'टोंक', districtEn: 'Tonk', latitude: 26.3607, longitude: 75.9184, elevation: 296 },
  { id: 'rj-peeplu', nameHi: 'पीपलू', nameEn: 'Peeplu', districtHi: 'टोंक', districtEn: 'Tonk', latitude: 25.7243, longitude: 76.1434, elevation: 281 },
  { id: 'rj-todaraisingh', nameHi: 'टोडारायसिंह', nameEn: 'Todaraisingh', districtHi: 'टोंक', districtEn: 'Tonk', latitude: 26.024, longitude: 75.4818, elevation: 315 },
  { id: 'rj-tonk', nameHi: 'टोंक', nameEn: 'Tonk', districtHi: 'टोंक', districtEn: 'Tonk', latitude: 26.1664, longitude: 75.7882, elevation: 289 },
  { id: 'rj-uniara', nameHi: 'उनियारा', nameEn: 'Uniara', districtHi: 'टोंक', districtEn: 'Tonk', latitude: 26.0342, longitude: 75.6206, elevation: 298 },
  // Udaipur
  { id: 'rj-bhinder', nameHi: 'भींडर', nameEn: 'Bhinder', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 24.5023, longitude: 74.1855, elevation: 443 },
  { id: 'rj-gogunda', nameHi: 'गोगुंदा', nameEn: 'Gogunda', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 24.7584, longitude: 73.5298, elevation: 823 },
  { id: 'rj-jhadol', nameHi: 'झाड़ोल', nameEn: 'Jhadol', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 24.3627, longitude: 73.5312, elevation: 496 },
  { id: 'rj-kanod', nameHi: 'कानोड़', nameEn: 'Kanod', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 24.4361, longitude: 74.2631, elevation: 409 },
  { id: 'rj-kherwara', nameHi: 'खेरवाड़ा', nameEn: 'Kherwara', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 23.9859, longitude: 73.5949, elevation: 250 },
  { id: 'rj-lasadiya', nameHi: 'लसाड़िया', nameEn: 'Lasadiya', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 24.261, longitude: 74.2421, elevation: 339 },
  { id: 'rj-mavli', nameHi: 'मावली', nameEn: 'Mavli', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 24.7835, longitude: 73.9839, elevation: 558 },
  { id: 'rj-nayagaon', nameHi: 'नयागांव', nameEn: 'Nayagaon', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 23.995, longitude: 73.76, elevation: 259 },
  { id: 'rj-phalasiya', nameHi: 'फलासिया', nameEn: 'Phalasiya', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 24.2697, longitude: 73.3864, elevation: 420 },
  { id: 'rj-salumber', nameHi: 'सलूंबर', nameEn: 'Salumber', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 24.1367, longitude: 74.0481, elevation: 285 },
  { id: 'rj-semari', nameHi: 'सेमारी', nameEn: 'Semari', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 24.0554, longitude: 73.8569, elevation: 287 },
  { id: 'rj-udaipur', nameHi: 'उदयपुर', nameEn: 'Udaipur', districtHi: 'उदयपुर', districtEn: 'Udaipur', latitude: 24.5858, longitude: 73.7135, elevation: 598 },
];
