// GENERATED by scripts/gen-verse-counts.mts — do not edit by hand.
//
// Verse counts for the library rows in `texts.ts`, lifted out of the corpora so
// that reading a row's subtitle does not evaluate the corpus behind it. The
// numbers are checked against the real payloads by
// `src/data/__tests__/verseCounts.test.ts`, so a corpus edit that changes a
// count fails the build until this file is regenerated.

export const achyutashtakamTotal = 8 as const;
export const bajrangBaanTotal = 20 as const;
export const bhavaniAshtakamTotal = 8 as const;
export const dattaAshtakamTotal = 8 as const;
export const deviSuktamTotal = 30 as const;
export const durgaChalisaCounts = {"openingDohas":0,"chaupais":40,"closingDohas":1,"totalVerses":41} as const;
export const durgaKavachTotal = 18 as const;
export const durgaStotramTotal = 33 as const;
export const durgaStutiArjunaTotal = 13 as const;
export const ganeshChalisaCounts = {"openingDohas":2,"chaupais":40,"closingDohas":1,"totalVerses":43} as const;
export const ganeshStotramTotal = 28 as const;
export const ganeshaKavachamTotal = 10 as const;
export const gangashtakamTotal = 8 as const;
export const gayatriChalisaCounts = {"openingDohas":2,"chaupais":40,"closingDohas":1,"totalVerses":43} as const;
export const hanumanAshtakTotal = 9 as const;
export const hanumanChalisaTotal = 43 as const;
export const kalikaAshtakamTotal = 10 as const;
export const krishnaChalisaCounts = {"openingDohas":2,"chaupais":40,"closingDohas":1,"totalVerses":43} as const;
export const krishnaStotramTotal = 12 as const;
export const krishnaStutiTotal = 12 as const;
export const kuberaStotramTotal = 17 as const;
export const lingashtakamTotal = 8 as const;
export const madhurashtakamTotal = 8 as const;
export const mahalakshmiAshtakamTotal = 8 as const;
export const narasimhaAshtakamTotal = 8 as const;
export const narayanaSuktamTotal = 14 as const;
export const navagrahaStotramTotal = 9 as const;
export const purushaSuktamTotal = 18 as const;
export const radhashtakamTotal = 8 as const;
export const ramChalisaCounts = {"openingDohas":1,"chaupais":40,"closingDohas":2,"totalVerses":43} as const;
export const ramStutiTotal = 9 as const;
export const ramaRakshaStotraTotal = 38 as const;
export const ramcharitmanasTotal = 19 as const;
export const rudrashtakamTotal = 9 as const;
export const saraswatiChalisaCounts = {"openingDohas":2,"chaupais":40,"closingDohas":1,"totalVerses":43} as const;
export const saraswatiStotramTotal = 7 as const;
export const shaniAshtakamTotal = 8 as const;
export const shivChalisaCounts = {"openingDohas":2,"chaupais":40,"closingDohas":1,"totalVerses":43} as const;
export const shivaKavachamTotal = 9 as const;
export const shivaStrotamTotal = 23 as const;
export const subrahmanyaAshtakamTotal = 8 as const;
export const sundarkandTotal = 354 as const;
export const suryaAshtakamTotal = 8 as const;
export const valmikiRamayanTotal = 23289 as const;
export const vishnuChalisaCounts = {"openingDohas":1,"chaupais":40,"closingDohas":0,"totalVerses":41} as const;
export const vishnuSahasranamaTotal = 79 as const;
