/** Deterministic offline content compiler. Run after editing scripture sources. */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';

const root = path.resolve(import.meta.dirname, '..');
const source = path.join(root, 'src/data');
const output = path.join(root, 'assets/library');
fs.mkdirSync(output, { recursive: true });
const documents = fs.readdirSync(source, { recursive: true }).filter((p): p is string =>
  typeof p === 'string' && p.endsWith('.json')
).sort().flatMap((key) => {
  const data = JSON.parse(fs.readFileSync(path.join(source, key), 'utf8'));
  return Array.isArray(data?.verses) ? [{ key, data }] : [];
});
// Refresh the authoring adapter before importing registries, including newly added texts.
if (!process.argv.includes('--check')) {
  const sources = documents.map(({key}) => `  '${key}': () => require('../data/${key}'),`).join('\n');
  fs.writeFileSync(path.join(root, 'src/storage/content.ts'), `// Generated source adapter for authoring tools, node tests and web. Native resolves content.native.ts.\nconst sources: Record<string, () => unknown> = {\n${sources}\n};\nexport function readContent<T>(key: string): T {\n  const load = sources[key];\n  if (!load) throw new Error(\`Unknown library document: \${key}\`);\n  return load() as T;\n}\nexport function readVerse<T>(key: string, position: number): T {\n  return readContent<{verses:T[]}>(key).verses[position];\n}\n`);
}
const { getSearchIndex, makeVerseEntry } = await import('../src/data/searchIndex');
const { getValmikiRamayanChapter } = await import('../src/data/valmiki-ramayan');
// The paged native reader trusts the compiler; run the existing whole-chapter
// invariants here, rather than walking thousands of verses on a device.
for (const { key, data } of documents) {
  if (key.startsWith('valmiki-ramayan/chapter-')) getValmikiRamayanChapter(data.chapter);
}
const index = getSearchIndex();
const verses = index.verses.filter((v) => v.sourceId !== 'valmiki-ramayan');
for (const { key, data } of documents) {
  if (!key.startsWith('valmiki-ramayan/chapter-')) continue;
  data.verses.forEach((v: any, verseIndex: number) => verses.push(makeVerseEntry({
    sourceId: 'valmiki-ramayan', sectionNameHi: 'वाल्मीकि रामायण', sectionNameEn: 'Valmiki Ramayan',
    chapter: data.chapter, verseIndex, labelHi: v.labelHi, labelEn: v.labelEn,
    linesHi: v.lines, linesEn: v.linesEn, meaningHi: v.meaningHi, meaningEn: v.meaningEn,
  })));
}
const entries = [...index.sections, ...index.deities, ...verses];
const version = crypto.createHash('sha256').update(JSON.stringify({ schema: 1, searchFormat: 2, documents, entries })).digest('hex');
const tmp = path.join(output, 'library.tmp.db');
fs.rmSync(tmp, { force: true });
const db = new DatabaseSync(tmp);
db.exec(`
 PRAGMA page_size=4096;
 CREATE TABLE metadata(version TEXT NOT NULL, schema_version INTEGER NOT NULL);
 CREATE TABLE documents(key TEXT PRIMARY KEY, metadata TEXT NOT NULL, verse_count INTEGER NOT NULL);
 CREATE TABLE verses(document_key TEXT NOT NULL, position INTEGER NOT NULL, id TEXT NOT NULL, data TEXT NOT NULL,
   PRIMARY KEY(document_key, position), UNIQUE(document_key,id));
 CREATE TABLE search_entries(ordinal INTEGER PRIMARY KEY, kind TEXT NOT NULL, data TEXT NOT NULL, fields TEXT NOT NULL);
 CREATE INDEX search_kind ON search_entries(kind);
 CREATE VIRTUAL TABLE search_fts USING fts5(text, tokenize='trigram', content='', detail=none);
 BEGIN;
`);
db.prepare('INSERT INTO metadata VALUES (?,1)').run(version);
const putDoc = db.prepare('INSERT INTO documents VALUES (?,?,?)');
const putVerse = db.prepare('INSERT INTO verses VALUES (?,?,?,?)');
for (const { key, data } of documents) {
  const { verses, ...metadata } = data;
  putDoc.run(key, JSON.stringify(metadata), verses.length);
  verses.forEach((v: any, i: number) => putVerse.run(key, i, v.id, JSON.stringify(v)));
}
const putSearch = db.prepare('INSERT INTO search_entries VALUES (?,?,?,?)');
const putFts = db.prepare('INSERT INTO search_fts(rowid,text) VALUES (?,?)');
entries.forEach(({ fieldsNorm, norm, ...entry }, ordinal) => {
  putSearch.run(ordinal + 1, entry.type, JSON.stringify(entry), JSON.stringify(fieldsNorm));
  putFts.run(ordinal + 1, fieldsNorm.join('\n'));
});
db.exec("COMMIT; INSERT INTO search_fts(search_fts) VALUES('optimize'); VACUUM;");
if (db.prepare('PRAGMA integrity_check').get()?.integrity_check !== 'ok') throw new Error('Library integrity failed');
db.close();
const final = path.join(output, 'library.db');
if (process.argv.includes('--check')) {
  const expected = fs.readFileSync(final);
  if (!expected.equals(fs.readFileSync(tmp))) throw new Error('Library is stale: run npm run build:library');
  fs.rmSync(tmp);
} else {
  fs.renameSync(tmp, final);
  fs.writeFileSync(path.join(root, 'src/storage/libraryVersion.ts'), `// Generated by build-library.mts\nexport const LIBRARY_VERSION = '${version}';\n`);

}
console.log(JSON.stringify({version, documents: documents.length, verses: documents.reduce((n,d) => n+d.data.verses.length,0), searchEntries:entries.length, bytes:fs.statSync(final).size}));
