/**
 * Cut the home-screen widget background plates (design.md §59) from the app's own
 * sketches: one pre-cropped, parchment-washed JPEG per (content, size) the catalog
 * offers, written to `assets/widget-backgrounds/`. Both native config plugins and
 * the in-app gallery read that one folder.
 *
 *   npx tsx scripts/build-widget-backgrounds.mts
 *
 * Requires ImageMagick 6 (`convert`). The plates are committed, so this only runs
 * when the art, the wash, or `WIDGET_BACKGROUND_DIMENSIONS` change. It refuses to
 * write a plate on which any widget text token would fall below 4.5:1.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { WIDGET_BACKGROUND_DIMENSIONS, WIDGET_BACKGROUND_SOURCES, widgetBackgroundPlates } from '../src/widgets/catalog';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_DIR = path.join(ROOT, 'assets', 'backgrounds');
const OUT_DIR = path.join(ROOT, 'assets', 'widget-backgrounds');

const PARCHMENT = '#F8EFD6'; // colors.parchmentSoft — the widgets' container background
/** Default share of the sketch over parchment (a source may set its own `wash`). The sketches are already near-parchment, so this keeps them a quiet watermark. */
const WASH = 0.22;
/** The sketches carry a burnt-paper border; it reads as a dirty edge on a rounded widget, so it is cropped away. */
const INSET = 0.08;
/** The text tokens the native widgets draw on this background (ink, inkMuted, saffronDeep). `gold` is the decorative ॐ mark. */
const TEXT_TOKENS = { ink: '#1A0E03', inkMuted: '#6E5230', saffronDeep: '#8A3E0B' };
const MIN_CONTRAST = 4.5;

const luminance = (hex: string) => {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
    .map((c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const contrast = (a: number, b: number) => (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05);

fs.mkdirSync(OUT_DIR, { recursive: true });
const index: string[] = [];
for (const { content, size, name } of widgetBackgroundPlates()) {
  const { file, focusY, wash = WASH } = WIDGET_BACKGROUND_SOURCES[content];
  const [width, height] = WIDGET_BACKGROUND_DIMENSIONS[size];
  const source = path.join(SOURCE_DIR, file);
  const [sw, sh] = execFileSync('identify', ['-format', '%w %h', source], { encoding: 'utf8' }).trim().split(' ').map(Number);
  // The usable square inside the burnt border, then the largest box of the plate's
  // aspect that fits it, centred on the subject's height and clamped inside.
  const left = Math.round(sw * INSET); const top = Math.round(sh * INSET);
  const innerW = sw - 2 * left; const innerH = sh - 2 * top;
  const aspect = width / height;
  const cropW = Math.round(Math.min(innerW, innerH * aspect));
  const cropH = Math.round(cropW / aspect);
  const cropX = left + Math.round((innerW - cropW) / 2);
  const cropY = Math.min(top + innerH - cropH, Math.max(top, Math.round(sh * focusY - cropH / 2)));
  const out = path.join(OUT_DIR, `${name}.jpg`);
  execFileSync('convert', [
    source, '-crop', `${cropW}x${cropH}+${cropX}+${cropY}`, '+repage', '-resize', `${width}x${height}!`,
    '(', '-size', `${width}x${height}`, `xc:${PARCHMENT}`, ')', '+swap',
    '-compose', 'blend', '-define', `compose:args=${Math.round(wash * 100)}`, '-composite',
    '-strip', '-interlace', 'none', '-sampling-factor', '4:2:0', '-quality', '82', out,
  ]);
  // Darkest the background gets under a glyph-sized area (a 1.5 px blur ignores single-pixel grain).
  const floor = Number(execFileSync('convert', [out, '-colorspace', 'RGB', '-grayscale', 'Rec709Luminance', '-blur', '0x1.5', '-format', '%[fx:minima]', 'info:'], { encoding: 'utf8' }));
  const [token, worst] = Object.entries(TEXT_TOKENS)
    .map(([key, hex]) => [key, contrast(luminance(hex), floor)] as const)
    .reduce((a, b) => (b[1] < a[1] ? b : a));
  if (worst < MIN_CONTRAST) {
    fs.rmSync(out);
    throw new Error(`${name}: ${token} reaches only ${worst.toFixed(2)}:1 on the darkest area — lower its wash`);
  }
  console.log(`${name}.jpg ${width}x${height} ${(fs.statSync(out).size / 1024).toFixed(1)} KB · worst text contrast ${worst.toFixed(2)}:1 (${token})`);
  index.push(`  ${name}: require('./${name}.jpg'),`);
}

fs.writeFileSync(path.join(OUT_DIR, 'index.ts'), `// Generated by scripts/build-widget-backgrounds.mts — do not edit by hand.
// The in-app Widget Gallery's copy of the plates the native widgets bundle.
export const widgetBackgroundImages: Record<string, number> = {
${index.join('\n')}
};
`);
