// Generates src/panchang/precomputedObservances.ts from the live festival scan, so the
// app does ZERO festival astronomy at runtime (which froze the Panchang screen on real
// devices). Run from the mobile/ directory after any change to the rules or month engine.
// IMPORTANT: run in India time so the resolved calendar days match users' devices:
//   TZ=Asia/Kolkata npx tsx scripts/gen-precomputed-observances.mts
import { writeFileSync } from 'node:fs';
import { resolveObservancesForYearLive } from '../src/panchang/festivalEngine';
import type { CalendarSystem } from '../src/panchang/types';

const YEARS = [2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031];
const SYSTEMS: CalendarSystem[] = ['purnimant', 'amanta'];

function iso(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

const lines: string[] = [];
let entryCount = 0;
for (const system of SYSTEMS) {
  for (const year of YEARS) {
    const observances = resolveObservancesForYearLive(year, system);
    const items = observances.map((o) => [o.rule.id, iso(o.date)]);
    lines.push(`  ${JSON.stringify(`${system}:${year}`)}: ${JSON.stringify(items)},`);
    entryCount += 1;
  }
}

const header = `export type PackedObservance = [ruleId: string, date: string];

`;
const out = `// AUTO-GENERATED by scripts/gen-precomputed-observances.mts — do not edit by hand.
// Festival/observance dates resolved offline so the app does ZERO festival astronomy
// at runtime (the per-day sunrise + lunar-month solves froze the Panchang screen on
// real devices). Keyed by "<calendarSystem>:<year>"; each entry is a [ruleId, date]
// pair, the date a local YYYY-MM-DD. Years outside this set fall back to live
// computation.
//
// The pair encoding is not stylistic: this table is the single largest module in the
// static launch graph, and spelling {"id":…,"date":…} out 4,680 times cost ~56 KB
// against the budget \`src/data/__tests__/launchGraph.test.ts\` enforces.
${header}export const PRECOMPUTED_OBSERVANCES: Record<string, PackedObservance[]> = {
${lines.join('\n')}
};
`;

writeFileSync('src/panchang/precomputedObservances.ts', out);
console.log(`Wrote ${entryCount} year-system entries to src/panchang/precomputedObservances.ts`);
