import fs from 'node:fs';
import path from 'node:path';

/**
 * Regenerate `src/navigation/routeGraph.ts`: for each route, the routes its
 * screen can navigate to.
 *
 * The background warm-up uses this to stay ONE LEVEL AHEAD of the user. Landing
 * on a screen pushes its children to the front of the queue, so the next tap is
 * warm even when someone dives into one branch faster than the breadth-first
 * walk reaches it.
 *
 * Derived by reading the `navigate('X')` / `push('X')` calls in each screen —
 * a heuristic, and deliberately one: it only ORDERS the warm-up, so a missed
 * edge costs a screen being warmed later, never anything a user can see. That
 * is the same bargain `depth` makes in `lazyScreen`.
 *
 * Run: npx tsx scripts/gen-route-graph.mts
 */
const ROOT = path.resolve(import.meta.dirname, '..');
const SCREENS = path.join(ROOT, 'src/screens');
const NAVIGATORS = ['HomeStackNavigator', 'MoreStackNavigator', 'PanchangStackNavigator', 'AudioStackNavigator'];

// route name -> screen component, read from each <Stack.Screen> element.
const routeToScreen = new Map<string, string>();
for (const nav of NAVIGATORS) {
  const src = fs.readFileSync(path.join(ROOT, 'src/navigation', `${nav}.tsx`), 'utf8');
  for (const el of src.match(/<\w+\.Screen\b[\s\S]*?(?:\/>|<\/\w+\.Screen>)/g) ?? []) {
    const name = /name="(\w+)"/.exec(el);
    const comp = /component=\{(\w+)\}/.exec(el);
    const lazyReq = /getComponent=\{load(\w+)Route\}/.exec(el);
    if (!name) continue;
    if (comp) routeToScreen.set(name[1], comp[1]);
    else if (lazyReq) routeToScreen.set(name[1], `${lazyReq[1]}Screen`);
  }
}

// screen component -> routes it navigates to.
const NAV_CALL = /navigat(?:e|ion\.push|ion\.replace)\(\s*['"](\w+)['"]/g;
const childrenOfScreen = new Map<string, Set<string>>();
for (const file of fs.readdirSync(SCREENS).filter((f) => f.endsWith('.tsx'))) {
  const src = fs.readFileSync(path.join(SCREENS, file), 'utf8');
  const targets = new Set<string>();
  for (const m of src.matchAll(NAV_CALL)) targets.add(m[1]);
  childrenOfScreen.set(file.replace('.tsx', ''), targets);
}

const graph: Record<string, string[]> = {};
for (const [route, screen] of [...routeToScreen].sort(([a], [b]) => a.localeCompare(b))) {
  const kids = [...(childrenOfScreen.get(screen) ?? [])]
    .filter((r) => routeToScreen.has(r) && r !== route)
    .sort();
  if (kids.length > 0) graph[route] = kids;
}

const body = Object.entries(graph)
  .map(([route, kids]) => `  ${JSON.stringify(route)}: [${kids.map((k) => JSON.stringify(k)).join(', ')}],`)
  .join('\n');

const out = `// GENERATED by scripts/gen-route-graph.mts — do not edit by hand.
//
// For each route, the routes its screen can open. Used ONLY to order the
// background warm-up (see \`screenPrefetch.prioritise\`): arriving somewhere
// pushes its children to the front of the queue so the next tap is already warm.
//
// Ordering-only means a stale or missing edge is harmless — that screen simply
// gets warmed by the ordinary breadth-first walk instead. Kept honest by
// \`__tests__/routeGraph.test.ts\`.

export const routeGraph: Readonly<Record<string, readonly string[]>> = {
${body}
};

/** Routes reachable in one tap from \`route\`. */
export function childRoutes(route: string | undefined): readonly string[] {
  return route ? routeGraph[route] ?? [] : [];
}
`;
fs.writeFileSync(path.join(ROOT, 'src/navigation/routeGraph.ts'), out, 'utf8');
console.log(`wrote ${Object.keys(graph).length} routes with children (${routeToScreen.size} routes total)`);
