"""Render the actual engine/GPT outputs, no invented competitor answers."""
import json
from pathlib import Path
out = Path(__file__).resolve().parents[2] / 'docs/evaluations/prashna-phase-2026-09-21'
data = json.loads((out / 'engine.json').read_text())
for c in data['cases']:
    p = out / f"gpt-{c['id']}.json"
    c['gpt'] = json.loads(p.read_text()) if p.exists() else None
    c.pop('chart', None)
    c.pop('gptFacts', None)
html = r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Vedansh · Current phase review</title>
<style>
:root{color-scheme:light;--ink:#332719;--muted:#716044;--line:#dfcfb0;--accent:#a44a16}*{box-sizing:border-box}body{margin:0;background:#f5edd4;color:var(--ink);font:17px/1.6 Georgia,serif}main{max-width:1450px;padding:36px 24px;margin:auto}h1{font-size:clamp(30px,4vw,48px);line-height:1.1;margin:12px 0}h2{font-size:27px;line-height:1.35;margin:12px 0}h3{font-size:20px;line-height:1.4;margin:18px 0 8px}p{margin:10px 0}.eyebrow,small,label,button,select,summary{font-family:system-ui,sans-serif}.eyebrow{font-size:11px;letter-spacing:2px;color:var(--accent);font-weight:700;text-transform:uppercase}.muted,small{color:var(--muted)}.controls{display:flex;flex-wrap:wrap;gap:16px;margin:28px 0}.controls label{display:grid;gap:6px;font-size:13px}select,button{min-height:44px;padding:10px 14px;border:1px solid var(--line);border-radius:12px;background:#fff9e9;color:var(--ink);font-size:15px;max-width:100%}.columns{display:grid;grid-template-columns:1fr 1.25fr;gap:24px;align-items:start}article,.notice{border:1px solid var(--line);background:#fff8e4;border-radius:20px;padding:24px;min-width:0}.notice{margin:20px 0;background:#ece3c9}.primary{border-color:#cf915b}.period{border-top:1px solid var(--line);padding-top:12px;color:var(--accent)}.segment{border-top:1px solid var(--line);margin-top:22px;padding-top:18px}.reason{border-left:2px solid #cf915b;padding-left:14px;margin:18px 0}summary{cursor:pointer;color:var(--accent);padding:10px 0;min-height:44px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.55 system-ui,sans-serif}.gpt{white-space:pre-wrap;font-size:16px}a{color:var(--accent)}.gallery{display:flex;flex-wrap:wrap;gap:16px}.gallery a{width:min(100%,285px)}.gallery img{width:100%;height:auto;border:1px solid var(--line);border-radius:14px}@media(max-width:780px){main{padding:24px 16px}.columns{grid-template-columns:1fr}article{padding:20px}}:focus-visible{outline:3px solid #a44a16;outline-offset:3px}
</style><main>
<div class="eyebrow">Vedansh · Career & business pilot</div><h1>What changes when the person’s time changes?</h1><p>Six public or synthetic profiles · five instants · two questions · 60 engine readings. Six recorded GPT responses each compare two instants.</p>
<div class="notice"><strong>Review checkpoint, not a release approval.</strong> This combines the natal chart, running dasha and current Jupiter/Saturn transits. The seven other topics have not moved to this model. Source review and richer interpretation rules remain open. <a href="../../roadmap/conventions/prashna-phase-v1.md">Computation and rule register</a></div>
<div class="controls"><label>Person<select id="person"></select></label><label>Question<select id="topic"><option value="naukri">Considering a job switch</option><option value="vyapar">Considering a business partnership</option></select></label><label>As of<select id="date"></select></label><label>Engine language<select id="language"><option value="en">English</option><option value="hi">हिन्दी</option></select></label></div>
<p id="facts" class="muted"></p><div class="columns"><article id="before"></article><article id="after" class="primary"></article></div>
<article class="segment"><div class="eyebrow">Actual external evaluation</div><h2>GPT’s independent reading</h2><p id="gptmeta" class="muted"></p><details open><summary>Read the recorded response for this person</summary><div id="gpt" class="gpt"></div></details></article>
<div class="notice"><strong>Review findings:</strong> GPT writes more specific narratives, but is not a factual oracle. In Kabir’s response it calls the tenth house Aquarius and its lord Saturn; the supplied chart says Pisces and Jupiter. Several responses claim vedha information is missing despite receiving all transit houses. Our pilot is narrower and can return limited timing where GPT fills in a broader narrative. Across 60 engine readings, 40 have a mixed headline and only four main direction texts appear. The reasons vary more, but the content still needs greater differentiation. These differences require rule review, not a vote.</div>
<article><div class="eyebrow">Other-platform evidence</div><h2>What can be compared honestly</h2><p><a href="https://cdn.astrosage.com/pdf/ca_report_pro_en.pdf">AstroSage public sample A</a> emphasises conventional and enterprising career types and lists occupational options. <a href="https://www.astrosage.com/pdf/as-career-report-en.pdf">Public sample B</a> provides a broader career report. The two birth inputs are reused here.</p><p>Neither report is a consultation answering our selected question at these current/future instants. They are useful communication references; they cannot validate this timing model. No AstroTalk consultation was obtained or fabricated.</p></article>
<article class="segment"><div class="eyebrow">Actual native app</div><h2>English & Hindi</h2><p>Current worktree JavaScript in the installed iOS debug shell. <a href="README.md">Review notes, screenshots, test results and limits</a>.</p><div class="gallery"><a href="screenshots/en-final/screenshots/01-current-phase.png"><img src="screenshots/en-final/screenshots/01-current-phase.png" alt="English current phase in the native app"></a><a href="screenshots/hi-375/screenshots/01-current-phase.png"><img src="screenshots/hi-375/screenshots/01-current-phase.png" alt="Hindi current phase in the native app"></a></div></article>
</main><script>
const data=DATA;const $=id=>document.getElementById(id);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const c of data.cases){const o=document.createElement('option');o.value=c.id;o.textContent=c.label;$('person').append(o)}$('person').value='aarav';
function dates(){const c=data.cases.find(c=>c.id===$('person').value);const old=$('date').value;$('date').replaceChildren();for(const r of c.readings.filter(r=>r.purpose==='naukri')){const o=document.createElement('option');o.value=r.label;o.textContent=r.label+' · '+new Date(r.asOf).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'medium'});$('date').append(o)}if([...$('date').options].some(o=>o.value===old))$('date').value=old;render()}
function render(){const c=data.cases.find(c=>c.id===$('person').value);const r=c.readings.find(r=>r.purpose===$('topic').value&&r.label===$('date').value);const p=r.phase;const l=$('language').value;const t=o=>esc(o[l]);const hd=(en,hi)=>l==='en'?en:hi;const old=r.previous; const dt=iso=>esc(new Date(iso).toLocaleDateString(l==='hi'?'hi-IN':'en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric'}));
$('facts').textContent=c.label+' · Birth UTC '+c.birth+' · As of '+r.asOf+' · '+r.milliseconds.toFixed(1)+' ms (Node, not a device benchmark)';
$('before').innerHTML='<div class="eyebrow">Previous natal-theme reading</div><h2>'+t(old.title)+'</h2><p>'+t(old.summary)+'</p>'+old.insights.map(i=>'<h3>'+t(i.title)+'</h3><p>'+t(i.meaning)+'</p>').join('')+'<h3>Previous checklist</h3>'+old.actions.map(a=>'<p>• '+t(a.text)+'</p>').join('');
$('after').innerHTML='<div class="eyebrow">'+hd('Your current phase','अभी का समय')+'</div><h2>'+t(p.title)+'</h2><p>'+t(p.summary)+'</p>'+(p.currentPeriod?'<p class="period">'+t(p.currentPeriod.label)+'<br><small>'+dt(p.currentPeriod.start)+' → '+dt(p.currentPeriod.end)+'</small></p>':'')+'<div class="segment"><div class="eyebrow">'+hd('Why this reading','ऐसा क्यों')+'</div>'+p.signals.filter(s=>s.layer!=='gochar'||s.houses.length).filter((s,i,a)=>!a.slice(0,i).some(x=>x.layer===s.layer&&x.graha===s.graha&&x.meaning.en===s.meaning.en)).map(s=>'<div class="reason"><h3>'+t(s.title)+'</h3><p>'+t(s.meaning)+'</p></div>').join('')+'</div><div class="segment"><div class="eyebrow">'+hd('Guidance for this phase','इस समय दिशा')+'</div>'+p.directions.map(d=>'<p>'+t(d.text)+'</p>').join('')+'</div>'+(p.next?'<div class="segment"><div class="eyebrow">'+hd('Next period change','अगली दशा का बदलाव')+'</div><p>'+t(p.next.date)+'</p><h3>'+t(p.next.title)+'</h3><p>'+t(p.next.text)+'</p></div>':'')+'<details><summary>'+hd('Calculation and source basis','गणना और आधार')+'</summary><pre>'+esc(JSON.stringify(p,null,2))+'</pre></details><small>'+t(p.limitation)+'</small>';
const g=c.gpt;$('gptmeta').textContent=g?g.returnedModel+' · response '+g.responseId+' · Original English output; covers Current date + After dasha boundary only. Question: '+JSON.parse(g.request.input).question:'No recorded response';$('gpt').textContent=g?g.text:'Not evaluated';document.documentElement.lang=l;}
$('person').addEventListener('change',dates);for(const id of ['topic','date','language'])$(id).addEventListener('change',render);dates();
</script></html>'''
(out / 'comparison.html').write_text(html.replace('DATA', json.dumps(data, ensure_ascii=False).replace('<','\\u003c')))
print(out / 'comparison.html')
