/**
 * Authored content for one Upanishad — consumed by scripts/build-upanishad.mjs.
 * `muktika` is the text's fixed number in the Muktika canon (1–108) and is the
 * reader's `chapter` id forever; `slug` must match `registry.ts`.
 *
 * Muṇḍaka — Atharvaveda. Three muṇḍakas × two khaṇḍas (9 · 13 · 10 · 11 · 10 · 11 = 64),
 * cited muṇḍaka.khaṇḍa.mantra. Meanings follow Śaṅkara.
 */
const M = (lines, meaningHi, meaningEn) => ({ lines, meaningHi, meaningEn });

export default {
  slug: 'mundaka',
  muktika: 5,
  vedaHi: 'अथर्ववेद',
  vedaEn: 'Atharvaveda',
  source: {
    baseText:
      'Atharvaveda (Śaunaka) recension with Śāṅkara-bhāṣya, as printed in Gita Press "ईशादि नौ उपनिषद्"; Devanagari written out from the printed text and checked against the Advaita Ashrama edition.',
    canonicalEdition: 'Gita Press Gorakhpur, ईशादि नौ उपनिषद् (शांकरभाष्यार्थ सहित), code 66',
    referenceUrls: [
      'https://sanskritdocuments.org/doc_upanishhat/mundaka.html',
      'https://www.wisdomlib.org/hinduism/book/mundaka-upanishad-shankara-bhashya',
      'https://archive.org/details/IshadiNauUpanishadGitaPress',
    ],
    notes:
      '64 mantras plus the Atharvavedic śānti-pāṭha (भद्रं कर्णेभिः) as page 1. 2.2.7 keeps its traditional four lines under one number. Vedic anunāsika ligatures are written with the standard anusvāra. Devanagari was authored from memory of the printed text with no network source available at build time — a line-by-line check against the Gita Press scan is still owed.',
    retrievedOn: '2026-09-25',
  },
  shanti: M(
    [
      'ॐ भद्रं कर्णेभिः शृणुयाम देवाः भद्रं पश्येमाक्षभिर्यजत्राः।',
      'स्थिरैरङ्गैस्तुष्टुवांसस्तनूभिर्व्यशेम देवहितं यदायुः।',
      'स्वस्ति न इन्द्रो वृद्धश्रवाः स्वस्ति नः पूषा विश्ववेदाः।',
      'स्वस्ति नस्तार्क्ष्यो अरिष्टनेमिः स्वस्ति नो बृहस्पतिर्दधातु॥',
      'ॐ शान्तिः शान्तिः शान्तिः॥',
    ],
    'हे देवों! हम कानों से शुभ सुनें; हे यज्ञार्ह देवों! हम नेत्रों से शुभ देखें। स्थिर अंगों और शरीरों से आपकी स्तुति करते हुए हम देवों के हित की आयु प्राप्त करें। महान यशस्वी इन्द्र हमारा कल्याण करें; सर्वज्ञ पूषा हमारा कल्याण करें; अरिष्टनेमि तार्क्ष्य (गरुड़) हमारा कल्याण करें; बृहस्पति हमारा कल्याण करें। ॐ शान्तिः शान्तिः शान्तिः।',
    'O gods, may we hear what is auspicious with our ears; O you worthy of worship, may we see what is auspicious with our eyes. Praising you with steady limbs and bodies, may we live the full span the gods have allotted. May Indra of great renown bless us; may all-knowing Pūṣan bless us; may Tārkṣya (Garuḍa) of unhindered course bless us; may Bṛhaspati grant us well-being. Om, peace, peace, peace.'
  ),
  khandas: [
    // ── Muṇḍaka 1 ──────────────────────────────────────────────────────────
    [
      [
        M(['ॐ ब्रह्मा देवानां प्रथमः सम्बभूव विश्वस्य कर्ता भुवनस्य गोप्ता।', 'स ब्रह्मविद्यां सर्वविद्याप्रतिष्ठामथर्वाय ज्येष्ठपुत्राय प्राह॥'],
          'देवताओं में सबसे पहले ब्रह्मा प्रकट हुए — विश्व के कर्ता और भुवन के रक्षक। उन्होंने समस्त विद्याओं की आधारभूत ब्रह्मविद्या अपने ज्येष्ठ पुत्र अथर्वा को कही।',
          'Brahmā arose first among the gods, the maker of all, the guardian of the world. He taught the knowledge of Brahman, the foundation of all knowledge, to his eldest son Atharvā.'),
        M(['अथर्वणे यां प्रवदेत ब्रह्माऽथर्वा तां पुरोवाचाङ्गिरे ब्रह्मविद्याम्।', 'स भारद्वाजाय सत्यवहाय प्राह भारद्वाजोऽङ्गिरसे परावराम्॥'],
          'जो ब्रह्मविद्या ब्रह्मा ने अथर्वा को कही, वह अथर्वा ने पूर्वकाल में अङ्गिर् को कही। अङ्गिर् ने उसे भारद्वाज सत्यवाह को कहा, और भारद्वाज ने परावर-रूप वह विद्या अङ्गिरा को कही।',
          'The knowledge Brahmā gave to Atharvā, Atharvā of old told to Aṅgir; Aṅgir told it to Satyavāha of the Bhāradvāja line, and Bhāradvāja passed on that knowledge, higher and lower, to Aṅgiras.'),
        M(['शौनको ह वै महाशालोऽङ्गिरसं विधिवदुपसन्नः पप्रच्छ।', 'कस्मिन्नु भगवो विज्ञाते सर्वमिदं विज्ञातं भवतीति॥'],
          'महागृहस्थ शौनक ने विधिपूर्वक अङ्गिरा के पास जाकर पूछा — "भगवन्! किसको जान लेने पर यह सब कुछ जाना हुआ हो जाता है?"',
          'Śaunaka, the great householder, approached Aṅgiras in the prescribed manner and asked: "Revered sir, what is that by knowing which all this becomes known?"'),
        M(['तस्मै स होवाच।', 'द्वे विद्ये वेदितव्ये इति ह स्म यद्ब्रह्मविदो वदन्ति परा चैवापरा च॥'],
          'उन्होंने उससे कहा — ब्रह्मवेत्ता कहते हैं कि दो विद्याएँ जानने योग्य हैं — परा और अपरा।',
          'He said to him: There are two kinds of knowledge to be known, so say the knowers of Brahman — the higher and the lower.'),
        M(['तत्रापरा ऋग्वेदो यजुर्वेदः सामवेदोऽथर्ववेदः शिक्षा कल्पो व्याकरणं निरुक्तं छन्दो ज्योतिषमिति।', 'अथ परा यया तदक्षरमधिगम्यते॥'],
          'उनमें अपरा विद्या है — ऋग्वेद, यजुर्वेद, सामवेद, अथर्ववेद, शिक्षा, कल्प, व्याकरण, निरुक्त, छन्द और ज्योतिष। और परा विद्या वह है जिससे वह अक्षर (ब्रह्म) जाना जाता है।',
          'Of these, the lower is the Ṛgveda, Yajurveda, Sāmaveda, Atharvaveda, phonetics, ritual, grammar, etymology, metre and astronomy. The higher is that by which the Imperishable is reached.'),
        M(['यत्तदद्रेश्यमग्राह्यमगोत्रमवर्णमचक्षुःश्रोत्रं तदपाणिपादम्।', 'नित्यं विभुं सर्वगतं सुसूक्ष्मं तदव्ययं यद्भूतयोनिं परिपश्यन्ति धीराः॥'],
          'जो अदृश्य, अग्राह्य, गोत्ररहित, वर्णरहित, नेत्र-श्रोत्ररहित, हाथ-पैर रहित है; जो नित्य, विभु, सर्वव्यापी, अत्यन्त सूक्ष्म और अविनाशी है — समस्त प्राणियों के उस उद्गम को धीर पुरुष सर्वत्र देखते हैं।',
          'That which is unseen, ungraspable, without lineage or colour, without eyes or ears, without hands or feet; eternal, all-pervading, omnipresent, most subtle, imperishable — the source of all beings — that the wise behold everywhere.'),
        M(['यथोर्णनाभिः सृजते गृह्णते च यथा पृथिव्यामोषधयः सम्भवन्ति।', 'यथा सतः पुरुषात्केशलोमानि तथाऽक्षरात्सम्भवतीह विश्वम्॥'],
          'जैसे मकड़ी (जाला) रचती और समेट लेती है, जैसे पृथ्वी पर औषधियाँ उत्पन्न होती हैं, जैसे जीवित पुरुष से केश और रोम निकलते हैं — वैसे ही उस अक्षर से यह विश्व उत्पन्न होता है।',
          'As a spider sends forth and draws in its thread, as plants grow on the earth, as hair grows on the head and body of a living person — so from the Imperishable arises this universe.'),
        M(['तपसा चीयते ब्रह्म ततोऽन्नमभिजायते।', 'अन्नात्प्राणो मनः सत्यं लोकाः कर्मसु चामृतम्॥'],
          'तप (ज्ञानरूप संकल्प) से ब्रह्म बढ़ता है, उससे अन्न (अव्याकृत) उत्पन्न होता है; अन्न से प्राण, मन, सत्य (पञ्चभूत), लोक और कर्मों में अमृत (फल) उत्पन्न होते हैं।',
          'Through the heat of knowledge Brahman expands; from that comes food (the unmanifest); from food come breath, mind, the elements, the worlds, and in works their immortal fruit.'),
        M(['यः सर्वज्ञः सर्वविद्यस्य ज्ञानमयं तपः।', 'तस्मादेतद्ब्रह्म नाम रूपमन्नं च जायते॥'],
          'जो सर्वज्ञ और सर्ववित् है, जिसका तप ज्ञानमय है — उससे यह (कार्य) ब्रह्म, नाम, रूप और अन्न उत्पन्न होते हैं।',
          'From Him who knows all and knows every thing, whose austerity is made of knowledge, is born this Brahman (Hiraṇyagarbha), name, form and food.'),
      ],
      [
        M(['तदेतत्सत्यं मन्त्रेषु कर्माणि कवयो यान्यपश्यंस्तानि त्रेतायां बहुधा सन्ततानि।', 'तान्याचरथ नियतं सत्यकामा एष वः पन्थाः सुकृतस्य लोके॥'],
          'यह सत्य है — मन्त्रों में ऋषियों ने जो कर्म देखे, वे त्रेता (तीन वेदों) में अनेक प्रकार से फैले हुए हैं। हे सत्यकामो! उनका नियमपूर्वक आचरण करो; कर्मफल के लोक में यही तुम्हारा मार्ग है।',
          'This is the truth: the rites the seers saw in the mantras are spread out in many ways across the three Vedas. Perform them faithfully, you who desire the true; this is your path to the world of good works.'),
        M(['यदा लेलायते ह्यर्चिः समिद्धे हव्यवाहने।', 'तदाऽऽज्यभागावन्तरेणाहुतीः प्रतिपादयेत्॥'],
          'जब प्रज्वलित अग्नि में ज्वाला लहराने लगे, तब दोनों आज्यभागों के बीच में श्रद्धापूर्वक आहुतियाँ दे।',
          'When the flame flickers in the well-kindled fire, then, between the two offerings of clarified butter, one should place the oblations with faith.'),
        M(['यस्याग्निहोत्रमदर्शमपौर्णमासमचातुर्मास्यमनाग्रयणमतिथिवर्जितं च।', 'अहुतमवैश्वदेवमविधिना हुतमासप्तमांस्तस्य लोकान्हिनस्ति॥'],
          'जिसका अग्निहोत्र दर्श, पौर्णमास, चातुर्मास्य और आग्रयण से रहित है, अतिथि-सेवा से रहित है, जो समय पर नहीं किया गया, वैश्वदेव से रहित है या अविधि से किया गया है — वह उसके सातों लोकों को नष्ट कर देता है।',
          'If one\'s Agnihotra lacks the new-moon and full-moon rites, the four-monthly and harvest rites, is without guests, without the offering to all gods, or is performed against the rule — it destroys his seven worlds.'),
        M(['काली कराली च मनोजवा च सुलोहिता या च सुधूम्रवर्णा।', 'स्फुलिङ्गिनी विश्वरुची च देवी लेलायमाना इति सप्त जिह्वाः॥'],
          'काली, कराली, मनोजवा, सुलोहिता, सुधूम्रवर्णा, स्फुलिङ्गिनी और विश्वरुची देवी — ये (अग्नि की) लहराती हुई सात जिह्वाएँ हैं।',
          'Kālī, Karālī, Manojavā, Sulohitā, Sudhūmravarṇā, Sphuliṅginī and the bright Viśvarucī — these are the seven flickering tongues of the fire.'),
        M(['एतेषु यश्चरते भ्राजमानेषु यथाकालं चाहुतयो ह्याददायन्।', 'तं नयन्त्येताः सूर्यस्य रश्मयो यत्र देवानां पतिरेकोऽधिवासः॥'],
          'जो इन प्रकाशमान ज्वालाओं में यथासमय आहुतियाँ देता हुआ कर्म करता है, उसे ये आहुतियाँ सूर्य की किरणें बनकर वहाँ ले जाती हैं जहाँ देवताओं का एक अधिपति निवास करता है।',
          'Whoever performs his rites while these flames blaze, offering oblations at the right time — those oblations, becoming rays of the sun, lead him to where the one Lord of the gods dwells.'),
        M(['एह्येहीति तमाहुतयः सुवर्चसः सूर्यस्य रश्मिभिर्यजमानं वहन्ति।', 'प्रियां वाचमभिवदन्त्योऽर्चयन्त्य एष वः पुण्यः सुकृतो ब्रह्मलोकः॥'],
          '"आओ, आओ" — कहती हुई तेजोमयी आहुतियाँ सूर्य की किरणों से यजमान को ले जाती हैं, प्रिय वचन बोलती और सम्मान करती हुई — "यह तुम्हारे सुकृत से अर्जित पुण्य ब्रह्मलोक है।"',
          '"Come, come!" — so the radiant oblations carry the sacrificer on the rays of the sun, speaking sweet words and honouring him: "This is the holy world of Brahmā, earned by your good deeds."'),
        M(['प्लवा ह्येते अदृढा यज्ञरूपा अष्टादशोक्तमवरं येषु कर्म।', 'एतच्छ्रेयो येऽभिनन्दन्ति मूढा जरामृत्युं ते पुनरेवापि यन्ति॥'],
          'ये अठारह (अंगों वाले) यज्ञरूप नौकाएँ अदृढ़ (टूटने वाली) हैं, जिनमें निकृष्ट कर्म कहा गया है। जो मूढ़ इसे ही श्रेय मानकर अभिनन्दन करते हैं, वे फिर-फिर जरा और मृत्यु को प्राप्त होते हैं।',
          'Frail indeed are these boats of sacrifice, the eighteen in which the lower work is prescribed. The deluded who hail this as the highest good go again and again to old age and death.'),
        M(['अविद्यायामन्तरे वर्तमानाः स्वयं धीराः पण्डितंमन्यमानाः।', 'जङ्घन्यमानाः परियन्ति मूढा अन्धेनैव नीयमाना यथान्धाः॥'],
          'अविद्या के भीतर रहते हुए भी अपने को धीर और पण्डित मानने वाले मूढ़ लोग बार-बार पीड़ित होकर भटकते हैं — जैसे अन्धे के द्वारा ले जाए जाते हुए अन्धे।',
          'Dwelling in the midst of ignorance yet thinking themselves wise and learned, the deluded wander about, battered again and again, like the blind led by the blind.'),
        M(['अविद्यायां बहुधा वर्तमाना वयं कृतार्था इत्यभिमन्यन्ति बालाः।', 'यत्कर्मिणो न प्रवेदयन्ति रागात्तेनातुराः क्षीणलोकाश्च्यवन्ते॥'],
          'अनेक प्रकार की अविद्या में रहते हुए अज्ञानी मानते हैं कि "हम कृतार्थ हो गए"। कर्मी लोग आसक्ति के कारण तत्त्व को नहीं जानते, इसलिए दुःखी होकर, पुण्य क्षीण होने पर, (स्वर्ग से) गिर जाते हैं।',
          'Living in manifold ignorance, the childish think "we have reached the goal". Because attachment keeps the ritualists from knowing the truth, they sink down, afflicted, when their merit is spent.'),
        M(['इष्टापूर्तं मन्यमाना वरिष्ठं नान्यच्छ्रेयो वेदयन्ते प्रमूढाः।', 'नाकस्य पृष्ठे ते सुकृतेऽनुभूत्वेमं लोकं हीनतरं वा विशन्ति॥'],
          'यज्ञ और परोपकार को ही सर्वश्रेष्ठ मानने वाले प्रमूढ़ लोग दूसरा कोई श्रेय नहीं जानते। वे स्वर्ग के शिखर पर अपने पुण्य का भोग कर इस लोक में या इससे भी निकृष्ट लोक में प्रवेश करते हैं।',
          'Regarding sacrifice and charity as the highest, the utterly deluded know no other good. Having enjoyed their merit on the heights of heaven, they enter this world again, or one lower still.'),
        M(['तपःश्रद्धे ये ह्युपवसन्त्यरण्ये शान्ता विद्वांसो भैक्ष्यचर्यां चरन्तः।', 'सूर्यद्वारेण ते विरजाः प्रयान्ति यत्रामृतः स पुरुषो ह्यव्ययात्मा॥'],
          'जो शान्त विद्वान् वन में तप और श्रद्धा का सेवन करते हुए भिक्षाचर्या से रहते हैं, वे निष्पाप होकर सूर्यद्वार से वहाँ जाते हैं जहाँ वह अमृत, अविनाशी पुरुष है।',
          'But those who live in the forest with austerity and faith, tranquil and wise, living on alms — they go, freed from stain, through the door of the sun to where dwells that immortal Person of imperishable nature.'),
        M(['परीक्ष्य लोकान्कर्मचितान्ब्राह्मणो निर्वेदमायान्नास्त्यकृतः कृतेन।', 'तद्विज्ञानार्थं स गुरुमेवाभिगच्छेत्समित्पाणिः श्रोत्रियं ब्रह्मनिष्ठम्॥'],
          'कर्मों से प्राप्त होने वाले लोकों की परीक्षा करके ब्राह्मण वैराग्य को प्राप्त हो — "किए हुए (कर्म) से अकृत (नित्य ब्रह्म) नहीं मिलता।" उसे जानने के लिए वह हाथ में समिधा लेकर श्रोत्रिय और ब्रह्मनिष्ठ गुरु के पास ही जाए।',
          'Having examined the worlds won by works, let the seeker grow dispassionate: the uncreated is not gained by what is done. To know it, let him go, fuel in hand, to a teacher learned in the scriptures and established in Brahman.'),
        M(['तस्मै स विद्वानुपसन्नाय सम्यक्प्रशान्तचित्ताय शमान्विताय।', 'येनाक्षरं पुरुषं वेद सत्यं प्रोवाच तां तत्त्वतो ब्रह्मविद्याम्॥'],
          'भली-भाँति शरण में आए, प्रशान्तचित्त और इन्द्रिय-संयम से युक्त उस शिष्य को वह विद्वान् गुरु उस ब्रह्मविद्या को यथार्थ रूप में कहे, जिससे वह सत्य अक्षर पुरुष जाना जाता है।',
          'To that disciple who has duly approached, whose mind is fully calmed and senses controlled, the wise teacher should truly teach the knowledge of Brahman by which the true, imperishable Person is known.'),
      ],
    ],
    // ── Muṇḍaka 2 ──────────────────────────────────────────────────────────
    [
      [
        M(['तदेतत्सत्यं यथा सुदीप्तात्पावकाद्विस्फुलिङ्गाः सहस्रशः प्रभवन्ते सरूपाः।', 'तथाऽक्षराद्विविधाः सोम्य भावाः प्रजायन्ते तत्र चैवापि यन्ति॥'],
          'यह सत्य है — जैसे प्रज्वलित अग्नि से उसी के समान रूप वाली हजारों चिनगारियाँ निकलती हैं, वैसे ही हे सोम्य! उस अक्षर से विविध भाव (प्राणी) उत्पन्न होते हैं और उसी में लौट जाते हैं।',
          'This is the truth: as from a blazing fire thousands of sparks of its own nature leap forth, so, my dear, from the Imperishable arise beings of many kinds, and into it they return.'),
        M(['दिव्यो ह्यमूर्तः पुरुषः स बाह्याभ्यन्तरो ह्यजः।', 'अप्राणो ह्यमनाः शुभ्रो ह्यक्षरात्परतः परः॥'],
          'वह पुरुष दिव्य और निराकार है; वह बाहर-भीतर सर्वत्र है, अजन्मा है। वह प्राणरहित, मनरहित, शुद्ध और अक्षर (अव्याकृत) से भी परे, परम है।',
          'Divine and formless is that Person, within and without, unborn; without breath, without mind, pure, higher than the high Imperishable.'),
        M(['एतस्माज्जायते प्राणो मनः सर्वेन्द्रियाणि च।', 'खं वायुर्ज्योतिरापः पृथिवी विश्वस्य धारिणी॥'],
          'इसी से प्राण, मन और समस्त इन्द्रियाँ उत्पन्न होती हैं; आकाश, वायु, तेज, जल और विश्व को धारण करने वाली पृथ्वी भी।',
          'From Him are born breath, mind and all the senses; space, air, fire, water, and the earth that supports all.'),
        M(['अग्निर्मूर्धा चक्षुषी चन्द्रसूर्यौ दिशः श्रोत्रे वाग्विवृताश्च वेदाः।', 'वायुः प्राणो हृदयं विश्वमस्य पद्भ्यां पृथिवी ह्येष सर्वभूतान्तरात्मा॥'],
          'अग्नि उसका सिर है, चन्द्र और सूर्य नेत्र, दिशाएँ कान, प्रकट वेद वाणी, वायु प्राण, विश्व हृदय और पृथ्वी उसके चरणों से उत्पन्न है — यही समस्त प्राणियों का अन्तरात्मा है।',
          'Fire is His head, the sun and moon His eyes, the directions His ears, the revealed Vedas His speech, the wind His breath, the universe His heart; from His feet came the earth. He is the inner Self of all beings.'),
        M(['तस्मादग्निः समिधो यस्य सूर्यः सोमात्पर्जन्य ओषधयः पृथिव्याम्।', 'पुमान्रेतः सिञ्चति योषितायां बह्वीः प्रजाः पुरुषात्सम्प्रसूताः॥'],
          'उससे वह (स्वर्ग) अग्नि उत्पन्न हुई जिसकी समिधा सूर्य है; चन्द्र से मेघ, मेघ से पृथ्वी पर औषधियाँ; पुरुष स्त्री में वीर्य सिञ्चन करता है — इस प्रकार उस पुरुष से अनेक प्रजाएँ उत्पन्न हुई हैं।',
          'From Him comes the fire whose fuel is the sun; from the moon, rain; from rain, the plants on earth; man pours seed into woman — thus from the Person have sprung the many creatures.'),
        M(['तस्मादृचः साम यजूंषि दीक्षा यज्ञाश्च सर्वे क्रतवो दक्षिणाश्च।', 'संवत्सरश्च यजमानश्च लोकाः सोमो यत्र पवते यत्र सूर्यः॥'],
          'उससे ही ऋचाएँ, साम, यजु, दीक्षा, समस्त यज्ञ, क्रतु और दक्षिणाएँ; संवत्सर, यजमान और वे लोक जहाँ चन्द्र पवित्र करता है और जहाँ सूर्य (प्रकाशता है) — उत्पन्न हुए।',
          'From Him come the Ṛk, Sāma and Yajus verses, initiation, all sacrifices and rites and gifts; the year, the sacrificer, and the worlds where the moon purifies and the sun shines.'),
        M(['तस्माच्च देवा बहुधा सम्प्रसूताः साध्या मनुष्याः पशवो वयांसि।', 'प्राणापानौ व्रीहियवौ तपश्च श्रद्धा सत्यं ब्रह्मचर्यं विधिश्च॥'],
          'उससे ही अनेक प्रकार के देवता, साध्य, मनुष्य, पशु, पक्षी, प्राण-अपान, धान-जौ, तप, श्रद्धा, सत्य, ब्रह्मचर्य और विधि उत्पन्न हुए हैं।',
          'From Him too are born the many gods, the Sādhyas, humans, beasts and birds; the in-breath and out-breath, rice and barley, austerity, faith, truth, chastity and the rule of life.'),
        M(['सप्त प्राणाः प्रभवन्ति तस्मात्सप्तार्चिषः समिधः सप्त होमाः।', 'सप्त इमे लोका येषु चरन्ति प्राणा गुहाशया निहिताः सप्त सप्त॥'],
          'उससे सात प्राण (इन्द्रियाँ) उत्पन्न होते हैं, सात ज्वालाएँ (विषय-प्रकाश), सात समिधाएँ, सात होम (विषय-ज्ञान), और ये सात लोक (इन्द्रिय-गोलक) जिनमें हृदय-गुहा में रखे हुए प्राण विचरते हैं — प्रत्येक प्राणी में सात-सात।',
          'From Him spring the seven breaths, the seven flames, the seven fuels, the seven oblations, and these seven worlds in which the breaths move, laid in the cave of the heart, seven in each.'),
        M(['अतः समुद्रा गिरयश्च सर्वेऽस्मात्स्यन्दन्ते सिन्धवः सर्वरूपाः।', 'अतश्च सर्वा ओषधयो रसश्च येनैष भूतैस्तिष्ठते ह्यन्तरात्मा॥'],
          'इसी से समस्त समुद्र और पर्वत हैं; इसी से सब प्रकार की नदियाँ बहती हैं; इसी से सब औषधियाँ और रस हैं, जिससे यह अन्तरात्मा (सूक्ष्म शरीर) पञ्चभूतों के साथ स्थित रहता है।',
          'From Him come all the oceans and mountains; from Him flow rivers of every kind; from Him come all plants and their essence, by which the inner self dwells among the elements.'),
        M(['पुरुष एवेदं विश्वं कर्म तपो ब्रह्म परामृतम्।', 'एतद्यो वेद निहितं गुहायां सोऽविद्याग्रन्थिं विकिरतीह सोम्य॥'],
          'यह समस्त विश्व — कर्म, तप, (कार्य) ब्रह्म — परम अमृत पुरुष ही है। हे सोम्य! जो इसे हृदय-गुहा में स्थित जानता है, वह यहीं अविद्या की गाँठ को छिन्न-भिन्न कर देता है।',
          'The Person alone is all this — work, austerity, Brahman, the supreme immortal. My dear, one who knows this, hidden in the cave of the heart, cuts asunder the knot of ignorance here and now.'),
      ],
      [
        M(['आविः सन्निहितं गुहाचरं नाम महत्पदमत्रैतत्समर्पितम्।', 'एजत्प्राणन्निमिषच्च यदेतज्जानथ सदसद्वरेण्यं परं विज्ञानाद्यद्वरिष्ठं प्रजानाम्॥'],
          'वह प्रकाशमान, अत्यन्त निकट, हृदय-गुहा में विचरने वाला महान् पद है; जो चलता, श्वास लेता और पलक झपकाता है — वह सब इसी में अर्पित है। इसे सत्-असत्, वरणीय, विज्ञान से परे और प्रजाओं के लिए सर्वश्रेष्ठ जानो।',
          'Radiant, near at hand, moving in the cave of the heart — the great goal; on it rests all that moves, breathes and blinks. Know it as being and non-being, the most desirable, beyond understanding, the highest of all for creatures.'),
        M(['यदर्चिमद्यदणुभ्योऽणु च यस्मिँल्लोका निहिता लोकिनश्च।', 'तदेतदक्षरं ब्रह्म स प्राणस्तदु वाङ्मनः तदेतत्सत्यं तदमृतं तद्वेद्धव्यं सोम्य विद्धि॥'],
          'जो ज्योतिर्मय है, जो सूक्ष्म से भी सूक्ष्म है, जिसमें लोक और लोकवासी स्थित हैं — वही यह अक्षर ब्रह्म है, वही प्राण, वाणी और मन है; वही सत्य और अमृत है। हे सोम्य! उसे ही वेधना (लक्ष्य करना) है — वेधो।',
          'That which is luminous, subtler than the subtle, in which rest the worlds and their dwellers — that is the imperishable Brahman; that is breath, speech and mind; that is truth, that is immortal. That, my dear, is the mark to be pierced — pierce it.'),
        M(['धनुर्गृहीत्वौपनिषदं महास्त्रं शरं ह्युपासानिशितं सन्धयीत।', 'आयम्य तद्भावगतेन चेतसा लक्ष्यं तदेवाक्षरं सोम्य विद्धि॥'],
          'उपनिषद्-रूप महान् धनुष को लेकर उस पर उपासना से तीक्ष्ण किए हुए बाण को चढ़ाए। उसे तद्भाव में लीन चित्त से खींचकर, हे सोम्य! उसी अक्षर को लक्ष्य जानकर वेधो।',
          'Take up the great bow of the Upaniṣad, fit to it the arrow sharpened by meditation; draw it with a mind absorbed in That, and, my dear, pierce the Imperishable as the target.'),
        M(['प्रणवो धनुः शरो ह्यात्मा ब्रह्म तल्लक्ष्यमुच्यते।', 'अप्रमत्तेन वेद्धव्यं शरवत्तन्मयो भवेत्॥'],
          'प्रणव (ॐ) धनुष है, आत्मा बाण है और ब्रह्म उसका लक्ष्य कहा गया है। सावधान होकर उसे वेधना चाहिए और बाण की तरह तन्मय हो जाना चाहिए।',
          'Om is the bow, the self is the arrow, Brahman is called the target. It is to be pierced by one who is undistracted; and, like the arrow, one should become one with it.'),
        M(['यस्मिन्द्यौः पृथिवी चान्तरिक्षमोतं मनः सह प्राणैश्च सर्वैः।', 'तमेवैकं जानथ आत्मानमन्या वाचो विमुञ्चथामृतस्यैष सेतुः॥'],
          'जिसमें स्वर्ग, पृथ्वी और अन्तरिक्ष ओतप्रोत हैं, तथा समस्त प्राणों के साथ मन भी — उसी एक को आत्मा जानो; अन्य वचनों को छोड़ दो। यही अमृत का सेतु है।',
          'In whom are woven heaven, earth and the space between, and the mind with all the breaths — know Him alone as the Self and leave off other words. This is the bridge to immortality.'),
        M(['अरा इव रथनाभौ संहता यत्र नाड्यः स एषोऽन्तश्चरते बहुधा जायमानः।', 'ओमित्येवं ध्यायथ आत्मानं स्वस्ति वः पाराय तमसः परस्तात्॥'],
          'जैसे रथ की नाभि में अरे जुड़े रहते हैं, वैसे जहाँ (हृदय में) नाड़ियाँ मिलती हैं — वहाँ यह आत्मा अनेक रूप से प्रकट होता हुआ भीतर विचरता है। "ॐ" — इस प्रकार आत्मा का ध्यान करो। अन्धकार के परे पार जाने के लिए तुम्हारा कल्याण हो।',
          'Where the veins meet like spokes in the hub of a wheel, there He moves within, becoming manifold. Meditate on the Self as Om. May you fare well in crossing to the far shore beyond darkness.'),
        M(['यः सर्वज्ञः सर्वविद्यस्यैष महिमा भुवि।', 'दिव्ये ब्रह्मपुरे ह्येष व्योम्न्यात्मा प्रतिष्ठितः॥', 'मनोमयः प्राणशरीरनेता प्रतिष्ठितोऽन्ने हृदयं सन्निधाय।', 'तद्विज्ञानेन परिपश्यन्ति धीरा आनन्दरूपममृतं यद्विभाति॥'],
          'जो सर्वज्ञ और सर्ववित् है, जिसकी यह महिमा पृथ्वी पर है — वह आत्मा दिव्य ब्रह्मपुर (हृदय) के आकाश में प्रतिष्ठित है। वह मनोमय है, प्राण और शरीर का नेता है, अन्न (देह) में हृदय को आश्रय बनाकर स्थित है। उसके विज्ञान से धीर पुरुष उस आनन्दरूप अमृत को सर्वत्र देखते हैं जो प्रकाशमान है।',
          'He who knows all and knows every thing, whose glory this is on earth — that Self is established in the space within the divine city of Brahman, the heart. Made of mind, leader of breath and body, He rests in food, seated in the heart. Through knowledge of Him the wise behold everywhere that which shines as immortal bliss.'),
        M(['भिद्यते हृदयग्रन्थिश्छिद्यन्ते सर्वसंशयाः।', 'क्षीयन्ते चास्य कर्माणि तस्मिन्दृष्टे परावरे॥'],
          'उस पर-अवर (कारण-कार्य रूप) ब्रह्म का दर्शन हो जाने पर हृदय की गाँठ टूट जाती है, सब संशय कट जाते हैं और इसके कर्म क्षीण हो जाते हैं।',
          'The knot of the heart is loosened, all doubts are cut away, and his works come to an end when He, the high and the low, is seen.'),
        M(['हिरण्मये परे कोशे विरजं ब्रह्म निष्कलम्।', 'तच्छुभ्रं ज्योतिषां ज्योतिस्तद्यदात्मविदो विदुः॥'],
          'सुवर्णमय परम कोश (हृदय) में निर्मल, निरवयव ब्रह्म है। वह शुद्ध है, ज्योतियों की ज्योति है — आत्मवेत्ता उसे ही जानते हैं।',
          'In the highest golden sheath is Brahman, stainless and without parts. Pure it is, the light of lights — that is what the knowers of the Self know.'),
        M(['न तत्र सूर्यो भाति न चन्द्रतारकं नेमा विद्युतो भान्ति कुतोऽयमग्निः।', 'तमेव भान्तमनुभाति सर्वं तस्य भासा सर्वमिदं विभाति॥'],
          'वहाँ न सूर्य प्रकाशता है, न चन्द्र-तारे, न ये बिजलियाँ चमकती हैं — फिर यह अग्नि कैसे? उसके प्रकाशित होने पर ही सब प्रकाशित होता है; उसकी भा से यह सब कुछ प्रकाशमान है।',
          'There the sun does not shine, nor the moon and stars, nor do these lightnings shine — how then this fire? All this shines only after Him who shines; by His light all this is lit.'),
        M(['ब्रह्मैवेदममृतं पुरस्ताद्ब्रह्म पश्चाद्ब्रह्म दक्षिणतश्चोत्तरेण।', 'अधश्चोर्ध्वं च प्रसृतं ब्रह्मैवेदं विश्वमिदं वरिष्ठम्॥'],
          'यह अमृत ब्रह्म ही आगे है, ब्रह्म ही पीछे है, ब्रह्म ही दक्षिण और उत्तर में है, नीचे और ऊपर भी फैला हुआ है। यह समस्त विश्व वह सर्वश्रेष्ठ ब्रह्म ही है।',
          'This immortal Brahman is in front, Brahman behind, Brahman to the right and to the left; spread out below and above — Brahman alone is all this, the supreme.'),
      ],
    ],
    // ── Muṇḍaka 3 ──────────────────────────────────────────────────────────
    [
      [
        M(['द्वा सुपर्णा सयुजा सखाया समानं वृक्षं परिषस्वजाते।', 'तयोरन्यः पिप्पलं स्वाद्वत्त्यनश्नन्नन्यो अभिचाकशीति॥'],
          'सदा साथ रहने वाले दो सखा पक्षी एक ही वृक्ष पर बैठे हैं। उनमें से एक (जीव) उसके स्वादु फल खाता है, दूसरा (ईश्वर) बिना खाए केवल देखता रहता है।',
          'Two birds, inseparable companions, cling to the same tree. One of them eats the sweet fruit; the other looks on without eating.'),
        M(['समाने वृक्षे पुरुषो निमग्नोऽनीशया शोचति मुह्यमानः।', 'जुष्टं यदा पश्यत्यन्यमीशमस्य महिमानमिति वीतशोकः॥'],
          'उसी वृक्ष (शरीर) में डूबा हुआ पुरुष असमर्थता से मोहित होकर शोक करता है। जब वह सबके द्वारा सेवित दूसरे — ईश्वर — को और उसकी महिमा को देखता है, तब शोकरहित हो जाता है।',
          'Sunk in the same tree, the person grieves, deluded by helplessness. But when he sees the other, the adored Lord, and His glory — he becomes free from sorrow.'),
        M(['यदा पश्यः पश्यते रुक्मवर्णं कर्तारमीशं पुरुषं ब्रह्मयोनिम्।', 'तदा विद्वान्पुण्यपापे विधूय निरञ्जनः परमं साम्यमुपैति॥'],
          'जब द्रष्टा उस सुवर्णवर्ण, कर्ता, ईश, पुरुष, ब्रह्म के उद्गम को देख लेता है, तब वह विद्वान् पुण्य-पाप दोनों को झाड़कर निर्मल हो परम साम्य को प्राप्त करता है।',
          'When the seer sees the golden-hued Person, the maker, the Lord, the source of Brahman — then, shaking off good and evil, stainless, he attains the supreme oneness.'),
        M(['प्राणो ह्येष यः सर्वभूतैर्विभाति विजानन्विद्वान्भवते नातिवादी।', 'आत्मक्रीड आत्मरतिः क्रियावानेष ब्रह्मविदां वरिष्ठः॥'],
          'यह वही प्राण (ईश्वर) है जो समस्त प्राणियों के रूप में प्रकाशित होता है। इसे जानने वाला विद्वान् अतिवादी नहीं होता। आत्मा में क्रीड़ा करने वाला, आत्मा में रमने वाला, (ज्ञान-)क्रियावान् — यही ब्रह्मवेत्ताओं में श्रेष्ठ है।',
          'This is the Life that shines through all beings. Knowing Him, the wise one does not talk beyond Him. Delighting in the Self, rejoicing in the Self, active in that knowledge — he is the best of the knowers of Brahman.'),
        M(['सत्येन लभ्यस्तपसा ह्येष आत्मा सम्यग्ज्ञानेन ब्रह्मचर्येण नित्यम्।', 'अन्तःशरीरे ज्योतिर्मयो हि शुभ्रो यं पश्यन्ति यतयः क्षीणदोषाः॥'],
          'यह आत्मा सत्य, तप, सम्यक् ज्ञान और नित्य ब्रह्मचर्य से प्राप्त होता है। वह शरीर के भीतर ज्योतिर्मय और शुद्ध है, जिसे दोषरहित यति देखते हैं।',
          'This Self is gained by truth, by austerity, by right knowledge and by constant chastity. He dwells within the body, made of light and pure; the strivers whose faults are worn away behold Him.'),
        M(['सत्यमेव जयते नानृतं सत्येन पन्था विततो देवयानः।', 'येनाऽऽक्रमन्त्यृषयो ह्याप्तकामा यत्र तत्सत्यस्य परमं निधानम्॥'],
          'सत्य की ही जय होती है, असत्य की नहीं। सत्य से ही देवयान मार्ग विस्तृत है, जिससे आप्तकाम ऋषि वहाँ जाते हैं जहाँ सत्य का परम निधान है।',
          'Truth alone prevails, not falsehood. By truth is laid out the path of the gods, by which the seers whose desires are fulfilled ascend to where the supreme treasure of truth abides.'),
        M(['बृहच्च तद्दिव्यमचिन्त्यरूपं सूक्ष्माच्च तत्सूक्ष्मतरं विभाति।', 'दूरात्सुदूरे तदिहान्तिके च पश्यत्स्विहैव निहितं गुहायाम्॥'],
          'वह महान्, दिव्य और अचिन्त्य रूप वाला है; वह सूक्ष्म से भी सूक्ष्मतर होकर प्रकाशित होता है। वह दूर से भी दूर है और यहाँ अत्यन्त निकट भी — देखने वालों के लिए यहीं हृदय-गुहा में स्थित है।',
          'Vast, divine, of unthinkable form, subtler than the subtle It shines forth. Farther than the far, yet here close at hand — for those who see, It rests here in the cave of the heart.'),
        M(['न चक्षुषा गृह्यते नापि वाचा नान्यैर्देवैस्तपसा कर्मणा वा।', 'ज्ञानप्रसादेन विशुद्धसत्त्वस्ततस्तु तं पश्यते निष्कलं ध्यायमानः॥'],
          'वह न नेत्र से ग्रहण किया जाता है, न वाणी से, न अन्य इन्द्रियों से, न तप या कर्म से। ज्ञान की निर्मलता से जिसका अन्तःकरण विशुद्ध हो गया है, वही ध्यान करता हुआ उस निरवयव को देखता है।',
          'He is not grasped by the eye, nor by speech, nor by the other senses, nor by austerity or works. Only one whose mind is purified by the serenity of knowledge sees Him, the partless, in meditation.'),
        M(['एषोऽणुरात्मा चेतसा वेदितव्यो यस्मिन्प्राणः पञ्चधा संविवेश।', 'प्राणैश्चित्तं सर्वमोतं प्रजानां यस्मिन्विशुद्धे विभवत्येष आत्मा॥'],
          'यह सूक्ष्म आत्मा (शुद्ध) चित्त से जानने योग्य है, जिसमें प्राण पाँच प्रकार से प्रविष्ट है। प्राणियों का समस्त चित्त प्राणों से ओतप्रोत है; उसके विशुद्ध होने पर यह आत्मा प्रकाशित होता है।',
          'This subtle Self is to be known by the mind into which the breath has entered fivefold. The whole mind of creatures is interwoven with the breaths; when that mind is purified, this Self shines forth.'),
        M(['यं यं लोकं मनसा संविभाति विशुद्धसत्त्वः कामयते यांश्च कामान्।', 'तं तं लोकं जयते तांश्च कामांस्तस्मादात्मज्ञं ह्यर्चयेत्भूतिकामः॥'],
          'विशुद्ध अन्तःकरण वाला (आत्मज्ञानी) जिस-जिस लोक का मन से संकल्प करता है और जिन-जिन कामनाओं को चाहता है, उस-उस लोक और उन कामनाओं को प्राप्त कर लेता है। इसलिए ऐश्वर्य चाहने वाला आत्मज्ञानी की पूजा करे।',
          'Whatever world the one of purified mind pictures in thought, whatever desires he desires — that world he wins and those desires. Therefore let one who seeks prosperity honour the knower of the Self.'),
      ],
      [
        M(['स वेदैतत्परमं ब्रह्म धाम यत्र विश्वं निहितं भाति शुभ्रम्।', 'उपासते पुरुषं ये ह्यकामास्ते शुक्रमेतदतिवर्तन्ति धीराः॥'],
          'वह (आत्मज्ञानी) इस परम ब्रह्मधाम को जानता है, जिसमें स्थित विश्व शुद्ध रूप में प्रकाशित होता है। जो निष्काम धीर पुरुष उस पुरुष की उपासना करते हैं, वे इस शुक्र (बीजरूप जन्म-कारण) को पार कर जाते हैं।',
          'He knows that supreme abode of Brahman in which the universe rests and shines pure. The wise who, free from desire, worship that Person pass beyond this seed of rebirth.'),
        M(['कामान्यः कामयते मन्यमानः स कामभिर्जायते तत्र तत्र।', 'पर्याप्तकामस्य कृतात्मनस्तु इहैव सर्वे प्रविलीयन्ति कामाः॥'],
          'जो (विषयों को) श्रेष्ठ मानकर कामनाएँ करता है, वह उन कामनाओं के साथ वहाँ-वहाँ जन्म लेता है। परन्तु जिसकी कामनाएँ पूर्ण हो गई हैं और जो कृतात्मा है, उसकी सब कामनाएँ यहीं विलीन हो जाती हैं।',
          'One who craves desires, dwelling on them, is born here and there through those desires. But for one whose desires are fulfilled and whose self is perfected, all desires dissolve here itself.'),
        M(['नायमात्मा प्रवचनेन लभ्यो न मेधया न बहुना श्रुतेन।', 'यमेवैष वृणुते तेन लभ्यस्तस्यैष आत्मा विवृणुते तनूं स्वाम्॥'],
          'यह आत्मा न प्रवचन से प्राप्त होता है, न बुद्धि से, न बहुत सुनने से। जिसे यह स्वयं वरण करता है, उसी से यह प्राप्त होता है; उसके लिए यह आत्मा अपना स्वरूप प्रकट कर देता है।',
          'This Self is not gained by discourse, nor by intellect, nor by much learning. It is gained by the one whom It chooses; to him this Self reveals Its own form.'),
        M(['नायमात्मा बलहीनेन लभ्यो न च प्रमादात्तपसो वाप्यलिङ्गात्।', 'एतैरुपायैर्यतते यस्तु विद्वांस्तस्यैष आत्मा विशते ब्रह्मधाम॥'],
          'यह आत्मा न बलहीन को प्राप्त होता है, न प्रमाद से, न लक्षणरहित (संन्यास-चिह्न से रहित) तप से। जो विद्वान् इन उपायों (बल, अप्रमाद, संन्यास) से प्रयत्न करता है, उसका यह आत्मा ब्रह्मधाम में प्रवेश करता है।',
          'This Self is not gained by the weak, nor through carelessness, nor by austerity without the marks of renunciation. But the wise one who strives by these means — his Self enters the abode of Brahman.'),
        M(['सम्प्राप्यैनमृषयो ज्ञानतृप्ताः कृतात्मानो वीतरागाः प्रशान्ताः।', 'ते सर्वगं सर्वतः प्राप्य धीरा युक्तात्मानः सर्वमेवाविशन्ति॥'],
          'ज्ञान से तृप्त, कृतात्मा, वीतराग और प्रशान्त ऋषि इसे प्राप्त कर, उस सर्वव्यापी को सर्वत्र पाकर, धीर और युक्तात्मा होकर सब में ही प्रवेश कर जाते हैं।',
          'Having attained Him, the seers — content with knowledge, perfected in self, free from passion, tranquil — find the all-pervading One everywhere and, wise and united in spirit, enter into the All.'),
        M(['वेदान्तविज्ञानसुनिश्चितार्थाः संन्यासयोगाद्यतयः शुद्धसत्त्वाः।', 'ते ब्रह्मलोकेषु परान्तकाले परामृताः परिमुच्यन्ति सर्वे॥'],
          'वेदान्त-विज्ञान से जिनका अर्थ (लक्ष्य) सुनिश्चित हो गया है, संन्यास-योग से जिनका अन्तःकरण शुद्ध हो गया है — वे यति परम अमृत होकर अन्तकाल में ब्रह्मलोकों में सब प्रकार से मुक्त हो जाते हैं।',
          'Those strivers who have ascertained the truth through the knowledge of Vedānta, whose minds are purified by the yoga of renunciation — they, at the final hour, become the supreme immortal and are wholly liberated in the worlds of Brahman.'),
        M(['गताः कलाः पञ्चदश प्रतिष्ठा देवाश्च सर्वे प्रतिदेवतासु।', 'कर्माणि विज्ञानमयश्च आत्मा परेऽव्यये सर्व एकीभवन्ति॥'],
          'पन्द्रह कलाएँ अपनी प्रतिष्ठाओं (कारणों) में चली जाती हैं, समस्त देव (इन्द्रियाँ) अपने-अपने अधिदेवताओं में; कर्म और विज्ञानमय आत्मा — ये सब उस परम अव्यय में एक हो जाते हैं।',
          'The fifteen parts go back to their sources, and all the senses to their presiding deities; one\'s works and the self made of knowledge — all become one in the supreme Imperishable.'),
        M(['यथा नद्यः स्यन्दमानाः समुद्रेऽस्तं गच्छन्ति नामरूपे विहाय।', 'तथा विद्वान्नामरूपाद्विमुक्तः परात्परं पुरुषमुपैति दिव्यम्॥'],
          'जैसे बहती हुई नदियाँ नाम-रूप छोड़कर समुद्र में विलीन हो जाती हैं, वैसे ही विद्वान् नाम-रूप से मुक्त होकर पर से भी पर दिव्य पुरुष को प्राप्त करता है।',
          'As flowing rivers disappear into the ocean, leaving name and form behind, so the knower, freed from name and form, reaches the divine Person, higher than the high.'),
        M(['स यो ह वै तत्परमं ब्रह्म वेद ब्रह्मैव भवति नास्याब्रह्मवित्कुले भवति।', 'तरति शोकं तरति पाप्मानं गुहाग्रन्थिभ्यो विमुक्तोऽमृतो भवति॥'],
          'जो उस परम ब्रह्म को जानता है, वह ब्रह्म ही हो जाता है; उसके कुल में कोई ब्रह्म को न जानने वाला नहीं होता। वह शोक को पार कर जाता है, पाप को पार कर जाता है, हृदय-गुहा की गाँठों से मुक्त होकर अमर हो जाता है।',
          'Whoever knows that supreme Brahman becomes Brahman indeed; in his family no one ignorant of Brahman is born. He crosses over sorrow, crosses over sin; freed from the knots of the heart, he becomes immortal.'),
        M(['तदेतदृचाऽभ्युक्तम्।', 'क्रियावन्तः श्रोत्रिया ब्रह्मनिष्ठाः स्वयं जुह्वत एकर्षिं श्रद्धयन्तः।', 'तेषामेवैतां ब्रह्मविद्यां वदेत शिरोव्रतं विधिवद्यैस्तु चीर्णम्॥'],
          'यही बात ऋचा में कही गई है — जो क्रियावान्, श्रोत्रिय और ब्रह्मनिष्ठ हैं, जो श्रद्धापूर्वक स्वयं एकर्षि (अग्नि) में हवन करते हैं, और जिन्होंने विधिपूर्वक शिरोव्रत का पालन किया है — उन्हीं को यह ब्रह्मविद्या कहे।',
          'This is declared in the verse: to those who perform the rites, who are learned in the Veda and devoted to Brahman, who with faith offer oblations themselves to the one Ṛṣi (the fire), and who have duly kept the vow of the head — to them alone let one teach this knowledge of Brahman.'),
        M(['तदेतत्सत्यमृषिरङ्गिराः पुरोवाच नैतदचीर्णव्रतोऽधीते।', 'नमः परमऋषिभ्यो नमः परमऋषिभ्यः॥'],
          'यह सत्य ऋषि अङ्गिरा ने पूर्वकाल में कहा। जिसने व्रत का पालन नहीं किया, वह इसे न पढ़े। परम ऋषियों को नमस्कार, परम ऋषियों को नमस्कार।',
          'This truth the seer Aṅgiras taught of old. Let no one who has not kept the vow study it. Salutation to the great seers; salutation to the great seers.'),
      ],
    ],
  ],
};
