// GENERATED by scripts/build-upanishad.mjs — do not edit. One loader per
// reviewed Upanishad, keyed by slug; native reads SQLite and web reads source JSON.
import type { UpanishadChapter } from './index';
import { readContent } from '../../storage/content';

export const upanishadTextLoaders: Readonly<Record<string, () => UpanishadChapter>> = {
};
