import assert from 'node:assert/strict';
import { test } from 'node:test';

import { nearestCity } from '../locations';
import {
  isPincodeCityId,
  isPincodeQuery,
  lookupPincode,
  nearestPincode,
  pincodeCityId,
  snapToNearestLocation,
  toDevanagariDigits,
  toPincodeLocation,
} from '../pincodes';
import pincodeData from '../pincodeData.json';

// Generated by `scripts/build-pincodes.mjs`; see that file for provenance and gates.
const INDIA = { latMin: 6.5, latMax: 37.6, lngMin: 68.0, lngMax: 97.5 };
const STRIDE = 7;

test('pincode table: shape matches what pincodes.ts assumes', () => {
  assert.equal(pincodeData.format, 1, 'format bump must be mirrored in pincodes.ts');
  assert.equal(pincodeData.stride, STRIDE);
  assert.equal(pincodeData.rows.length, pincodeData.count * STRIDE, 'flat array is count × stride');
  assert.ok(pincodeData.count > 18000, `expected 18k+ pincodes, got ${pincodeData.count}`);
  assert.equal(pincodeData.states.length, pincodeData.statesEn.length);
  assert.equal(pincodeData.states.length, pincodeData.statesHi.length);
});

test('pincode table: ascending order (binary search depends on it) and in-India coordinates', () => {
  let previous = -1;
  for (let row = 0; row < pincodeData.count; row += 1) {
    const at = row * STRIDE;
    const pin = pincodeData.rows[at];
    assert.ok(pin > previous, `pincodes must strictly ascend; ${pin} followed ${previous}`);
    previous = pin;

    const lat = pincodeData.rows[at + 1] / 1e4;
    const lng = pincodeData.rows[at + 2] / 1e4;
    assert.ok(pincodeData.talukas[pincodeData.rows[at + 4]] !== undefined, `pincode ${pin} has no taluka`);
    assert.ok(
      lat >= INDIA.latMin && lat <= INDIA.latMax && lng >= INDIA.lngMin && lng <= INDIA.lngMax,
      `pincode ${pin} at (${lat}, ${lng}) is outside India`
    );
  }
});

test('pincode table: every state carries a Devanagari name', () => {
  for (const [index, hi] of pincodeData.statesHi.entries()) {
    assert.ok(hi.length > 0 && /[ऀ-ॿ]/.test(hi), `${pincodeData.statesEn[index]} lacks a Devanagari name`);
  }
});

test('isPincodeQuery accepts only a 6-digit code that does not start with 0', () => {
  assert.equal(isPincodeQuery('416001'), true);
  assert.equal(isPincodeQuery('  416001  '), true, 'trims');
  assert.equal(isPincodeQuery('41600'), false, 'too short');
  assert.equal(isPincodeQuery('4160011'), false, 'too long');
  assert.equal(isPincodeQuery('016001'), false, 'no Indian pincode begins with 0');
  assert.equal(isPincodeQuery('kolhapur'), false);
  assert.equal(isPincodeQuery(''), false);
});

test('lookupPincode resolves Kolhapur — the case the city list could not serve', () => {
  const entry = lookupPincode('416001');
  assert.ok(entry, '416001 must resolve');
  assert.equal(entry.pincode, '416001');
  assert.equal(entry.districtEn, 'Kolhapur');
  assert.equal(entry.stateEn, 'Maharashtra');
  assert.equal(entry.stateHi, 'महाराष्ट्र');
  // Roughly the city; the source geocoder sits ~19 km SW of the Mahalakshmi temple.
  assert.ok(Math.abs(entry.latitude - 16.7) < 0.3, `lat ${entry.latitude}`);
  assert.ok(Math.abs(entry.longitude - 74.24) < 0.3, `lng ${entry.longitude}`);
});

test('lookupPincode spot-checks across the country', () => {
  const cases: [string, string, string][] = [
    ['110001', 'New Delhi', 'Delhi'],
    ['400001', 'Mumbai', 'Maharashtra'],
    ['560001', 'Bangalore', 'Karnataka'],
    ['456001', 'Ujjain', 'Madhya Pradesh'],
    ['781001', 'Kamrup', 'Assam'],
  ];
  for (const [pin, district, state] of cases) {
    const entry = lookupPincode(pin);
    assert.ok(entry, `${pin} must resolve`);
    assert.equal(entry.stateEn, state, `${pin} state`);
    assert.equal(entry.districtEn, district, `${pin} district`);
  }
});

test('taluka carries the familiar name when the district does not', () => {
  // Guwahati is a taluka of Kamrup district; showing only the district would hide the
  // one name a user actually recognises, which is why both ship.
  const guwahati = lookupPincode('781001')!;
  assert.equal(guwahati.districtEn, 'Kamrup');
  assert.equal(guwahati.talukaEn, 'Guwahati');

  // Kolhapur is the reverse — the district is the familiar name, the taluka is not.
  const kolhapur = lookupPincode('416001')!;
  assert.equal(kolhapur.districtEn, 'Kolhapur');
  assert.equal(kolhapur.talukaEn, 'Karvir');

  // And in Mumbai both are the same, which the picker collapses to one name.
  const mumbai = lookupPincode('400001')!;
  assert.equal(mumbai.districtEn, mumbai.talukaEn);
});

test('lookupPincode returns null for malformed and unknown codes', () => {
  assert.equal(lookupPincode('41600'), null);
  assert.equal(lookupPincode('abcdef'), null);
  assert.equal(lookupPincode(''), null);
  // Well-formed but not a real pincode — the 9xxxxx range is Army Post Office, absent here.
  assert.equal(lookupPincode('999999'), null);
});

test('toDevanagariDigits converts digits and leaves other characters alone', () => {
  assert.equal(toDevanagariDigits('416001'), '४१६००१');
  assert.equal(toDevanagariDigits('110001'), '११०००१');
  assert.equal(toDevanagariDigits('· x'), '· x');
});

test('pincode city ids are stable, prefixed, and recognised', () => {
  assert.equal(pincodeCityId('416001'), 'pin-416001');
  assert.equal(isPincodeCityId('pin-416001'), true);
  assert.equal(isPincodeCityId('pin-41600'), false);
  assert.equal(isPincodeCityId('pin-016001'), false);
  assert.equal(isPincodeCityId('ujjain'), false);
  assert.equal(isPincodeCityId('rj-mount-abu'), false);
});

test('toPincodeLocation labels in both scripts and keeps its source', () => {
  const entry = lookupPincode('416001')!;
  const location = toPincodeLocation(entry, 'pincode');
  assert.equal(location.cityId, 'pin-416001');
  assert.equal(location.labelEn, '416001 · Kolhapur, Maharashtra');
  assert.equal(location.labelHi, '४१६००१ · महाराष्ट्र');
  assert.ok(/[ऀ-ॿ]/.test(location.labelHi), 'Hindi label must be Devanagari so gu/kn transliteration works');
  assert.equal(location.source, 'pincode');
  assert.equal(location.latitude, entry.latitude);
  assert.equal(location.elevation, entry.elevation);
});

test('nearestPincode beats nearestCity where the city list is sparse', () => {
  // The Mahalakshmi temple, Kolhapur. Before the pincode tier this GPS fix snapped to
  // Panaji — a different state, ~135 km away, and Goa's sunrise.
  const lat = 16.7;
  const lng = 74.233;
  assert.equal(nearestCity(lat, lng).id, 'panaji', 'the old behaviour this tier replaces');

  const entry = nearestPincode(lat, lng);
  assert.ok(entry, 'a nearest pincode must exist');
  assert.equal(entry.stateEn, 'Maharashtra', 'must not cross into Goa');
  const km = Math.hypot((entry.latitude - lat) * 111, (entry.longitude - lng) * 111 * Math.cos((lat * Math.PI) / 180));
  assert.ok(km < 25, `nearest pincode should be close, was ${km.toFixed(0)} km`);
});

test('snapToNearestLocation returns a gps-sourced location', () => {
  const location = snapToNearestLocation(16.7, 74.233);
  assert.equal(location.source, 'gps');
  assert.ok(isPincodeCityId(location.cityId), `expected a pincode id, got ${location.cityId}`);
  assert.ok(location.labelEn.includes('Maharashtra'));
});

test('snapToNearestLocation keeps the CITY where pincode coverage is thin', () => {
  // The regression this guard exists for. The geocoder carries 1 of the directory's 207
  // Jammu & Kashmir pincodes, so Srinagar's "nearest" pincode is 156 km away in Doda while
  // the bundled Srinagar entry is right on top of the fix. Always preferring a pincode
  // would have made J&K users markedly worse off than before this tier shipped.
  const location = snapToNearestLocation(34.0837, 74.7973);
  assert.equal(location.cityId, 'srinagar', `expected the bundled city, got ${location.cityId}`);
  assert.equal(location.source, 'gps');

  // Ziro, Arunachal Pradesh: only 19 of 48 state pincodes are geocoded, and the closest
  // sits ~44 km away across the border in Assam — still closer than any bundled city, so
  // the pincode legitimately wins here.
  const ziro = snapToNearestLocation(27.63, 93.83);
  assert.ok(isPincodeCityId(ziro.cityId), `expected a pincode, got ${ziro.cityId}`);
});

test('nearestPincode still reports the raw nearest, guard or not', () => {
  const entry = nearestPincode(34.0837, 74.7973);
  assert.ok(entry, 'must resolve');
  assert.equal(entry.stateEn, 'Jammu & Kashmir', 'the lone geocoded J&K row');
});
